/**
 * Schema round-trip tests (fixtures = the examples shipped inside the vendor spec) for the 'redshift-data' bubble.
 *
 * GENERATED by @bubblelab/bubble-appgen from redshift-data.openapi.json — do not hand-edit;
 * re-run `pnpm --filter @bubblelab/bubble-appgen generate:redshift-data` instead.
 * Vendor docs: https://docs.aws.amazon.com/redshift-data/latest/APIReference/Welcome.html
 */

import { describe, expect, it } from 'vitest';
import {
  RedshiftDataParamsSchema,
  RedshiftDataResultSchema,
} from './redshift-data.schema.js';
import { REDSHIFT_DATA_OPERATION_METADATA } from './redshift-data.metadata.js';

describe('redshift-data generated contract', () => {
  it('execute_statement: accepts a spec-example request', () => {
    const result = RedshiftDataParamsSchema.safeParse({
      operation: 'execute_statement',
      endpointUrl: 'https://redshift-data.us-east-1.amazonaws.com',
      Sql: 'example',
    });
    expect(result.success).toBe(true);
  });

  it('execute_statement: rejects a type-corrupted request (Sql: number)', () => {
    const result = RedshiftDataParamsSchema.safeParse({
      operation: 'execute_statement',
      endpointUrl: 'https://redshift-data.us-east-1.amazonaws.com',
      Sql: 12345,
    });
    expect(result.success).toBe(false);
  });

  it('describe_statement: accepts a spec-example request', () => {
    const result = RedshiftDataParamsSchema.safeParse({
      operation: 'describe_statement',
      endpointUrl: 'https://redshift-data.us-east-1.amazonaws.com',
      Id: 'example',
    });
    expect(result.success).toBe(true);
  });

  it('describe_statement: rejects a type-corrupted request (Id: number)', () => {
    const result = RedshiftDataParamsSchema.safeParse({
      operation: 'describe_statement',
      endpointUrl: 'https://redshift-data.us-east-1.amazonaws.com',
      Id: 12345,
    });
    expect(result.success).toBe(false);
  });

  it('get_statement_result: accepts a spec-example request', () => {
    const result = RedshiftDataParamsSchema.safeParse({
      operation: 'get_statement_result',
      endpointUrl: 'https://redshift-data.us-east-1.amazonaws.com',
      Id: 'example',
    });
    expect(result.success).toBe(true);
  });

  it('get_statement_result: rejects a type-corrupted request (Id: number)', () => {
    const result = RedshiftDataParamsSchema.safeParse({
      operation: 'get_statement_result',
      endpointUrl: 'https://redshift-data.us-east-1.amazonaws.com',
      Id: 12345,
    });
    expect(result.success).toBe(false);
  });

  it('rejects requests missing the required endpointUrl', () => {
    const result = RedshiftDataParamsSchema.safeParse({
      operation: 'execute_statement',
      Sql: 'example',
    });
    expect(result.success).toBe(false);
  });

  it('rejects unknown operations', () => {
    const result = RedshiftDataParamsSchema.safeParse({
      operation: 'not_a_real_operation',
    });
    expect(result.success).toBe(false);
  });

  it('every schema operation has cited side-effect metadata (coverage guard)', () => {
    const operations = RedshiftDataParamsSchema.options.map(
      (option) => option.shape.operation.value
    );
    for (const operation of operations) {
      const entry = REDSHIFT_DATA_OPERATION_METADATA[operation];
      expect(entry, `missing metadata for ${operation}`).toBeDefined();
      expect(entry.citation.length).toBeGreaterThan(0);
      expect(entry.source.length).toBeGreaterThan(0);
    }
  });
});
