/**
 * Doc-grounded per-operation side-effect metadata (IR-8) for the 'redshift-data' bubble.
 *
 * GENERATED by @bubblelab/bubble-appgen from redshift-data.openapi.json — do not hand-edit;
 * re-run `pnpm --filter @bubblelab/bubble-appgen generate:redshift-data` instead.
 * Vendor docs: https://docs.aws.amazon.com/redshift-data/latest/APIReference/Welcome.html
 */

import type { BubbleOperationMetadata } from '@bubblelab/shared-schemas';

export const REDSHIFT_DATA_OPERATION_METADATA: BubbleOperationMetadata = {
  execute_statement: {
    sideEffect: 'write',
    destructive: false,
    idempotent: false,
    confidence: 0.85,
    source: 'openapi',
    citation:
      'redshift-data.openapi.json#/paths/~1#X-Amz-Target=RedshiftData.ExecuteStatement/post — "Runs an SQL statement, which can be data manipulation language (DML) or data definition language (DDL)." — carrier operation: executes caller-supplied SQL; fail-safe write until statement-level verb refinement is applied',
  },
  describe_statement: {
    sideEffect: 'read',
    destructive: false,
    idempotent: true,
    confidence: 0.85,
    source: 'openapi',
    citation:
      'redshift-data.openapi.json#/paths/~1#X-Amz-Target=RedshiftData.DescribeStatement/post — "Describes the details about a specific instance when a query was run by the Amazon Redshift Data API."',
  },
  get_statement_result: {
    sideEffect: 'read',
    destructive: false,
    idempotent: true,
    confidence: 0.85,
    source: 'openapi',
    citation:
      'redshift-data.openapi.json#/paths/~1#X-Amz-Target=RedshiftData.GetStatementResult/post — "Fetches the temporarily cached result of an SQL statement in JSON format."',
  },
};
