/**
 * ServiceBubble class (raw-fetch pattern) for the 'redshift-data' bubble.
 *
 * GENERATED by @bubblelab/bubble-appgen from redshift-data.openapi.json — do not hand-edit;
 * re-run `pnpm --filter @bubblelab/bubble-appgen generate:redshift-data` instead.
 * Vendor docs: https://docs.aws.amazon.com/redshift-data/latest/APIReference/Welcome.html
 */

import { ServiceBubble } from '../../../types/service-bubble-class.js';
import type { BubbleContext } from '../../../types/bubble.js';
import { CredentialType } from '@bubblelab/shared-schemas';
import { REDSHIFT_DATA_OPERATION_METADATA } from './redshift-data.metadata.js';
import {
  RedshiftDataParamsSchema,
  RedshiftDataResultSchema,
  ExecuteStatementPayloadSchema,
  DescribeStatementPayloadSchema,
  GetStatementResultPayloadSchema,
  type RedshiftDataParams,
  type RedshiftDataParamsInput,
  type RedshiftDataResult,
} from './redshift-data.schema.js';

/** Strip a trailing slash so path concatenation stays canonical. */
function trimBaseUrl(url: string): string {
  return url.endsWith('/') ? url.slice(0, -1) : url;
}

/** Drop undefined values before JSON body serialization. */
function pruneUndefined(
  record: Record<string, unknown>
): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(record)) {
    if (value !== undefined) out[key] = value;
  }
  return out;
}

export class RedshiftDataBubble<
  T extends RedshiftDataParamsInput = RedshiftDataParamsInput,
> extends ServiceBubble<
  T,
  Extract<RedshiftDataResult, { operation: T['operation'] }>
> {
  static readonly type = 'service' as const;
  static readonly service = 'redshift';
  static readonly authType = 'apikey' as const;
  static readonly bubbleName = 'redshift-data';
  static readonly operationMetadata = REDSHIFT_DATA_OPERATION_METADATA;
  static readonly schema = RedshiftDataParamsSchema;
  static readonly resultSchema = RedshiftDataResultSchema;
  static readonly shortDescription =
    'Amazon Redshift Data API integration generated from the official AWS Smithy model (execute SQL, poll statement status, fetch results). NOTE: live calls additionally require AWS SigV4 request signing, which the generated raw-fetch bearer pattern does not implement yet';
  static readonly longDescription = `
    Amazon Redshift Data API integration generated from the official AWS Smithy model (execute SQL, poll statement status, fetch results). NOTE: live calls additionally require AWS SigV4 request signing, which the generated raw-fetch bearer pattern does not implement yet

    Operations (generated from the vendor OpenAPI spec):
    - execute_statement [side-effect: write]: Runs an SQL statement, which can be data manipulation language (DML) or data definition language (DDL).
    - describe_statement [side-effect: read]: Describes the details about a specific instance when a query was run by the Amazon Redshift Data API.
    - get_statement_result [side-effect: read]: Fetches the temporarily cached result of an SQL statement in JSON format.

    Credential: REDSHIFT_DATA_CRED (bearer token) + per-account endpointUrl.
  `;
  static readonly alias = 'rs-data';

  constructor(
    params: T = {
      operation: 'describe_statement',
      endpointUrl: 'https://redshift-data.us-east-1.amazonaws.com',
      Id: 'example',
    } as T,
    context?: BubbleContext,
    instanceId?: string
  ) {
    super(params, context, instanceId);
  }

  private requestHeaders(
    token: string,
    hasBody: boolean
  ): Record<string, string> {
    const headers: Record<string, string> = {
      Authorization: `Bearer ${token}`,
      Accept: 'application/json',
      'User-Agent': 'bubblelab/1.0',
      'Content-Type': 'application/x-amz-json-1.1',
    };
    if (hasBody) headers['Content-Type'] ??= 'application/json';
    return headers;
  }

  public async testCredential(): Promise<boolean> {
    const token = this.chooseCredential();
    if (!token) {
      throw new Error('redshift-data credentials are required');
    }
    const params = { endpointUrl: this.params.endpointUrl };
    // Probe: POST /#X-Amz-Target=RedshiftData.DescribeStatement (describe_statement) with a synthesized handle.
    // 401/403 mean the credential was rejected; any other status means it was accepted.
    const response = await fetch(
      `${trimBaseUrl(params.endpointUrl)}/#X-Amz-Target=RedshiftData.DescribeStatement`,
      {
        method: 'POST',
        headers: {
          ...this.requestHeaders(token, true),
          'X-Amz-Target': 'RedshiftData.DescribeStatement',
        },
        body: JSON.stringify({ Id: 'example' }),
      }
    );
    return response.status !== 401 && response.status !== 403;
  }

  protected chooseCredential(): string | undefined {
    const credentials = this.params.credentials;
    if (!credentials || typeof credentials !== 'object') {
      return undefined;
    }
    return credentials[CredentialType.REDSHIFT_DATA_CRED];
  }

  protected async performAction(
    context?: BubbleContext
  ): Promise<Extract<RedshiftDataResult, { operation: T['operation'] }>> {
    void context;
    const { operation } = this.params;
    switch (operation) {
      case 'execute_statement':
        return this.handleExecuteStatement() as Promise<
          Extract<RedshiftDataResult, { operation: T['operation'] }>
        >;
      case 'describe_statement':
        return this.handleDescribeStatement() as Promise<
          Extract<RedshiftDataResult, { operation: T['operation'] }>
        >;
      case 'get_statement_result':
        return this.handleGetStatementResult() as Promise<
          Extract<RedshiftDataResult, { operation: T['operation'] }>
        >;
      default:
        return {
          operation: operation as T['operation'],
          success: false,
          error: `Unknown operation: ${String(operation)}`,
        } as Extract<RedshiftDataResult, { operation: T['operation'] }>;
    }
  }

  private async handleExecuteStatement(): Promise<
    Extract<RedshiftDataResult, { operation: 'execute_statement' }>
  > {
    const params = RedshiftDataParamsSchema.parse(this.params) as Extract<
      RedshiftDataParams,
      { operation: 'execute_statement' }
    >;
    try {
      const token = this.chooseCredential();
      if (!token) {
        return {
          operation: 'execute_statement',
          success: false,
          error: 'REDSHIFT_DATA_CRED credential not found',
        };
      }
      const url = `${trimBaseUrl(params.endpointUrl)}/#X-Amz-Target=RedshiftData.ExecuteStatement`;
      const body = pruneUndefined({
        Sql: params.Sql,
        ClusterIdentifier: params.ClusterIdentifier,
        SecretArn: params.SecretArn,
        DbUser: params.DbUser,
        Database: params.Database,
        WithEvent: params.WithEvent,
        StatementName: params.StatementName,
        Parameters: params.Parameters,
        WorkgroupName: params.WorkgroupName,
        ClientToken: params.ClientToken,
        ResultFormat: params.ResultFormat,
        SessionKeepAliveSeconds: params.SessionKeepAliveSeconds,
        SessionId: params.SessionId,
      });
      const response = await fetch(url, {
        method: 'POST',
        headers: {
          ...this.requestHeaders(token, true),
          'X-Amz-Target': 'RedshiftData.ExecuteStatement',
        },
        body: JSON.stringify(body),
      });
      if (!response.ok) {
        const errorText = await response.text();
        return {
          operation: 'execute_statement',
          success: false,
          error: `redshift-data API error (${response.status}): ${errorText}`,
        };
      }
      const payload = ExecuteStatementPayloadSchema.parse(
        await response.json()
      );
      return {
        operation: 'execute_statement',
        success: true,
        error: '',
        ...payload,
      };
    } catch (error) {
      return {
        operation: 'execute_statement',
        success: false,
        error:
          error instanceof Error ? error.message : 'Unknown error occurred',
      };
    }
  }

  private async handleDescribeStatement(): Promise<
    Extract<RedshiftDataResult, { operation: 'describe_statement' }>
  > {
    const params = RedshiftDataParamsSchema.parse(this.params) as Extract<
      RedshiftDataParams,
      { operation: 'describe_statement' }
    >;
    try {
      const token = this.chooseCredential();
      if (!token) {
        return {
          operation: 'describe_statement',
          success: false,
          error: 'REDSHIFT_DATA_CRED credential not found',
        };
      }
      const url = `${trimBaseUrl(params.endpointUrl)}/#X-Amz-Target=RedshiftData.DescribeStatement`;
      const body = pruneUndefined({
        Id: params.Id,
      });
      const response = await fetch(url, {
        method: 'POST',
        headers: {
          ...this.requestHeaders(token, true),
          'X-Amz-Target': 'RedshiftData.DescribeStatement',
        },
        body: JSON.stringify(body),
      });
      if (!response.ok) {
        const errorText = await response.text();
        return {
          operation: 'describe_statement',
          success: false,
          error: `redshift-data API error (${response.status}): ${errorText}`,
        };
      }
      const payload = DescribeStatementPayloadSchema.parse(
        await response.json()
      );
      return {
        operation: 'describe_statement',
        success: true,
        error: '',
        ...payload,
      };
    } catch (error) {
      return {
        operation: 'describe_statement',
        success: false,
        error:
          error instanceof Error ? error.message : 'Unknown error occurred',
      };
    }
  }

  private async handleGetStatementResult(): Promise<
    Extract<RedshiftDataResult, { operation: 'get_statement_result' }>
  > {
    const params = RedshiftDataParamsSchema.parse(this.params) as Extract<
      RedshiftDataParams,
      { operation: 'get_statement_result' }
    >;
    try {
      const token = this.chooseCredential();
      if (!token) {
        return {
          operation: 'get_statement_result',
          success: false,
          error: 'REDSHIFT_DATA_CRED credential not found',
        };
      }
      const url = `${trimBaseUrl(params.endpointUrl)}/#X-Amz-Target=RedshiftData.GetStatementResult`;
      const body = pruneUndefined({
        Id: params.Id,
        NextToken: params.NextToken,
      });
      const response = await fetch(url, {
        method: 'POST',
        headers: {
          ...this.requestHeaders(token, true),
          'X-Amz-Target': 'RedshiftData.GetStatementResult',
        },
        body: JSON.stringify(body),
      });
      if (!response.ok) {
        const errorText = await response.text();
        return {
          operation: 'get_statement_result',
          success: false,
          error: `redshift-data API error (${response.status}): ${errorText}`,
        };
      }
      const payload = GetStatementResultPayloadSchema.parse(
        await response.json()
      );
      return {
        operation: 'get_statement_result',
        success: true,
        error: '',
        ...payload,
      };
    } catch (error) {
      return {
        operation: 'get_statement_result',
        success: false,
        error:
          error instanceof Error ? error.message : 'Unknown error occurred',
      };
    }
  }
}
