/**
 * Zod contract (params + results) for the 'redshift-data' bubble.
 *
 * GENERATED by @bubblelab/bubble-appgen from redshift-data.openapi.json — do not hand-edit;
 * re-run `pnpm --filter @bubblelab/bubble-appgen generate:redshift-data` instead.
 * Vendor docs: https://docs.aws.amazon.com/redshift-data/latest/APIReference/Welcome.html
 */

import { z } from 'zod';
import { CredentialType } from '@bubblelab/shared-schemas';

// Base credentials schema shared by every operation branch
const BaseCredentialsSchema = z
  .record(z.nativeEnum(CredentialType), z.string())
  .optional()
  .describe('Object mapping credential types to values (injected at runtime)');

/** Documented 2xx response payload of ExecuteStatement (statuses: 200); all fields optional because presence varies by status code. */
export const ExecuteStatementPayloadSchema = z.object({
  Id: z
    .string()
    .describe(
      'The identifier of the SQL statement whose results are to be fetched. This value is a universally unique identifier (UUID) generated by Amazon Redshift Data API.'
    )
    .optional(),
  CreatedAt: z
    .number()
    .describe(
      'The date and time (UTC) the statement was created. (awsJson1_1 timestamp: epoch seconds)'
    )
    .optional(),
  ClusterIdentifier: z
    .string()
    .min(1)
    .max(63)
    .describe(
      'The cluster identifier. This element is not returned when connecting to a serverless workgroup.'
    )
    .optional(),
  DbUser: z.string().describe('The database user name.').optional(),
  DbGroups: z
    .array(z.string())
    .describe('A list of colon (:) separated names of database groups.')
    .optional(),
  Database: z.string().describe('The name of the database.').optional(),
  SecretArn: z
    .string()
    .describe(
      'The name or ARN of the secret that enables access to the database.'
    )
    .optional(),
  WorkgroupName: z
    .string()
    .min(3)
    .max(128)
    .describe(
      'The serverless workgroup name or Amazon Resource Name (ARN). This element is not returned when connecting to a provisioned cluster.'
    )
    .optional(),
  SessionId: z
    .string()
    .describe('The session identifier of the query.')
    .optional(),
});

/** Documented 2xx response payload of DescribeStatement (statuses: 200); all fields optional because presence varies by status code. */
export const DescribeStatementPayloadSchema = z.object({
  Id: z
    .string()
    .describe(
      'The identifier of the SQL statement described. This value is a universally unique identifier (UUID) generated by Amazon Redshift Data API.'
    )
    .optional(),
  SecretArn: z
    .string()
    .describe(
      'The name or Amazon Resource Name (ARN) of the secret that enables access to the database.'
    )
    .optional(),
  DbUser: z.string().describe('The database user name.').optional(),
  Database: z.string().describe('The name of the database.').optional(),
  ClusterIdentifier: z.string().describe('The cluster identifier.').optional(),
  Duration: z
    .number()
    .int()
    .describe('The amount of time in nanoseconds that the statement ran.')
    .optional(),
  Error: z
    .string()
    .describe(
      'The error message from the cluster if the SQL statement encountered an error while running.'
    )
    .optional(),
  Status: z
    .enum([
      'SUBMITTED',
      'PICKED',
      'STARTED',
      'FINISHED',
      'ABORTED',
      'FAILED',
      'ALL',
    ])
    .describe(
      'The status of the SQL statement being described. Status values are defined as follows: ABORTED - The query run was stopped by the user. ALL - A status value that includes all query statuses. This value can be used to filter results. FAILED - The query run failed. FINISHED - The query has finished running. PICKED - The query has been chosen to be run. STARTED - The query run has started. SUBMITTED - The query was submitted, but not yet processed.'
    )
    .optional(),
  CreatedAt: z
    .number()
    .describe(
      'The date and time (UTC) when the SQL statement was submitted to run. (awsJson1_1 timestamp: epoch seconds)'
    )
    .optional(),
  UpdatedAt: z
    .number()
    .describe(
      'The date and time (UTC) that the metadata for the SQL statement was last updated. An example is the time the status last changed. (awsJson1_1 timestamp: epoch seconds)'
    )
    .optional(),
  RedshiftPid: z
    .number()
    .int()
    .describe('The process identifier from Amazon Redshift.')
    .optional(),
  HasResultSet: z
    .boolean()
    .describe(
      'A value that indicates whether the statement has a result set. The result set can be empty. The value is true for an empty result set. The value is true if any substatement returns a result set.'
    )
    .optional(),
  QueryString: z.string().describe('The SQL statement text.').optional(),
  ResultRows: z
    .number()
    .int()
    .describe(
      'Either the number of rows returned from the SQL statement or the number of rows affected. If result size is greater than zero, the result rows can be the number of rows affected by SQL statements such as INSERT, UPDATE, DELETE, COPY, and others. A -1 indicates the value is null.'
    )
    .optional(),
  ResultSize: z
    .number()
    .int()
    .describe(
      'The size in bytes of the returned results. A -1 indicates the value is null.'
    )
    .optional(),
  RedshiftQueryId: z
    .number()
    .int()
    .describe(
      'The identifier of the query generated by Amazon Redshift. These identifiers are also available in the query column of the STL_QUERY system view.'
    )
    .optional(),
  QueryParameters: z
    .array(
      z
        .object({
          name: z.string().describe('The name of the parameter.'),
          value: z
            .string()
            .min(1)
            .describe(
              'The value of the parameter. Amazon Redshift implicitly converts to the proper data type. For more information, see Data types in the Amazon Redshift Database Developer Guide .'
            ),
        })
        .describe('A parameter used in a SQL statement.')
    )
    .describe('The parameters for the SQL statement.')
    .optional(),
  SubStatements: z
    .array(
      z
        .object({
          Id: z
            .string()
            .describe(
              'The identifier of the SQL statement. This value is a universally unique identifier (UUID) generated by Amazon Redshift Data API. A suffix indicates the number of the SQL statement. For example, d9b6c0c9-0747-4bf4-b142-e8883122f766:2 has a suffix of :2 that indicates the second SQL statement of a batch query.'
            ),
          Duration: z
            .number()
            .int()
            .describe(
              'The amount of time in nanoseconds that the statement ran.'
            )
            .optional(),
          Error: z
            .string()
            .describe(
              'The error message from the cluster if the SQL statement encountered an error while running.'
            )
            .optional(),
          Status: z
            .enum([
              'SUBMITTED',
              'PICKED',
              'STARTED',
              'FINISHED',
              'ABORTED',
              'FAILED',
            ])
            .describe(
              'The status of the SQL statement. An example is the that the SQL statement finished.'
            )
            .optional(),
          CreatedAt: z
            .number()
            .describe(
              'The date and time (UTC) the statement was created. (awsJson1_1 timestamp: epoch seconds)'
            )
            .optional(),
          UpdatedAt: z
            .number()
            .describe(
              'The date and time (UTC) that the statement metadata was last updated. (awsJson1_1 timestamp: epoch seconds)'
            )
            .optional(),
          QueryString: z
            .string()
            .describe('The SQL statement text.')
            .optional(),
          ResultRows: z
            .number()
            .int()
            .describe(
              'Either the number of rows returned from the SQL statement or the number of rows affected. If result size is greater than zero, the result rows can be the number of rows affected by SQL statements such as INSERT, UPDATE, DELETE, COPY, and others. A -1 indicates the value is null.'
            )
            .optional(),
          ResultSize: z
            .number()
            .int()
            .describe(
              'The size in bytes of the returned results. A -1 indicates the value is null.'
            )
            .optional(),
          RedshiftQueryId: z
            .number()
            .int()
            .describe(
              'The SQL statement identifier. This value is a universally unique identifier (UUID) generated by Amazon Redshift Data API.'
            )
            .optional(),
          HasResultSet: z
            .boolean()
            .describe(
              'A value that indicates whether the statement has a result set. The result set can be empty. The value is true for an empty result set.'
            )
            .optional(),
        })
        .describe('Information about an SQL statement.')
    )
    .describe('The SQL statements from a multiple statement run.')
    .optional(),
  WorkgroupName: z
    .string()
    .min(3)
    .max(128)
    .describe('The serverless workgroup name or Amazon Resource Name (ARN).')
    .optional(),
  ResultFormat: z
    .enum(['JSON', 'CSV'])
    .describe('The data format of the result of the SQL statement.')
    .optional(),
  SessionId: z
    .string()
    .describe('The session identifier of the query.')
    .optional(),
});

/** Documented 2xx response payload of GetStatementResult (statuses: 200); all fields optional because presence varies by status code. */
export const GetStatementResultPayloadSchema = z.object({
  Records: z
    .array(
      z.array(
        z
          .object({
            isNull: z
              .boolean()
              .describe('A value that indicates whether the data is NULL.')
              .optional(),
            booleanValue: z
              .boolean()
              .describe('A value of the Boolean data type.')
              .optional(),
            longValue: z
              .number()
              .int()
              .describe('A value of the long data type.')
              .optional(),
            doubleValue: z
              .number()
              .describe('A value of the double data type.')
              .optional(),
            stringValue: z
              .string()
              .describe('A value of the string data type.')
              .optional(),
            blobValue: z.string().describe('base64-encoded binary').optional(),
          })
          .describe(
            'Tagged union: exactly one member is set. A data value in a column.'
          )
      )
    )
    .describe('The results of the SQL statement in JSON format.')
    .optional(),
  ColumnMetadata: z
    .array(
      z
        .object({
          isCaseSensitive: z
            .boolean()
            .describe(
              'A value that indicates whether the column is case-sensitive.'
            )
            .optional(),
          isCurrency: z
            .boolean()
            .describe(
              'A value that indicates whether the column contains currency values.'
            )
            .optional(),
          isSigned: z
            .boolean()
            .describe(
              'A value that indicates whether an integer column is signed.'
            )
            .optional(),
          label: z.string().describe('The label for the column.').optional(),
          name: z.string().describe('The name of the column.').optional(),
          nullable: z
            .number()
            .int()
            .describe('A value that indicates whether the column is nullable.')
            .optional(),
          precision: z
            .number()
            .int()
            .describe(
              'The precision value of a decimal number column, or the column length for a non-numeric column.'
            )
            .optional(),
          scale: z
            .number()
            .int()
            .describe('The scale value of a decimal number column.')
            .optional(),
          schemaName: z
            .string()
            .describe(
              'The name of the schema that contains the table that includes the column.'
            )
            .optional(),
          tableName: z
            .string()
            .describe('The name of the table that includes the column.')
            .optional(),
          typeName: z
            .string()
            .describe('The database-specific data type of the column.')
            .optional(),
          length: z
            .number()
            .int()
            .describe('The length of the column.')
            .optional(),
          columnDefault: z
            .string()
            .describe('The default value of the column.')
            .optional(),
        })
        .describe('The properties (metadata) of a column.')
    )
    .describe('The properties (metadata) of a column.')
    .optional(),
  TotalNumRows: z
    .number()
    .int()
    .describe(
      'The total number of rows in the result set returned from a query. You can use this number to estimate the number of calls to the GetStatementResult operation needed to page through the results.'
    )
    .optional(),
  NextToken: z
    .string()
    .describe(
      'A value that indicates the starting point for the next set of response records in a subsequent request. If a value is returned in a response, you can retrieve the next set of records by providing this returned NextToken value in the next NextToken parameter and retrying the command. If the NextToken field is empty, all response records have been retrieved for the request.'
    )
    .optional(),
});

export const RedshiftDataParamsSchema = z.discriminatedUnion('operation', [
  z.object({
    operation: z
      .literal('execute_statement')
      .describe(
        'Runs an SQL statement, which can be data manipulation language (DML) or data definition language (DDL).'
      ),
    endpointUrl: z
      .string()
      .url()
      .describe(
        'Regional Redshift Data API endpoint (e.g. https://redshift-data.us-east-1.amazonaws.com)'
      ),
    Sql: z.string().describe('The SQL statement text to run.'),
    ClusterIdentifier: z
      .string()
      .min(1)
      .max(63)
      .describe(
        'The cluster identifier. This parameter is required when connecting to a cluster and authenticating using either Secrets Manager or temporary credentials.'
      )
      .optional(),
    SecretArn: z
      .string()
      .describe(
        'The name or ARN of the secret that enables access to the database. This parameter is required when authenticating using Secrets Manager.'
      )
      .optional(),
    DbUser: z
      .string()
      .describe(
        'The database user name. This parameter is required when connecting to a cluster as a database user and authenticating using temporary credentials.'
      )
      .optional(),
    Database: z
      .string()
      .describe(
        'The name of the database. This parameter is required when authenticating using either Secrets Manager or temporary credentials.'
      )
      .optional(),
    WithEvent: z
      .boolean()
      .describe(
        'A value that indicates whether to send an event to the Amazon EventBridge event bus after the SQL statement runs.'
      )
      .optional(),
    StatementName: z
      .string()
      .max(2048)
      .describe(
        'The name of the SQL statement. You can name the SQL statement when you create it to identify the query.'
      )
      .optional(),
    Parameters: z
      .array(
        z
          .object({
            name: z.string().describe('The name of the parameter.'),
            value: z
              .string()
              .min(1)
              .describe(
                'The value of the parameter. Amazon Redshift implicitly converts to the proper data type. For more information, see Data types in the Amazon Redshift Database Developer Guide .'
              ),
          })
          .describe('A parameter used in a SQL statement.')
      )
      .describe('The parameters for the SQL statement.')
      .optional(),
    WorkgroupName: z
      .string()
      .min(3)
      .max(128)
      .describe(
        'The serverless workgroup name or Amazon Resource Name (ARN). This parameter is required when connecting to a serverless workgroup and authenticating using either Secrets Manager or temporary credentials.'
      )
      .optional(),
    ClientToken: z
      .string()
      .min(1)
      .max(64)
      .describe(
        'A unique, case-sensitive identifier that you provide to ensure the idempotency of the request.'
      )
      .optional(),
    ResultFormat: z
      .enum(['JSON', 'CSV'])
      .describe(
        'The data format of the result of the SQL statement. If no format is specified, the default is JSON.'
      )
      .optional(),
    SessionKeepAliveSeconds: z
      .number()
      .int()
      .min(0)
      .max(86400)
      .describe(
        'The number of seconds to keep the session alive after the query finishes. The maximum time a session can keep alive is 24 hours. After 24 hours, the session is forced closed and the query is terminated.'
      )
      .optional(),
    SessionId: z
      .string()
      .describe('The session identifier of the query.')
      .optional(),
    credentials: BaseCredentialsSchema,
  }),
  z.object({
    operation: z
      .literal('describe_statement')
      .describe(
        'Describes the details about a specific instance when a query was run by the Amazon Redshift Data API.'
      ),
    endpointUrl: z
      .string()
      .url()
      .describe(
        'Regional Redshift Data API endpoint (e.g. https://redshift-data.us-east-1.amazonaws.com)'
      ),
    Id: z
      .string()
      .describe(
        'The identifier of the SQL statement to describe. This value is a universally unique identifier (UUID) generated by Amazon Redshift Data API. A suffix indicates the number of the SQL statement. For example, d9b6c0c9-0747-4bf4-b142-e8883122f766:2 has a suffix of :2 that indicates the second SQL statement of a batch query. This identifier is returned by BatchExecuteStatment , ExecuteStatement , and ListStatements .'
      ),
    credentials: BaseCredentialsSchema,
  }),
  z.object({
    operation: z
      .literal('get_statement_result')
      .describe(
        'Fetches the temporarily cached result of an SQL statement in JSON format.'
      ),
    endpointUrl: z
      .string()
      .url()
      .describe(
        'Regional Redshift Data API endpoint (e.g. https://redshift-data.us-east-1.amazonaws.com)'
      ),
    Id: z
      .string()
      .describe(
        'The identifier of the SQL statement whose results are to be fetched. This value is a universally unique identifier (UUID) generated by Amazon Redshift Data API. A suffix indicates then number of the SQL statement. For example, d9b6c0c9-0747-4bf4-b142-e8883122f766:2 has a suffix of :2 that indicates the second SQL statement of a batch query. This identifier is returned by BatchExecuteStatment , ExecuteStatment , and ListStatements .'
      ),
    NextToken: z
      .string()
      .describe(
        'A value that indicates the starting point for the next set of response records in a subsequent request. If a value is returned in a response, you can retrieve the next set of records by providing this returned NextToken value in the next NextToken parameter and retrying the command. If the NextToken field is empty, all response records have been retrieved for the request.'
      )
      .optional(),
    credentials: BaseCredentialsSchema,
  }),
]);

export const RedshiftDataResultSchema = z.discriminatedUnion('operation', [
  z
    .object({
      operation: z.literal('execute_statement'),
      success: z.boolean().describe('Whether the operation succeeded'),
      error: z.string().describe('Error message if operation failed'),
    })
    .merge(ExecuteStatementPayloadSchema),
  z
    .object({
      operation: z.literal('describe_statement'),
      success: z.boolean().describe('Whether the operation succeeded'),
      error: z.string().describe('Error message if operation failed'),
    })
    .merge(DescribeStatementPayloadSchema),
  z
    .object({
      operation: z.literal('get_statement_result'),
      success: z.boolean().describe('Whether the operation succeeded'),
      error: z.string().describe('Error message if operation failed'),
    })
    .merge(GetStatementResultPayloadSchema),
]);

export type RedshiftDataParamsInput = z.input<typeof RedshiftDataParamsSchema>;
export type RedshiftDataParams = z.output<typeof RedshiftDataParamsSchema>;
export type RedshiftDataResult = z.output<typeof RedshiftDataResultSchema>;

export type RedshiftDataExecuteStatementParams = Extract<
  RedshiftDataParamsInput,
  { operation: 'execute_statement' }
>;
export type RedshiftDataDescribeStatementParams = Extract<
  RedshiftDataParamsInput,
  { operation: 'describe_statement' }
>;
export type RedshiftDataGetStatementResultParams = Extract<
  RedshiftDataParamsInput,
  { operation: 'get_statement_result' }
>;

export type RedshiftDataOperationResult<
  T extends RedshiftDataParams['operation'],
> = Extract<RedshiftDataResult, { operation: T }>;
