/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as HomeRouteImport } from './routes/home'
import { Route as FlowsRouteImport } from './routes/flows'
import { Route as CredentialsRouteImport } from './routes/credentials'
import { Route as AddToolRouteImport } from './routes/add-tool'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuildIndexRouteImport } from './routes/build.index'
import { Route as BuildPageIndexRouteImport } from './routes/build-page.index'
import { Route as PagePageIdRouteImport } from './routes/page.$pageId'
import { Route as FlowFlowIdRouteImport } from './routes/flow.$flowId'
import { Route as BuildFlowIdRouteImport } from './routes/build.$flowId'
import { Route as BuildPagePageIdRouteImport } from './routes/build-page.$pageId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowsRoute = FlowsRouteImport.update({
  id: '/flows',
  path: '/flows',
  getParentRoute: () => rootRouteImport,
} as any)
const CredentialsRoute = CredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const AddToolRoute = AddToolRouteImport.update({
  id: '/add-tool',
  path: '/add-tool',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildIndexRoute = BuildIndexRouteImport.update({
  id: '/build/',
  path: '/build/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildPageIndexRoute = BuildPageIndexRouteImport.update({
  id: '/build-page/',
  path: '/build-page/',
  getParentRoute: () => rootRouteImport,
} as any)
const PagePageIdRoute = PagePageIdRouteImport.update({
  id: '/page/$pageId',
  path: '/page/$pageId',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowFlowIdRoute = FlowFlowIdRouteImport.update({
  id: '/flow/$flowId',
  path: '/flow/$flowId',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildFlowIdRoute = BuildFlowIdRouteImport.update({
  id: '/build/$flowId',
  path: '/build/$flowId',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildPagePageIdRoute = BuildPagePageIdRouteImport.update({
  id: '/build-page/$pageId',
  path: '/build-page/$pageId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-tool': typeof AddToolRoute
  '/credentials': typeof CredentialsRoute
  '/flows': typeof FlowsRoute
  '/home': typeof HomeRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/build-page/$pageId': typeof BuildPagePageIdRoute
  '/build/$flowId': typeof BuildFlowIdRoute
  '/flow/$flowId': typeof FlowFlowIdRoute
  '/page/$pageId': typeof PagePageIdRoute
  '/build-page': typeof BuildPageIndexRoute
  '/build': typeof BuildIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-tool': typeof AddToolRoute
  '/credentials': typeof CredentialsRoute
  '/flows': typeof FlowsRoute
  '/home': typeof HomeRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/build-page/$pageId': typeof BuildPagePageIdRoute
  '/build/$flowId': typeof BuildFlowIdRoute
  '/flow/$flowId': typeof FlowFlowIdRoute
  '/page/$pageId': typeof PagePageIdRoute
  '/build-page': typeof BuildPageIndexRoute
  '/build': typeof BuildIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-tool': typeof AddToolRoute
  '/credentials': typeof CredentialsRoute
  '/flows': typeof FlowsRoute
  '/home': typeof HomeRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/build-page/$pageId': typeof BuildPagePageIdRoute
  '/build/$flowId': typeof BuildFlowIdRoute
  '/flow/$flowId': typeof FlowFlowIdRoute
  '/page/$pageId': typeof PagePageIdRoute
  '/build-page/': typeof BuildPageIndexRoute
  '/build/': typeof BuildIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-tool'
    | '/credentials'
    | '/flows'
    | '/home'
    | '/pricing'
    | '/settings'
    | '/build-page/$pageId'
    | '/build/$flowId'
    | '/flow/$flowId'
    | '/page/$pageId'
    | '/build-page'
    | '/build'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-tool'
    | '/credentials'
    | '/flows'
    | '/home'
    | '/pricing'
    | '/settings'
    | '/build-page/$pageId'
    | '/build/$flowId'
    | '/flow/$flowId'
    | '/page/$pageId'
    | '/build-page'
    | '/build'
  id:
    | '__root__'
    | '/'
    | '/add-tool'
    | '/credentials'
    | '/flows'
    | '/home'
    | '/pricing'
    | '/settings'
    | '/build-page/$pageId'
    | '/build/$flowId'
    | '/flow/$flowId'
    | '/page/$pageId'
    | '/build-page/'
    | '/build/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddToolRoute: typeof AddToolRoute
  CredentialsRoute: typeof CredentialsRoute
  FlowsRoute: typeof FlowsRoute
  HomeRoute: typeof HomeRoute
  PricingRoute: typeof PricingRoute
  SettingsRoute: typeof SettingsRoute
  BuildPagePageIdRoute: typeof BuildPagePageIdRoute
  BuildFlowIdRoute: typeof BuildFlowIdRoute
  FlowFlowIdRoute: typeof FlowFlowIdRoute
  PagePageIdRoute: typeof PagePageIdRoute
  BuildPageIndexRoute: typeof BuildPageIndexRoute
  BuildIndexRoute: typeof BuildIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flows': {
      id: '/flows'
      path: '/flows'
      fullPath: '/flows'
      preLoaderRoute: typeof FlowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credentials': {
      id: '/credentials'
      path: '/credentials'
      fullPath: '/credentials'
      preLoaderRoute: typeof CredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-tool': {
      id: '/add-tool'
      path: '/add-tool'
      fullPath: '/add-tool'
      preLoaderRoute: typeof AddToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build/': {
      id: '/build/'
      path: '/build'
      fullPath: '/build'
      preLoaderRoute: typeof BuildIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build-page/': {
      id: '/build-page/'
      path: '/build-page'
      fullPath: '/build-page'
      preLoaderRoute: typeof BuildPageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/page/$pageId': {
      id: '/page/$pageId'
      path: '/page/$pageId'
      fullPath: '/page/$pageId'
      preLoaderRoute: typeof PagePageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flow/$flowId': {
      id: '/flow/$flowId'
      path: '/flow/$flowId'
      fullPath: '/flow/$flowId'
      preLoaderRoute: typeof FlowFlowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build/$flowId': {
      id: '/build/$flowId'
      path: '/build/$flowId'
      fullPath: '/build/$flowId'
      preLoaderRoute: typeof BuildFlowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build-page/$pageId': {
      id: '/build-page/$pageId'
      path: '/build-page/$pageId'
      fullPath: '/build-page/$pageId'
      preLoaderRoute: typeof BuildPagePageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddToolRoute: AddToolRoute,
  CredentialsRoute: CredentialsRoute,
  FlowsRoute: FlowsRoute,
  HomeRoute: HomeRoute,
  PricingRoute: PricingRoute,
  SettingsRoute: SettingsRoute,
  BuildPagePageIdRoute: BuildPagePageIdRoute,
  BuildFlowIdRoute: BuildFlowIdRoute,
  FlowFlowIdRoute: FlowFlowIdRoute,
  PagePageIdRoute: PagePageIdRoute,
  BuildPageIndexRoute: BuildPageIndexRoute,
  BuildIndexRoute: BuildIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
