/**
 * Code generation (ADD-ANY-APP S6): OperationDrafts + classifications ->
 * the compliance-target file set from ADD-ANY-APP section 1:
 *
 *   <app>.schema.ts    Zod params discriminated union + result schemas
 *   <app>.ts           class <App>Bubble extends ServiceBubble (raw fetch)
 *   <app>.metadata.ts  doc-grounded side-effect map, cited
 *   <app>.schema.test.ts  spec-example round-trips + coverage guard
 *   index.ts           exports
 *
 * Emitted code contains no `as any` and must pass repo typecheck as-is.
 */
import type { OperationSideEffectMetadata } from '@bubblelab/shared-schemas';
import type { AuthInference } from './auth-infer.js';
import type { AppGenConfig, OperationDraft } from './types.js';
import {
  emitKey,
  exampleFor,
  zodFor,
  zodForOptionalObject,
} from './zod-emit.js';

export interface GeneratedFile {
  fileName: string;
  content: string;
}

function pascal(snake: string): string {
  return snake
    .split(/[_-]/)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

function upperSnake(kebab: string): string {
  return kebab.replace(/-/g, '_').toUpperCase();
}

/** `params.name` or `params['x-y']` depending on identifier validity. */
function paramAccess(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name)
    ? `params.${name}`
    : `params[${JSON.stringify(name)}]`;
}

function generatedHeader(config: AppGenConfig, what: string): string {
  return [
    '/**',
    ` * ${what} for the '${config.appName}' bubble.`,
    ' *',
    ` * GENERATED by @bubblelab/bubble-appgen from ${config.specName} — do not hand-edit;`,
    ` * re-run \`pnpm --filter @bubblelab/bubble-appgen generate:${config.appName}\` instead.`,
    ...(config.docsUrl ? [` * Vendor docs: ${config.docsUrl}`] : []),
    ' */',
  ].join('\n');
}

// ── <app>.schema.ts ───────────────────────────────────────────────────────────

function emitParamsBranch(config: AppGenConfig, draft: OperationDraft): string {
  const summary = (draft.summary ?? draft.description ?? draft.name).trim();
  const lines: string[] = [];
  lines.push('  z.object({');
  lines.push(
    `    operation: z.literal('${draft.name}').describe(${JSON.stringify(summary)}),`
  );
  lines.push(
    `    ${config.baseUrlParam.name}: z.string().url().describe(${JSON.stringify(
      `${config.baseUrlParam.description} (e.g. ${config.baseUrlParam.example})`
    )}),`
  );
  const order: Record<string, number> = { path: 0, body: 1, query: 2 };
  const fields = [...draft.fields].sort(
    (a, b) => order[a.location] - order[b.location]
  );
  for (const field of fields) {
    let expr = zodFor(field.schema);
    if (!field.required) expr += '.optional()';
    lines.push(`    ${emitKey(field.name)}: ${expr},`);
  }
  lines.push('    credentials: BaseCredentialsSchema,');
  lines.push('  }),');
  return lines.join('\n');
}

export function emitSchemaFile(
  config: AppGenConfig,
  drafts: OperationDraft[]
): string {
  const cls = config.className;
  const parts: string[] = [];
  parts.push(generatedHeader(config, 'Zod contract (params + results)'));
  parts.push('');
  parts.push("import { z } from 'zod';");
  parts.push("import { CredentialType } from '@bubblelab/shared-schemas';");
  parts.push('');
  parts.push('// Base credentials schema shared by every operation branch');
  parts.push('const BaseCredentialsSchema = z');
  parts.push('  .record(z.nativeEnum(CredentialType), z.string())');
  parts.push('  .optional()');
  parts.push(
    "  .describe('Object mapping credential types to values (injected at runtime)');"
  );
  parts.push('');

  for (const draft of drafts) {
    parts.push(
      `/** Documented 2xx response payload of ${draft.operationId} (statuses: ${draft.responseSources.join(', ')}); all fields optional because presence varies by status code. */`
    );
    parts.push(
      `export const ${pascal(draft.name)}PayloadSchema = ${zodForOptionalObject(draft.responseProperties)};`
    );
    parts.push('');
  }

  parts.push(
    `export const ${cls}ParamsSchema = z.discriminatedUnion('operation', [`
  );
  for (const draft of drafts) parts.push(emitParamsBranch(config, draft));
  parts.push(']);');
  parts.push('');

  parts.push(
    `export const ${cls}ResultSchema = z.discriminatedUnion('operation', [`
  );
  for (const draft of drafts) {
    parts.push('  z');
    parts.push('    .object({');
    parts.push(`      operation: z.literal('${draft.name}'),`);
    parts.push(
      "      success: z.boolean().describe('Whether the operation succeeded'),"
    );
    parts.push(
      "      error: z.string().describe('Error message if operation failed'),"
    );
    parts.push('    })');
    parts.push(`    .merge(${pascal(draft.name)}PayloadSchema),`);
  }
  parts.push(']);');
  parts.push('');

  parts.push(
    `export type ${cls}ParamsInput = z.input<typeof ${cls}ParamsSchema>;`
  );
  parts.push(`export type ${cls}Params = z.output<typeof ${cls}ParamsSchema>;`);
  parts.push(`export type ${cls}Result = z.output<typeof ${cls}ResultSchema>;`);
  parts.push('');
  for (const draft of drafts) {
    parts.push(`export type ${cls}${pascal(draft.name)}Params = Extract<`);
    parts.push(`  ${cls}ParamsInput,`);
    parts.push(`  { operation: '${draft.name}' }`);
    parts.push('>;');
  }
  parts.push('');
  parts.push(
    `export type ${cls}OperationResult<T extends ${cls}Params['operation']> = Extract<`
  );
  parts.push(`  ${cls}Result,`);
  parts.push('  { operation: T }');
  parts.push('>;');
  parts.push('');
  return parts.join('\n');
}

// ── <app>.metadata.ts ─────────────────────────────────────────────────────────

export function emitMetadataFile(
  config: AppGenConfig,
  classified: Array<{
    draft: OperationDraft;
    metadata: OperationSideEffectMetadata;
  }>
): string {
  const constName = `${upperSnake(config.appName)}_OPERATION_METADATA`;
  const parts: string[] = [];
  parts.push(
    generatedHeader(
      config,
      'Doc-grounded per-operation side-effect metadata (IR-8)'
    )
  );
  parts.push('');
  parts.push(
    "import type { BubbleOperationMetadata } from '@bubblelab/shared-schemas';"
  );
  parts.push('');
  parts.push(`export const ${constName}: BubbleOperationMetadata = {`);
  for (const { draft, metadata } of classified) {
    parts.push(`  ${emitKey(draft.name)}: {`);
    parts.push(`    sideEffect: '${metadata.sideEffect}',`);
    parts.push(`    destructive: ${metadata.destructive},`);
    parts.push(`    idempotent: ${metadata.idempotent},`);
    parts.push(`    confidence: ${metadata.confidence},`);
    parts.push(`    source: '${metadata.source}',`);
    parts.push(`    citation:`);
    parts.push(`      ${JSON.stringify(metadata.citation)},`);
    if (metadata.unverified === true) parts.push('    unverified: true,');
    parts.push('  },');
  }
  parts.push('};');
  parts.push('');
  return parts.join('\n');
}

// ── <app>.ts (the class) ──────────────────────────────────────────────────────

function emitUrlExpression(
  config: AppGenConfig,
  draft: OperationDraft
): string {
  const path = draft.pathTemplate.replace(
    /\{([^}]+)\}/g,
    (_match, name: string) => {
      return '${encodeURIComponent(' + paramAccess(name) + ')}';
    }
  );
  const queryFields = draft.fields.filter((f) => f.location === 'query');
  const base = '${trimBaseUrl(' + paramAccess(config.baseUrlParam.name) + ')}';
  if (queryFields.length === 0) {
    return '`' + base + path + '`';
  }
  return '`' + base + path + '${query}`';
}

function emitHandler(
  config: AppGenConfig,
  draft: OperationDraft,
  formCapable: boolean
): string {
  const cls = config.className;
  const op = draft.name;
  const handler = `handle${pascal(op)}`;
  const queryFields = draft.fields.filter((f) => f.location === 'query');
  const bodyFields = draft.fields.filter((f) => f.location === 'body');
  const hasBody = bodyFields.length > 0;

  const lines: string[] = [];
  lines.push(`  private async ${handler}(): Promise<`);
  lines.push(`    Extract<${cls}Result, { operation: '${op}' }>`);
  lines.push('  > {');
  lines.push(
    `    const params = ${cls}ParamsSchema.parse(this.params) as Extract<`
  );
  lines.push(`      ${cls}Params,`);
  lines.push(`      { operation: '${op}' }`);
  lines.push('    >;');
  lines.push('    try {');
  lines.push('      const token = this.chooseCredential();');
  lines.push('      if (!token) {');
  lines.push('        return {');
  lines.push(`          operation: '${op}',`);
  lines.push('          success: false,');
  lines.push(
    `          error: '${config.credentialType} credential not found',`
  );
  lines.push('        };');
  lines.push('      }');
  if (queryFields.length > 0) {
    lines.push('      const query = buildQuery({');
    for (const field of queryFields) {
      lines.push(`        ${emitKey(field.name)}: ${paramAccess(field.name)},`);
    }
    lines.push('      });');
  }
  lines.push(`      const url = ${emitUrlExpression(config, draft)};`);
  if (hasBody) {
    lines.push('      const body = pruneUndefined({');
    for (const field of bodyFields) {
      lines.push(`        ${emitKey(field.name)}: ${paramAccess(field.name)},`);
    }
    lines.push('      });');
  }
  const headersArgs = formCapable
    ? hasBody
      ? `token, '${draft.bodyEncoding}'`
      : 'token'
    : `token, ${hasBody}`;
  lines.push('      const response = await fetch(url, {');
  lines.push(`        method: '${draft.method}',`);
  lines.push(`        headers: this.requestHeaders(${headersArgs}),`);
  if (hasBody) {
    lines.push(
      draft.bodyEncoding === 'form'
        ? '        body: encodeForm(body),'
        : '        body: JSON.stringify(body),'
    );
  }
  lines.push('      });');
  lines.push('      if (!response.ok) {');
  lines.push('        const errorText = await response.text();');
  lines.push('        return {');
  lines.push(`          operation: '${op}',`);
  lines.push('          success: false,');
  lines.push(
    '          error: `' +
      config.appName +
      ' API error (${response.status}): ${errorText}`,'
  );
  lines.push('        };');
  lines.push('      }');
  lines.push(
    `      const payload = ${pascal(op)}PayloadSchema.parse(await response.json());`
  );
  lines.push(
    `      return { operation: '${op}', success: true, error: '', ...payload };`
  );
  lines.push('    } catch (error) {');
  lines.push('      return {');
  lines.push(`        operation: '${op}',`);
  lines.push('        success: false,');
  lines.push(
    "        error: error instanceof Error ? error.message : 'Unknown error occurred',"
  );
  lines.push('      };');
  lines.push('    }');
  lines.push('  }');
  return lines.join('\n');
}

/**
 * The cheapest credential probe: a GET classified `read`, else any GET (a GET
 * never carries a body, so a synthesized-handle probe cannot execute work).
 * A write-classified non-GET is never used as the probe.
 */
function pickProbe(
  classified: Array<{
    draft: OperationDraft;
    metadata: OperationSideEffectMetadata;
  }>
): OperationDraft {
  const readGet = classified.find(
    ({ draft, metadata }) =>
      draft.method === 'GET' && metadata.sideEffect === 'read'
  );
  if (readGet) return readGet.draft;
  const anyGet = classified.find(({ draft }) => draft.method === 'GET');
  if (anyGet) return anyGet.draft;
  throw new Error(
    'no GET operation available for testCredential(); supply a probe operation in the config'
  );
}

/** Synthesized literal params for an operation (constructor default, probe). */
function synthesizedParams(
  config: AppGenConfig,
  draft: OperationDraft
): Record<string, unknown> {
  const out: Record<string, unknown> = {
    operation: draft.name,
    [config.baseUrlParam.name]: config.baseUrlParam.example,
  };
  for (const field of draft.fields) {
    if (field.required || field.location === 'path') {
      out[field.name] = exampleFor(field.schema);
    }
  }
  return out;
}

/** The `Authorization`/api-key header line stamped inside requestHeaders(). */
function authHeaderLine(auth: AuthInference): string {
  if (auth.placement.kind === 'header') {
    return `      ${emitKey(auth.placement.headerName)}: token,`;
  }
  return '      Authorization: `Bearer ${token}`,';
}

/** Human description of the credential wire format for longDescription. */
function authDescription(auth: AuthInference): string {
  if (auth.placement.kind === 'header') {
    return `API key sent in the ${auth.placement.headerName} header`;
  }
  return 'bearer token';
}

export function emitClassFile(
  config: AppGenConfig,
  classified: Array<{
    draft: OperationDraft;
    metadata: OperationSideEffectMetadata;
  }>,
  auth: AuthInference
): string {
  const cls = config.className;
  const drafts = classified.map((c) => c.draft);
  const metadataConst = `${upperSnake(config.appName)}_OPERATION_METADATA`;
  const probe = pickProbe(classified);
  // Constructor default = the probe operation (never a write-shaped default).
  const defaults = synthesizedParams(config, probe);
  const anyQuery = drafts.some((d) =>
    d.fields.some((f) => f.location === 'query')
  );
  const anyBody = drafts.some((d) =>
    d.fields.some((f) => f.location === 'body')
  );
  // Form-capable apps get contentType-aware headers + the encodeForm helper;
  // JSON-only apps keep the original (smaller) emission.
  const anyForm = drafts.some(
    (d) =>
      d.bodyEncoding === 'form' && d.fields.some((f) => f.location === 'body')
  );

  const parts: string[] = [];
  parts.push(
    generatedHeader(config, 'ServiceBubble class (raw-fetch pattern)')
  );
  parts.push('');
  parts.push(
    "import { ServiceBubble } from '../../../types/service-bubble-class.js';"
  );
  parts.push("import type { BubbleContext } from '../../../types/bubble.js';");
  parts.push("import { CredentialType } from '@bubblelab/shared-schemas';");
  parts.push(
    `import { ${metadataConst} } from './${config.appName}.metadata.js';`
  );
  parts.push('import {');
  parts.push(`  ${cls}ParamsSchema,`);
  parts.push(`  ${cls}ResultSchema,`);
  for (const draft of drafts)
    parts.push(`  ${pascal(draft.name)}PayloadSchema,`);
  parts.push(`  type ${cls}Params,`);
  parts.push(`  type ${cls}ParamsInput,`);
  parts.push(`  type ${cls}Result,`);
  parts.push(`} from './${config.appName}.schema.js';`);
  parts.push('');
  parts.push(
    '/** Strip a trailing slash so path concatenation stays canonical. */'
  );
  parts.push('function trimBaseUrl(url: string): string {');
  parts.push("  return url.endsWith('/') ? url.slice(0, -1) : url;");
  parts.push('}');
  parts.push('');
  if (anyQuery) {
    parts.push(
      "/** Serialize defined query params; returns '' or '?k=v&…'. */"
    );
    parts.push('function buildQuery(');
    parts.push(
      '  params: Record<string, string | number | boolean | undefined>'
    );
    parts.push('): string {');
    parts.push('  const search = new URLSearchParams();');
    parts.push('  for (const [key, value] of Object.entries(params)) {');
    parts.push('    if (value !== undefined) search.set(key, String(value));');
    parts.push('  }');
    parts.push('  const qs = search.toString();');
    parts.push("  return qs.length > 0 ? `?${qs}` : '';");
    parts.push('}');
    parts.push('');
  }
  if (anyBody) {
    parts.push('/** Drop undefined values before JSON body serialization. */');
    parts.push('function pruneUndefined(');
    parts.push('  record: Record<string, unknown>');
    parts.push('): Record<string, unknown> {');
    parts.push('  const out: Record<string, unknown> = {};');
    parts.push('  for (const [key, value] of Object.entries(record)) {');
    parts.push('    if (value !== undefined) out[key] = value;');
    parts.push('  }');
    parts.push('  return out;');
    parts.push('}');
    parts.push('');
  }
  if (anyForm) {
    parts.push('/**');
    parts.push(
      ' * Bracket-flatten nested values into application/x-www-form-urlencoded'
    );
    parts.push(
      ' * pairs (OpenAPI deepObject style: metadata[key]=v, line_items[0][price]=v).'
    );
    parts.push(' */');
    parts.push(
      'function encodeForm(record: Record<string, unknown>): string {'
    );
    parts.push('  const search = new URLSearchParams();');
    parts.push('  const walk = (key: string, value: unknown): void => {');
    parts.push('    if (value === undefined || value === null) return;');
    parts.push('    if (Array.isArray(value)) {');
    parts.push(
      '      value.forEach((item, index) => walk(`${key}[${index}]`, item));'
    );
    parts.push("    } else if (typeof value === 'object') {");
    parts.push(
      '      for (const [child, childValue] of Object.entries(value)) {'
    );
    parts.push('        walk(`${key}[${child}]`, childValue);');
    parts.push('      }');
    parts.push('    } else {');
    parts.push('      search.append(key, String(value));');
    parts.push('    }');
    parts.push('  };');
    parts.push(
      '  for (const [key, value] of Object.entries(record)) walk(key, value);'
    );
    parts.push('  return search.toString();');
    parts.push('}');
    parts.push('');
  }
  parts.push(`export class ${cls}Bubble<`);
  parts.push(`  T extends ${cls}ParamsInput = ${cls}ParamsInput,`);
  parts.push('> extends ServiceBubble<');
  parts.push('  T,');
  parts.push(`  Extract<${cls}Result, { operation: T['operation'] }>`);
  parts.push('> {');
  parts.push("  static readonly type = 'service' as const;");
  parts.push(`  static readonly service = '${config.service}';`);
  parts.push(`  // S5 auth (${auth.source}): ${auth.citation}`);
  parts.push(`  static readonly authType = '${auth.authType}' as const;`);
  parts.push(`  static readonly bubbleName = '${config.appName}';`);
  parts.push(`  static readonly operationMetadata = ${metadataConst};`);
  parts.push(`  static readonly schema = ${cls}ParamsSchema;`);
  parts.push(`  static readonly resultSchema = ${cls}ResultSchema;`);
  parts.push(
    `  static readonly shortDescription = ${JSON.stringify(config.shortDescription)};`
  );
  parts.push('  static readonly longDescription = `');
  parts.push(`    ${config.shortDescription}`);
  parts.push('');
  parts.push('    Operations (generated from the vendor OpenAPI spec):');
  for (const { draft, metadata } of classified) {
    const summary = (draft.summary ?? '').trim();
    parts.push(
      `    - ${draft.name} [side-effect: ${metadata.sideEffect}]: ${summary}`
    );
  }
  parts.push('');
  parts.push(
    `    Credential: ${config.credentialType} (${authDescription(auth)}) + per-account ${config.baseUrlParam.name}.`
  );
  parts.push('  `;');
  if (config.alias) parts.push(`  static readonly alias = '${config.alias}';`);
  parts.push('');
  parts.push('  constructor(');
  parts.push(`    params: T = ${JSON.stringify(defaults)} as T,`);
  parts.push('    context?: BubbleContext');
  parts.push('  ) {');
  parts.push('    super(params, context);');
  parts.push('  }');
  parts.push('');
  parts.push('  private requestHeaders(');
  parts.push('    token: string,');
  if (anyForm) {
    parts.push("    contentType?: 'json' | 'form'");
  } else {
    parts.push('    hasBody: boolean');
  }
  parts.push('  ): Record<string, string> {');
  parts.push('    const headers: Record<string, string> = {');
  parts.push(authHeaderLine(auth));
  for (const [header, value] of Object.entries({
    Accept: 'application/json',
    ...config.authHeaders,
  })) {
    parts.push(`      ${emitKey(header)}: ${JSON.stringify(value)},`);
  }
  parts.push('    };');
  if (anyForm) {
    parts.push("    if (contentType === 'json') {");
    parts.push("      headers['Content-Type'] = 'application/json';");
    parts.push('    }');
    parts.push("    if (contentType === 'form') {");
    parts.push(
      "      headers['Content-Type'] = 'application/x-www-form-urlencoded';"
    );
    parts.push('    }');
  } else {
    parts.push(
      "    if (hasBody) headers['Content-Type'] = 'application/json';"
    );
  }
  parts.push('    return headers;');
  parts.push('  }');
  parts.push('');
  parts.push('  public async testCredential(): Promise<boolean> {');
  parts.push('    const token = this.chooseCredential();');
  parts.push('    if (!token) {');
  parts.push(
    `      throw new Error('${config.appName} credentials are required');`
  );
  parts.push('    }');
  parts.push(
    `    const params = { ${config.baseUrlParam.name}: this.params.${config.baseUrlParam.name} };`
  );
  parts.push(
    `    // Probe: ${probe.method} ${probe.pathTemplate} (${probe.name}) with a synthesized handle.`
  );
  parts.push(
    '    // 401/403 mean the credential was rejected; any other status means it was accepted.'
  );
  const probeParams = synthesizedParams(config, probe);
  const probePath = probe.pathTemplate.replace(
    /\{([^}]+)\}/g,
    (_match, name: string) => String(probeParams[name])
  );
  parts.push(
    '    const response = await fetch(`${trimBaseUrl(params.' +
      config.baseUrlParam.name +
      ')}' +
      probePath +
      '`, {'
  );
  parts.push(`      method: '${probe.method}',`);
  parts.push(
    anyForm
      ? '      headers: this.requestHeaders(token),'
      : '      headers: this.requestHeaders(token, false),'
  );
  parts.push('    });');
  parts.push('    return response.status !== 401 && response.status !== 403;');
  parts.push('  }');
  parts.push('');
  parts.push('  protected chooseCredential(): string | undefined {');
  parts.push('    const credentials = this.params.credentials;');
  parts.push("    if (!credentials || typeof credentials !== 'object') {");
  parts.push('      return undefined;');
  parts.push('    }');
  parts.push(
    `    return credentials[CredentialType.${config.credentialType}];`
  );
  parts.push('  }');
  parts.push('');
  parts.push('  protected async performAction(');
  parts.push('    context?: BubbleContext');
  parts.push(
    `  ): Promise<Extract<${cls}Result, { operation: T['operation'] }>> {`
  );
  parts.push('    void context;');
  parts.push('    const { operation } = this.params;');
  parts.push('    switch (operation) {');
  for (const draft of drafts) {
    parts.push(`      case '${draft.name}':`);
    parts.push(`        return this.handle${pascal(draft.name)}() as Promise<`);
    parts.push(
      `          Extract<${cls}Result, { operation: T['operation'] }>`
    );
    parts.push('        >;');
  }
  parts.push('      default:');
  parts.push('        return {');
  parts.push("          operation: operation as T['operation'],");
  parts.push('          success: false,');
  parts.push('          error: `Unknown operation: ${String(operation)}`,');
  parts.push(
    `        } as Extract<${cls}Result, { operation: T['operation'] }>;`
  );
  parts.push('    }');
  parts.push('  }');
  parts.push('');
  for (const draft of drafts) {
    parts.push(emitHandler(config, draft, anyForm));
    parts.push('');
  }
  parts.push('}');
  parts.push('');
  return parts.join('\n');
}

// ── index.ts ──────────────────────────────────────────────────────────────────

export function emitIndexFile(config: AppGenConfig): string {
  const cls = config.className;
  const metadataConst = `${upperSnake(config.appName)}_OPERATION_METADATA`;
  return [
    generatedHeader(config, 'Public exports'),
    '',
    `export { ${cls}Bubble } from './${config.appName}.js';`,
    `export { ${metadataConst} } from './${config.appName}.metadata.js';`,
    'export {',
    `  ${cls}ParamsSchema,`,
    `  ${cls}ResultSchema,`,
    `  type ${cls}Params,`,
    `  type ${cls}Result,`,
    `  type ${cls}ParamsInput,`,
    `} from './${config.appName}.schema.js';`,
    '',
  ].join('\n');
}

// ── <app>.schema.test.ts ──────────────────────────────────────────────────────

export function emitTestFile(
  config: AppGenConfig,
  drafts: OperationDraft[]
): string {
  const cls = config.className;
  const metadataConst = `${upperSnake(config.appName)}_OPERATION_METADATA`;
  const parts: string[] = [];
  parts.push(
    generatedHeader(
      config,
      'Schema round-trip tests (fixtures = the examples shipped inside the vendor spec)'
    )
  );
  parts.push('');
  parts.push("import { describe, expect, it } from 'vitest';");
  parts.push('import {');
  parts.push(`  ${cls}ParamsSchema,`);
  parts.push(`  ${cls}ResultSchema,`);
  parts.push(`} from './${config.appName}.schema.js';`);
  parts.push(
    `import { ${metadataConst} } from './${config.appName}.metadata.js';`
  );
  parts.push('');
  parts.push(`describe('${config.appName} generated contract', () => {`);

  for (const draft of drafts) {
    const valid: Record<string, unknown> = {
      operation: draft.name,
      [config.baseUrlParam.name]: config.baseUrlParam.example,
      ...(draft.requestExample ?? {}),
    };
    for (const field of draft.fields) {
      if (
        (field.required || field.location === 'path') &&
        valid[field.name] === undefined
      ) {
        valid[field.name] = exampleFor(field.schema);
      }
    }
    parts.push(`  it('${draft.name}: accepts a spec-example request', () => {`);
    parts.push(
      `    const result = ${cls}ParamsSchema.safeParse(${JSON.stringify(valid)});`
    );
    parts.push('    expect(result.success).toBe(true);');
    parts.push('  });');
    parts.push('');

    // Invalid fixture: corrupt the first string field's type, or drop a
    // required generator-added field.
    const stringField = draft.fields.find((f) => f.schema.type === 'string');
    if (stringField) {
      const invalid = { ...valid, [stringField.name]: 12345 };
      parts.push(
        `  it('${draft.name}: rejects a type-corrupted request (${stringField.name}: number)', () => {`
      );
      parts.push(
        `    const result = ${cls}ParamsSchema.safeParse(${JSON.stringify(invalid)});`
      );
      parts.push('    expect(result.success).toBe(false);');
      parts.push('  });');
      parts.push('');
    }

    const exampleStatus = Object.keys(draft.responseExamples)[0];
    if (exampleStatus !== undefined) {
      const fixture = {
        operation: draft.name,
        success: true,
        error: '',
        ...(draft.responseExamples[exampleStatus] as Record<string, unknown>),
      };
      parts.push(
        `  it('${draft.name}: spec ${exampleStatus}-response example parses through the result schema', () => {`
      );
      parts.push(
        `    const result = ${cls}ResultSchema.safeParse(${JSON.stringify(fixture)});`
      );
      parts.push('    expect(result.success).toBe(true);');
      parts.push('  });');
      parts.push('');
    }
  }

  parts.push(
    `  it('rejects requests missing the required ${config.baseUrlParam.name}', () => {`
  );
  const missingBase: Record<string, unknown> = { operation: drafts[0].name };
  for (const field of drafts[0].fields) {
    if (field.required || field.location === 'path') {
      missingBase[field.name] = exampleFor(field.schema);
    }
  }
  parts.push(
    `    const result = ${cls}ParamsSchema.safeParse(${JSON.stringify(missingBase)});`
  );
  parts.push('    expect(result.success).toBe(false);');
  parts.push('  });');
  parts.push('');
  parts.push("  it('rejects unknown operations', () => {");
  parts.push(
    `    const result = ${cls}ParamsSchema.safeParse({ operation: 'not_a_real_operation' });`
  );
  parts.push('    expect(result.success).toBe(false);');
  parts.push('  });');
  parts.push('');
  parts.push(
    "  it('every schema operation has cited side-effect metadata (coverage guard)', () => {"
  );
  parts.push(`    const operations = ${cls}ParamsSchema.options.map(`);
  parts.push('      (option) => option.shape.operation.value');
  parts.push('    );');
  parts.push('    for (const operation of operations) {');
  parts.push(`      const entry = ${metadataConst}[operation];`);
  parts.push(
    '      expect(entry, `missing metadata for ${operation}`).toBeDefined();'
  );
  parts.push('      expect(entry.citation.length).toBeGreaterThan(0);');
  parts.push('      expect(entry.source.length).toBeGreaterThan(0);');
  parts.push('    }');
  parts.push('  });');
  parts.push('});');
  parts.push('');
  return parts.join('\n');
}

// ── Entry point ───────────────────────────────────────────────────────────────

export function emitBubble(
  config: AppGenConfig,
  classified: Array<{
    draft: OperationDraft;
    metadata: OperationSideEffectMetadata;
  }>,
  auth: AuthInference
): GeneratedFile[] {
  const drafts = classified.map((c) => c.draft);
  return [
    {
      fileName: `${config.appName}.schema.ts`,
      content: emitSchemaFile(config, drafts),
    },
    {
      fileName: `${config.appName}.metadata.ts`,
      content: emitMetadataFile(config, classified),
    },
    {
      fileName: `${config.appName}.ts`,
      content: emitClassFile(config, classified, auth),
    },
    {
      fileName: `${config.appName}.schema.test.ts`,
      content: emitTestFile(config, drafts),
    },
    { fileName: 'index.ts', content: emitIndexFile(config) },
  ];
}
