/**
 * Schema round-trip tests (fixtures = the examples shipped inside the vendor spec) for the 'databricks-sql' bubble.
 *
 * GENERATED by @bubblelab/bubble-appgen from databricks-sql-statements.yaml — do not hand-edit;
 * re-run `pnpm --filter @bubblelab/bubble-appgen generate:databricks-sql` instead.
 * Vendor docs: https://docs.databricks.com/api/workspace/statementexecution
 */

import { describe, expect, it } from 'vitest';
import {
  DatabricksSqlParamsSchema,
  DatabricksSqlResultSchema,
} from './databricks-sql.schema.js';
import { DATABRICKS_SQL_OPERATION_METADATA } from './databricks-sql.metadata.js';

describe('databricks-sql generated contract', () => {
  it('execute_statement: accepts a spec-example request', () => {
    const result = DatabricksSqlParamsSchema.safeParse({
      operation: 'execute_statement',
      workspaceUrl: 'https://dbc-a1b2c3d4-e5f6.cloud.databricks.com',
      statement: 'SELECT * FROM range(10)',
      warehouse_id: 'abcdef0123456789',
      wait_timeout: '10s',
      on_wait_timeout: 'CONTINUE',
      disposition: 'INLINE',
      format: 'JSON_ARRAY',
    });
    expect(result.success).toBe(true);
  });

  it('execute_statement: rejects a type-corrupted request (statement: number)', () => {
    const result = DatabricksSqlParamsSchema.safeParse({
      operation: 'execute_statement',
      workspaceUrl: 'https://dbc-a1b2c3d4-e5f6.cloud.databricks.com',
      statement: 12345,
      warehouse_id: 'abcdef0123456789',
      wait_timeout: '10s',
      on_wait_timeout: 'CONTINUE',
      disposition: 'INLINE',
      format: 'JSON_ARRAY',
    });
    expect(result.success).toBe(false);
  });

  it('execute_statement: spec 200-response example parses through the result schema', () => {
    const result = DatabricksSqlResultSchema.safeParse({
      operation: 'execute_statement',
      success: true,
      error: '',
      statement_id: '01f06a2b-0000-1abc-9def-0123456789ab',
      status: { state: 'SUCCEEDED' },
      manifest: {
        format: 'JSON_ARRAY',
        schema: {
          column_count: 1,
          columns: [
            { name: 'id', position: 0, type_name: 'LONG', type_text: 'BIGINT' },
          ],
        },
        total_chunk_count: 1,
        total_row_count: 10,
        truncated: false,
      },
      result: {
        chunk_index: 0,
        row_count: 10,
        row_offset: 0,
        data_array: [['0'], ['1']],
      },
    });
    expect(result.success).toBe(true);
  });

  it('get_statement: accepts a spec-example request', () => {
    const result = DatabricksSqlParamsSchema.safeParse({
      operation: 'get_statement',
      workspaceUrl: 'https://dbc-a1b2c3d4-e5f6.cloud.databricks.com',
      statement_id: 'example',
    });
    expect(result.success).toBe(true);
  });

  it('get_statement: rejects a type-corrupted request (statement_id: number)', () => {
    const result = DatabricksSqlParamsSchema.safeParse({
      operation: 'get_statement',
      workspaceUrl: 'https://dbc-a1b2c3d4-e5f6.cloud.databricks.com',
      statement_id: 12345,
    });
    expect(result.success).toBe(false);
  });

  it('get_statement: spec 200-response example parses through the result schema', () => {
    const result = DatabricksSqlResultSchema.safeParse({
      operation: 'get_statement',
      success: true,
      error: '',
      statement_id: '01f06a2b-0000-1abc-9def-0123456789ab',
      status: { state: 'RUNNING' },
    });
    expect(result.success).toBe(true);
  });

  it('rejects requests missing the required workspaceUrl', () => {
    const result = DatabricksSqlParamsSchema.safeParse({
      operation: 'execute_statement',
      statement: 'example',
      warehouse_id: 'example',
    });
    expect(result.success).toBe(false);
  });

  it('rejects unknown operations', () => {
    const result = DatabricksSqlParamsSchema.safeParse({
      operation: 'not_a_real_operation',
    });
    expect(result.success).toBe(false);
  });

  it('every schema operation has cited side-effect metadata (coverage guard)', () => {
    const operations = DatabricksSqlParamsSchema.options.map(
      (option) => option.shape.operation.value
    );
    for (const operation of operations) {
      const entry = DATABRICKS_SQL_OPERATION_METADATA[operation];
      expect(entry, `missing metadata for ${operation}`).toBeDefined();
      expect(entry.citation.length).toBeGreaterThan(0);
      expect(entry.source.length).toBeGreaterThan(0);
    }
  });
});
