/**
 * Doc-grounded per-operation side-effect metadata (IR-8) for the 'databricks-sql' bubble.
 *
 * GENERATED by @bubblelab/bubble-appgen from databricks-sql-statements.yaml — do not hand-edit;
 * re-run `pnpm --filter @bubblelab/bubble-appgen generate:databricks-sql` instead.
 * Vendor docs: https://docs.databricks.com/api/workspace/statementexecution
 */

import type { BubbleOperationMetadata } from '@bubblelab/shared-schemas';

export const DATABRICKS_SQL_OPERATION_METADATA: BubbleOperationMetadata = {
  execute_statement: {
    sideEffect: 'write',
    destructive: false,
    idempotent: false,
    confidence: 0.85,
    source: 'openapi',
    citation:
      'databricks-sql-statements.yaml#/paths/~1api~12.0~1sql~1statements/post — "Executes a SQL statement on a SQL warehouse." — carrier operation: executes caller-supplied SQL; fail-safe write until statement-level verb refinement is applied',
  },
  get_statement: {
    sideEffect: 'read',
    destructive: false,
    idempotent: true,
    confidence: 0.85,
    source: 'openapi',
    citation:
      'databricks-sql-statements.yaml#/paths/~1api~12.0~1sql~1statements~1{statement_id}/get — "Gets status, manifest, and result data for an executed statement."',
  },
};
