/**
 * ServiceBubble class (raw-fetch pattern) for the 'databricks-sql' bubble.
 *
 * GENERATED by @bubblelab/bubble-appgen from databricks-sql-statements.yaml — do not hand-edit;
 * re-run `pnpm --filter @bubblelab/bubble-appgen generate:databricks-sql` instead.
 * Vendor docs: https://docs.databricks.com/api/workspace/statementexecution
 */

import { ServiceBubble } from '../../../types/service-bubble-class.js';
import type { BubbleContext } from '../../../types/bubble.js';
import { CredentialType } from '@bubblelab/shared-schemas';
import { DATABRICKS_SQL_OPERATION_METADATA } from './databricks-sql.metadata.js';
import {
  DatabricksSqlParamsSchema,
  DatabricksSqlResultSchema,
  ExecuteStatementPayloadSchema,
  GetStatementPayloadSchema,
  type DatabricksSqlParams,
  type DatabricksSqlParamsInput,
  type DatabricksSqlResult,
} from './databricks-sql.schema.js';

/** Strip a trailing slash so path concatenation stays canonical. */
function trimBaseUrl(url: string): string {
  return url.endsWith('/') ? url.slice(0, -1) : url;
}

/** Drop undefined values before JSON body serialization. */
function pruneUndefined(
  record: Record<string, unknown>
): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(record)) {
    if (value !== undefined) out[key] = value;
  }
  return out;
}

export class DatabricksSqlBubble<
  T extends DatabricksSqlParamsInput = DatabricksSqlParamsInput,
> extends ServiceBubble<
  T,
  Extract<DatabricksSqlResult, { operation: T['operation'] }>
> {
  static readonly type = 'service' as const;
  static readonly service = 'databricks';
  static readonly authType = 'apikey' as const;
  static readonly bubbleName = 'databricks-sql';
  static readonly operationMetadata = DATABRICKS_SQL_OPERATION_METADATA;
  static readonly schema = DatabricksSqlParamsSchema;
  static readonly resultSchema = DatabricksSqlResultSchema;
  static readonly shortDescription =
    'Databricks SQL Statement Execution API integration generated from a hand-transcribed OpenAPI snippet of the official docs (execute SQL on a SQL warehouse, poll status and fetch results)';
  static readonly longDescription = `
    Databricks SQL Statement Execution API integration generated from a hand-transcribed OpenAPI snippet of the official docs (execute SQL on a SQL warehouse, poll status and fetch results)

    Operations (generated from the vendor OpenAPI spec):
    - execute_statement [side-effect: write]: Executes a SQL statement on a SQL warehouse.
    - get_statement [side-effect: read]: Gets status, manifest, and result data for an executed statement.

    Credential: DATABRICKS_PAT (bearer token) + per-account workspaceUrl.
  `;
  static readonly alias = 'dbx-sql';

  constructor(
    params: T = {
      operation: 'get_statement',
      workspaceUrl: 'https://dbc-a1b2c3d4-e5f6.cloud.databricks.com',
      statement_id: 'example',
    } as T,
    context?: BubbleContext,
    instanceId?: string
  ) {
    super(params, context, instanceId);
  }

  private requestHeaders(
    token: string,
    hasBody: boolean
  ): Record<string, string> {
    const headers: Record<string, string> = {
      Authorization: `Bearer ${token}`,
      Accept: 'application/json',
      'User-Agent': 'bubblelab/1.0',
    };
    if (hasBody) headers['Content-Type'] ??= 'application/json';
    return headers;
  }

  public async testCredential(): Promise<boolean> {
    const token = this.chooseCredential();
    if (!token) {
      throw new Error('databricks-sql credentials are required');
    }
    const params = { workspaceUrl: this.params.workspaceUrl };
    // Probe: GET /api/2.0/sql/statements/{statement_id} (get_statement) with a synthesized handle.
    // 401/403 mean the credential was rejected; any other status means it was accepted.
    const response = await fetch(
      `${trimBaseUrl(params.workspaceUrl)}/api/2.0/sql/statements/example`,
      {
        method: 'GET',
        headers: this.requestHeaders(token, false),
      }
    );
    return response.status !== 401 && response.status !== 403;
  }

  protected chooseCredential(): string | undefined {
    const credentials = this.params.credentials;
    if (!credentials || typeof credentials !== 'object') {
      return undefined;
    }
    return credentials[CredentialType.DATABRICKS_PAT];
  }

  protected async performAction(
    context?: BubbleContext
  ): Promise<Extract<DatabricksSqlResult, { operation: T['operation'] }>> {
    void context;
    const { operation } = this.params;
    switch (operation) {
      case 'execute_statement':
        return this.handleExecuteStatement() as Promise<
          Extract<DatabricksSqlResult, { operation: T['operation'] }>
        >;
      case 'get_statement':
        return this.handleGetStatement() as Promise<
          Extract<DatabricksSqlResult, { operation: T['operation'] }>
        >;
      default:
        return {
          operation: operation as T['operation'],
          success: false,
          error: `Unknown operation: ${String(operation)}`,
        } as Extract<DatabricksSqlResult, { operation: T['operation'] }>;
    }
  }

  private async handleExecuteStatement(): Promise<
    Extract<DatabricksSqlResult, { operation: 'execute_statement' }>
  > {
    const params = DatabricksSqlParamsSchema.parse(this.params) as Extract<
      DatabricksSqlParams,
      { operation: 'execute_statement' }
    >;
    try {
      const token = this.chooseCredential();
      if (!token) {
        return {
          operation: 'execute_statement',
          success: false,
          error: 'DATABRICKS_PAT credential not found',
        };
      }
      const url = `${trimBaseUrl(params.workspaceUrl)}/api/2.0/sql/statements`;
      const body = pruneUndefined({
        statement: params.statement,
        warehouse_id: params.warehouse_id,
        catalog: params.catalog,
        schema: params.schema,
        parameters: params.parameters,
        byte_limit: params.byte_limit,
        row_limit: params.row_limit,
        disposition: params.disposition,
        format: params.format,
        wait_timeout: params.wait_timeout,
        on_wait_timeout: params.on_wait_timeout,
      });
      const response = await fetch(url, {
        method: 'POST',
        headers: this.requestHeaders(token, true),
        body: JSON.stringify(body),
      });
      if (!response.ok) {
        const errorText = await response.text();
        return {
          operation: 'execute_statement',
          success: false,
          error: `databricks-sql API error (${response.status}): ${errorText}`,
        };
      }
      const payload = ExecuteStatementPayloadSchema.parse(
        await response.json()
      );
      return {
        operation: 'execute_statement',
        success: true,
        error: '',
        ...payload,
      };
    } catch (error) {
      return {
        operation: 'execute_statement',
        success: false,
        error:
          error instanceof Error ? error.message : 'Unknown error occurred',
      };
    }
  }

  private async handleGetStatement(): Promise<
    Extract<DatabricksSqlResult, { operation: 'get_statement' }>
  > {
    const params = DatabricksSqlParamsSchema.parse(this.params) as Extract<
      DatabricksSqlParams,
      { operation: 'get_statement' }
    >;
    try {
      const token = this.chooseCredential();
      if (!token) {
        return {
          operation: 'get_statement',
          success: false,
          error: 'DATABRICKS_PAT credential not found',
        };
      }
      const url = `${trimBaseUrl(params.workspaceUrl)}/api/2.0/sql/statements/${encodeURIComponent(params.statement_id)}`;
      const response = await fetch(url, {
        method: 'GET',
        headers: this.requestHeaders(token, false),
      });
      if (!response.ok) {
        const errorText = await response.text();
        return {
          operation: 'get_statement',
          success: false,
          error: `databricks-sql API error (${response.status}): ${errorText}`,
        };
      }
      const payload = GetStatementPayloadSchema.parse(await response.json());
      return {
        operation: 'get_statement',
        success: true,
        error: '',
        ...payload,
      };
    } catch (error) {
      return {
        operation: 'get_statement',
        success: false,
        error:
          error instanceof Error ? error.message : 'Unknown error occurred',
      };
    }
  }
}
