/**
 * Zod contract (params + results) for the 'databricks-sql' bubble.
 *
 * GENERATED by @bubblelab/bubble-appgen from databricks-sql-statements.yaml — do not hand-edit;
 * re-run `pnpm --filter @bubblelab/bubble-appgen generate:databricks-sql` instead.
 * Vendor docs: https://docs.databricks.com/api/workspace/statementexecution
 */

import { z } from 'zod';
import { CredentialType } from '@bubblelab/shared-schemas';

// Base credentials schema shared by every operation branch
const BaseCredentialsSchema = z
  .record(z.nativeEnum(CredentialType), z.string())
  .optional()
  .describe('Object mapping credential types to values (injected at runtime)');

/** Documented 2xx response payload of ExecuteStatement (statuses: 200); all fields optional because presence varies by status code. */
export const ExecuteStatementPayloadSchema = z.object({
  statement_id: z
    .string()
    .describe(
      'The statement ID is returned upon successfully submitting a SQL statement, and is a required reference for all subsequent calls.'
    )
    .optional(),
  status: z
    .object({
      state: z
        .enum([
          'PENDING',
          'RUNNING',
          'SUCCEEDED',
          'FAILED',
          'CANCELED',
          'CLOSED',
        ])
        .describe(
          'Statement execution state. PENDING waiting for warehouse; RUNNING running; SUCCEEDED execution was successful, result data available for fetch; FAILED execution failed, reason for failure described in the accompanying error message; CANCELED user canceled; CLOSED execution successful, and statement closed, result no longer available for fetch.'
        )
        .optional(),
      error: z
        .object({
          error_code: z
            .string()
            .describe('Error code, e.g. BAD_REQUEST or INTERNAL_ERROR.')
            .optional(),
          message: z
            .string()
            .describe('A brief summary of the error condition.')
            .optional(),
        })
        .describe('Error details when the statement status is FAILED.')
        .optional(),
      sql_state: z
        .string()
        .describe(
          'SQLSTATE error code returned when the statement execution fails. Only populated when the statement status is FAILED.'
        )
        .optional(),
    })
    .describe(
      'The status response includes execution state and if relevant, error information.'
    )
    .optional(),
  manifest: z
    .object({
      format: z
        .enum(['JSON_ARRAY', 'ARROW_STREAM', 'CSV'])
        .describe('The result format.')
        .optional(),
      schema: z
        .object({
          column_count: z
            .number()
            .int()
            .describe('The number of columns in the result set.')
            .optional(),
          columns: z
            .array(
              z.object({
                name: z.string().describe('The name of the column.').optional(),
                position: z
                  .number()
                  .int()
                  .describe(
                    'The ordinal position of the column (starting at position 0).'
                  )
                  .optional(),
                type_name: z
                  .string()
                  .describe(
                    "The name of the base data type. This doesn't include details for complex types such as STRUCT, MAP or ARRAY."
                  )
                  .optional(),
                type_text: z
                  .string()
                  .describe('The full SQL type specification.')
                  .optional(),
                type_precision: z
                  .number()
                  .int()
                  .describe(
                    'Specifies the number of digits in a number. This applies to the DECIMAL type.'
                  )
                  .optional(),
                type_scale: z
                  .number()
                  .int()
                  .describe(
                    'Specifies the number of digits to the right of the decimal point in a number. This applies to the DECIMAL type.'
                  )
                  .optional(),
                type_interval_type: z
                  .string()
                  .describe('The format of the interval type.')
                  .optional(),
              })
            )
            .describe('Ordered column descriptions.')
            .optional(),
        })
        .describe('The schema is an ordered list of column descriptions.')
        .optional(),
      chunks: z
        .array(
          z.object({
            byte_count: z
              .number()
              .int()
              .describe(
                'The number of bytes in the result chunk. This field is not available when using INLINE disposition.'
              )
              .optional(),
            chunk_index: z
              .number()
              .int()
              .describe(
                'The position within the sequence of result set chunks.'
              )
              .optional(),
            row_count: z
              .number()
              .int()
              .describe('The number of rows within the result chunk.')
              .optional(),
            row_offset: z
              .number()
              .int()
              .describe('The starting row offset within the result set.')
              .optional(),
          })
        )
        .describe('Array of result set chunk metadata.')
        .optional(),
      total_byte_count: z
        .number()
        .int()
        .describe(
          'The total number of bytes in the result set. This field is not available when using INLINE disposition.'
        )
        .optional(),
      total_chunk_count: z
        .number()
        .int()
        .describe(
          'The total number of chunks that the result set has been divided into.'
        )
        .optional(),
      total_row_count: z
        .number()
        .int()
        .describe('The total number of rows in the result set.')
        .optional(),
      truncated: z
        .boolean()
        .describe(
          'Indicates whether the result is truncated due to row_limit or byte_limit.'
        )
        .optional(),
    })
    .describe(
      'The result manifest provides schema and metadata for the result set.'
    )
    .optional(),
  result: z
    .object({
      byte_count: z
        .number()
        .int()
        .describe(
          'The number of bytes in the result chunk. This field is not available when using INLINE disposition.'
        )
        .optional(),
      chunk_index: z
        .number()
        .int()
        .describe('The position within the sequence of result set chunks.')
        .optional(),
      row_count: z
        .number()
        .int()
        .describe('The number of rows within the result chunk.')
        .optional(),
      row_offset: z
        .number()
        .int()
        .describe('The starting row offset within the result set.')
        .optional(),
      data_array: z
        .array(z.array(z.string().nullable()))
        .describe(
          'The JSON_ARRAY format is an array of arrays of values, where each non-null value is formatted as a string. Null values are encoded as JSON null.'
        )
        .optional(),
      next_chunk_index: z
        .number()
        .int()
        .describe(
          'When fetching, provides the chunk_index for the next chunk. If absent, indicates there are no more chunks.'
        )
        .optional(),
      next_chunk_internal_link: z
        .string()
        .describe(
          'When fetching, provides a link to fetch the next chunk. This link is an absolute path to be joined with your workspace URL, and should be treated as an opaque link.'
        )
        .optional(),
      external_links: z
        .array(
          z.object({
            byte_count: z
              .number()
              .int()
              .describe('The number of bytes in the result chunk.')
              .optional(),
            chunk_index: z
              .number()
              .int()
              .describe(
                'The position within the sequence of result set chunks.'
              )
              .optional(),
            expiration: z
              .string()
              .describe(
                'Indicates the date-time that the given external link will expire and becomes invalid, after which point a new external_link must be requested.'
              )
              .optional(),
            external_link: z
              .string()
              .describe(
                'A URL pointing to a chunk of result data, hosted by an external service, with a short expiration time (<= 15 minutes).'
              )
              .optional(),
            http_headers: z
              .record(z.string(), z.string())
              .describe(
                'HTTP headers that must be included with a GET request to the external_link.'
              )
              .optional(),
            next_chunk_index: z
              .number()
              .int()
              .describe(
                'When fetching, provides the chunk_index for the next chunk.'
              )
              .optional(),
            next_chunk_internal_link: z
              .string()
              .describe(
                'When fetching, provides a link to fetch the next chunk.'
              )
              .optional(),
            row_count: z
              .number()
              .int()
              .describe('The number of rows within the result chunk.')
              .optional(),
            row_offset: z
              .number()
              .int()
              .describe('The starting row offset within the result set.')
              .optional(),
          })
        )
        .describe(
          'External links pointing to chunks of result data on cloud storage (EXTERNAL_LINKS disposition only). These URLs contain temporary credentials and should be treated as sensitive.'
        )
        .optional(),
    })
    .describe('Result data chunk (first chunk when INLINE).')
    .optional(),
});

/** Documented 2xx response payload of GetStatement (statuses: 200); all fields optional because presence varies by status code. */
export const GetStatementPayloadSchema = z.object({
  statement_id: z
    .string()
    .describe(
      'The statement ID is returned upon successfully submitting a SQL statement, and is a required reference for all subsequent calls.'
    )
    .optional(),
  status: z
    .object({
      state: z
        .enum([
          'PENDING',
          'RUNNING',
          'SUCCEEDED',
          'FAILED',
          'CANCELED',
          'CLOSED',
        ])
        .describe(
          'Statement execution state. PENDING waiting for warehouse; RUNNING running; SUCCEEDED execution was successful, result data available for fetch; FAILED execution failed, reason for failure described in the accompanying error message; CANCELED user canceled; CLOSED execution successful, and statement closed, result no longer available for fetch.'
        )
        .optional(),
      error: z
        .object({
          error_code: z
            .string()
            .describe('Error code, e.g. BAD_REQUEST or INTERNAL_ERROR.')
            .optional(),
          message: z
            .string()
            .describe('A brief summary of the error condition.')
            .optional(),
        })
        .describe('Error details when the statement status is FAILED.')
        .optional(),
      sql_state: z
        .string()
        .describe(
          'SQLSTATE error code returned when the statement execution fails. Only populated when the statement status is FAILED.'
        )
        .optional(),
    })
    .describe(
      'The status response includes execution state and if relevant, error information.'
    )
    .optional(),
  manifest: z
    .object({
      format: z
        .enum(['JSON_ARRAY', 'ARROW_STREAM', 'CSV'])
        .describe('The result format.')
        .optional(),
      schema: z
        .object({
          column_count: z
            .number()
            .int()
            .describe('The number of columns in the result set.')
            .optional(),
          columns: z
            .array(
              z.object({
                name: z.string().describe('The name of the column.').optional(),
                position: z
                  .number()
                  .int()
                  .describe(
                    'The ordinal position of the column (starting at position 0).'
                  )
                  .optional(),
                type_name: z
                  .string()
                  .describe(
                    "The name of the base data type. This doesn't include details for complex types such as STRUCT, MAP or ARRAY."
                  )
                  .optional(),
                type_text: z
                  .string()
                  .describe('The full SQL type specification.')
                  .optional(),
                type_precision: z
                  .number()
                  .int()
                  .describe(
                    'Specifies the number of digits in a number. This applies to the DECIMAL type.'
                  )
                  .optional(),
                type_scale: z
                  .number()
                  .int()
                  .describe(
                    'Specifies the number of digits to the right of the decimal point in a number. This applies to the DECIMAL type.'
                  )
                  .optional(),
                type_interval_type: z
                  .string()
                  .describe('The format of the interval type.')
                  .optional(),
              })
            )
            .describe('Ordered column descriptions.')
            .optional(),
        })
        .describe('The schema is an ordered list of column descriptions.')
        .optional(),
      chunks: z
        .array(
          z.object({
            byte_count: z
              .number()
              .int()
              .describe(
                'The number of bytes in the result chunk. This field is not available when using INLINE disposition.'
              )
              .optional(),
            chunk_index: z
              .number()
              .int()
              .describe(
                'The position within the sequence of result set chunks.'
              )
              .optional(),
            row_count: z
              .number()
              .int()
              .describe('The number of rows within the result chunk.')
              .optional(),
            row_offset: z
              .number()
              .int()
              .describe('The starting row offset within the result set.')
              .optional(),
          })
        )
        .describe('Array of result set chunk metadata.')
        .optional(),
      total_byte_count: z
        .number()
        .int()
        .describe(
          'The total number of bytes in the result set. This field is not available when using INLINE disposition.'
        )
        .optional(),
      total_chunk_count: z
        .number()
        .int()
        .describe(
          'The total number of chunks that the result set has been divided into.'
        )
        .optional(),
      total_row_count: z
        .number()
        .int()
        .describe('The total number of rows in the result set.')
        .optional(),
      truncated: z
        .boolean()
        .describe(
          'Indicates whether the result is truncated due to row_limit or byte_limit.'
        )
        .optional(),
    })
    .describe(
      'The result manifest provides schema and metadata for the result set.'
    )
    .optional(),
  result: z
    .object({
      byte_count: z
        .number()
        .int()
        .describe(
          'The number of bytes in the result chunk. This field is not available when using INLINE disposition.'
        )
        .optional(),
      chunk_index: z
        .number()
        .int()
        .describe('The position within the sequence of result set chunks.')
        .optional(),
      row_count: z
        .number()
        .int()
        .describe('The number of rows within the result chunk.')
        .optional(),
      row_offset: z
        .number()
        .int()
        .describe('The starting row offset within the result set.')
        .optional(),
      data_array: z
        .array(z.array(z.string().nullable()))
        .describe(
          'The JSON_ARRAY format is an array of arrays of values, where each non-null value is formatted as a string. Null values are encoded as JSON null.'
        )
        .optional(),
      next_chunk_index: z
        .number()
        .int()
        .describe(
          'When fetching, provides the chunk_index for the next chunk. If absent, indicates there are no more chunks.'
        )
        .optional(),
      next_chunk_internal_link: z
        .string()
        .describe(
          'When fetching, provides a link to fetch the next chunk. This link is an absolute path to be joined with your workspace URL, and should be treated as an opaque link.'
        )
        .optional(),
      external_links: z
        .array(
          z.object({
            byte_count: z
              .number()
              .int()
              .describe('The number of bytes in the result chunk.')
              .optional(),
            chunk_index: z
              .number()
              .int()
              .describe(
                'The position within the sequence of result set chunks.'
              )
              .optional(),
            expiration: z
              .string()
              .describe(
                'Indicates the date-time that the given external link will expire and becomes invalid, after which point a new external_link must be requested.'
              )
              .optional(),
            external_link: z
              .string()
              .describe(
                'A URL pointing to a chunk of result data, hosted by an external service, with a short expiration time (<= 15 minutes).'
              )
              .optional(),
            http_headers: z
              .record(z.string(), z.string())
              .describe(
                'HTTP headers that must be included with a GET request to the external_link.'
              )
              .optional(),
            next_chunk_index: z
              .number()
              .int()
              .describe(
                'When fetching, provides the chunk_index for the next chunk.'
              )
              .optional(),
            next_chunk_internal_link: z
              .string()
              .describe(
                'When fetching, provides a link to fetch the next chunk.'
              )
              .optional(),
            row_count: z
              .number()
              .int()
              .describe('The number of rows within the result chunk.')
              .optional(),
            row_offset: z
              .number()
              .int()
              .describe('The starting row offset within the result set.')
              .optional(),
          })
        )
        .describe(
          'External links pointing to chunks of result data on cloud storage (EXTERNAL_LINKS disposition only). These URLs contain temporary credentials and should be treated as sensitive.'
        )
        .optional(),
    })
    .describe('Result data chunk (first chunk when INLINE).')
    .optional(),
});

export const DatabricksSqlParamsSchema = z.discriminatedUnion('operation', [
  z.object({
    operation: z
      .literal('execute_statement')
      .describe('Executes a SQL statement on a SQL warehouse.'),
    workspaceUrl: z
      .string()
      .url()
      .describe(
        'Per-workspace Databricks URL (e.g. https://dbc-a1b2c3d4-e5f6.cloud.databricks.com)'
      ),
    statement: z
      .string()
      .describe(
        'The SQL statement to execute. The statement can optionally be parameterized, see parameters. The maximum query text size is 16 MiB.'
      ),
    warehouse_id: z
      .string()
      .describe('Warehouse upon which to execute a statement.'),
    catalog: z
      .string()
      .describe(
        'Sets default catalog for statement execution, similar to USE CATALOG in SQL.'
      )
      .optional(),
    schema: z
      .string()
      .describe(
        'Sets default schema for statement execution, similar to USE SCHEMA in SQL.'
      )
      .optional(),
    parameters: z
      .array(
        z.object({
          name: z
            .string()
            .describe(
              'The name of a parameter marker to be substituted in the statement.'
            ),
          type: z
            .string()
            .describe(
              'The data type, given as a string. For example INT, STRING, DECIMAL(10,2). If no type is given the type is assumed to be STRING. Complex types, such as ARRAY, MAP, and STRUCT are not supported.'
            )
            .optional(),
          value: z
            .string()
            .describe(
              'The value to substitute, represented as a string. If omitted, the value is interpreted as NULL.'
            )
            .optional(),
        })
      )
      .describe(
        'A list of parameters to pass into a SQL statement containing parameter markers. A parameter consists of a name, a value, and optionally a type. To represent a NULL value, the value field may be omitted or set to null explicitly. If the type field is omitted, the value is interpreted as a string.'
      )
      .optional(),
    byte_limit: z
      .number()
      .int()
      .describe(
        "Applies the given byte limit to the statement's result size. Byte counts are based on internal data representations and might not match the final size in the requested format."
      )
      .optional(),
    row_limit: z
      .number()
      .int()
      .describe(
        "Applies the given row limit to the statement's result set, but unlike the LIMIT clause in SQL, it also sets the truncated field in the response to indicate whether the result was trimmed due to the limit or not."
      )
      .optional(),
    disposition: z
      .enum(['INLINE', 'EXTERNAL_LINKS'])
      .describe(
        'The fetch disposition provides two modes of fetching results, INLINE and EXTERNAL_LINKS. INLINE results are limited to 25 MiB; EXTERNAL_LINKS returns URLs pointing to cloud storage for result sets up to 100 GiB.'
      )
      .optional(),
    format: z
      .enum(['JSON_ARRAY', 'ARROW_STREAM', 'CSV'])
      .describe(
        'Statement execution supports three result formats, JSON_ARRAY (default), ARROW_STREAM, and CSV. ARROW_STREAM and CSV are supported only with EXTERNAL_LINKS disposition.'
      )
      .optional(),
    wait_timeout: z
      .string()
      .describe(
        "The time in seconds the call will wait for the statement's result set as Ns, where N can be set to 0 or to a value between 5 and 50. When set to 0s, the statement executes in asynchronous mode."
      )
      .optional(),
    on_wait_timeout: z
      .enum(['CONTINUE', 'CANCEL'])
      .describe(
        'When wait_timeout > 0s, determines what happens when the timeout is reached. CONTINUE keeps executing asynchronously and returns a statement ID for polling; CANCEL cancels the execution and returns with a CANCELED state.'
      )
      .optional(),
    credentials: BaseCredentialsSchema,
  }),
  z.object({
    operation: z
      .literal('get_statement')
      .describe(
        'Gets status, manifest, and result data for an executed statement.'
      ),
    workspaceUrl: z
      .string()
      .url()
      .describe(
        'Per-workspace Databricks URL (e.g. https://dbc-a1b2c3d4-e5f6.cloud.databricks.com)'
      ),
    statement_id: z
      .string()
      .describe(
        'The statement ID is returned upon successfully submitting a SQL statement, and is a required reference for all subsequent calls.'
      ),
    credentials: BaseCredentialsSchema,
  }),
]);

export const DatabricksSqlResultSchema = z.discriminatedUnion('operation', [
  z
    .object({
      operation: z.literal('execute_statement'),
      success: z.boolean().describe('Whether the operation succeeded'),
      error: z.string().describe('Error message if operation failed'),
    })
    .merge(ExecuteStatementPayloadSchema),
  z
    .object({
      operation: z.literal('get_statement'),
      success: z.boolean().describe('Whether the operation succeeded'),
      error: z.string().describe('Error message if operation failed'),
    })
    .merge(GetStatementPayloadSchema),
]);

export type DatabricksSqlParamsInput = z.input<
  typeof DatabricksSqlParamsSchema
>;
export type DatabricksSqlParams = z.output<typeof DatabricksSqlParamsSchema>;
export type DatabricksSqlResult = z.output<typeof DatabricksSqlResultSchema>;

export type DatabricksSqlExecuteStatementParams = Extract<
  DatabricksSqlParamsInput,
  { operation: 'execute_statement' }
>;
export type DatabricksSqlGetStatementParams = Extract<
  DatabricksSqlParamsInput,
  { operation: 'get_statement' }
>;

export type DatabricksSqlOperationResult<
  T extends DatabricksSqlParams['operation'],
> = Extract<DatabricksSqlResult, { operation: T }>;
