/**
 * ServiceBubble class (raw-fetch pattern) for the 'stripe-payments-api' bubble.
 *
 * GENERATED by @bubblelab/bubble-appgen from stripe-payments.yaml — do not hand-edit;
 * re-run `pnpm --filter @bubblelab/bubble-appgen generate:stripe-payments-api` instead.
 * Vendor docs: https://docs.stripe.com/api
 */

import { ServiceBubble } from '../../../types/service-bubble-class.js';
import type { BubbleContext } from '../../../types/bubble.js';
import { CredentialType } from '@bubblelab/shared-schemas';
import { STRIPE_PAYMENTS_API_OPERATION_METADATA } from './stripe-payments-api.metadata.js';
import {
  StripePaymentsApiParamsSchema,
  StripePaymentsApiResultSchema,
  CreatePaymentIntentPayloadSchema,
  CreatePaymentLinkPayloadSchema,
  CreatePayoutPayloadSchema,
  CreateRefundPayloadSchema,
  ListChargesPayloadSchema,
  GetBalancePayloadSchema,
  type StripePaymentsApiParams,
  type StripePaymentsApiParamsInput,
  type StripePaymentsApiResult,
} from './stripe-payments-api.schema.js';

/** Strip a trailing slash so path concatenation stays canonical. */
function trimBaseUrl(url: string): string {
  return url.endsWith('/') ? url.slice(0, -1) : url;
}

/** Serialize defined query params; returns '' or '?k=v&…'. */
function buildQuery(
  params: Record<string, string | number | boolean | undefined>
): string {
  const search = new URLSearchParams();
  for (const [key, value] of Object.entries(params)) {
    if (value !== undefined) search.set(key, String(value));
  }
  const qs = search.toString();
  return qs.length > 0 ? `?${qs}` : '';
}

/** Drop undefined values before JSON body serialization. */
function pruneUndefined(
  record: Record<string, unknown>
): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(record)) {
    if (value !== undefined) out[key] = value;
  }
  return out;
}

/**
 * Bracket-flatten nested values into application/x-www-form-urlencoded
 * pairs (OpenAPI deepObject style: metadata[key]=v, line_items[0][price]=v).
 */
function encodeForm(record: Record<string, unknown>): string {
  const search = new URLSearchParams();
  const walk = (key: string, value: unknown): void => {
    if (value === undefined || value === null) return;
    if (Array.isArray(value)) {
      value.forEach((item, index) => walk(`${key}[${index}]`, item));
    } else if (typeof value === 'object') {
      for (const [child, childValue] of Object.entries(value)) {
        walk(`${key}[${child}]`, childValue);
      }
    } else {
      search.append(key, String(value));
    }
  };
  for (const [key, value] of Object.entries(record)) walk(key, value);
  return search.toString();
}

export class StripePaymentsApiBubble<
  T extends StripePaymentsApiParamsInput = StripePaymentsApiParamsInput,
> extends ServiceBubble<
  T,
  Extract<StripePaymentsApiResult, { operation: T['operation'] }>
> {
  static readonly type = 'service' as const;
  static readonly service = 'stripe';
  // S5 auth (openapi): inferred from securityScheme bearerAuth (http bearer)
  static readonly authType = 'apikey' as const;
  static readonly bubbleName = 'stripe-payments-api';
  static readonly operationMetadata = STRIPE_PAYMENTS_API_OPERATION_METADATA;
  static readonly schema = StripePaymentsApiParamsSchema;
  static readonly resultSchema = StripePaymentsApiResultSchema;
  static readonly shortDescription =
    'Stripe Payments API integration generated from the official OpenAPI spec (payment intents, payment links, payouts, refunds, charges, balance)';
  static readonly longDescription = `
    Stripe Payments API integration generated from the official OpenAPI spec (payment intents, payment links, payouts, refunds, charges, balance)

    Operations (generated from the vendor OpenAPI spec):
    - create_payment_intent [side-effect: write]: Create a PaymentIntent
    - create_payment_link [side-effect: write]: Create a payment link
    - create_payout [side-effect: write]: Create a payout
    - create_refund [side-effect: write]: Create customer balance refund
    - list_charges [side-effect: read]: List all charges
    - get_balance [side-effect: read]: Retrieve balance

    Credential: STRIPE_CRED (bearer token) + per-account baseUrl.
  `;
  static readonly alias = 'stripe-pay';

  constructor(
    params: T = {
      operation: 'list_charges',
      baseUrl: 'https://api.stripe.com',
    } as T,
    context?: BubbleContext
  ) {
    super(params, context);
  }

  private requestHeaders(
    token: string,
    contentType?: 'json' | 'form'
  ): Record<string, string> {
    const headers: Record<string, string> = {
      Authorization: `Bearer ${token}`,
      Accept: 'application/json',
      'User-Agent': 'bubblelab/1.0',
    };
    if (contentType === 'json') {
      headers['Content-Type'] = 'application/json';
    }
    if (contentType === 'form') {
      headers['Content-Type'] = 'application/x-www-form-urlencoded';
    }
    return headers;
  }

  public async testCredential(): Promise<boolean> {
    const token = this.chooseCredential();
    if (!token) {
      throw new Error('stripe-payments-api credentials are required');
    }
    const params = { baseUrl: this.params.baseUrl };
    // Probe: GET /v1/charges (list_charges) with a synthesized handle.
    // 401/403 mean the credential was rejected; any other status means it was accepted.
    const response = await fetch(`${trimBaseUrl(params.baseUrl)}/v1/charges`, {
      method: 'GET',
      headers: this.requestHeaders(token),
    });
    return response.status !== 401 && response.status !== 403;
  }

  protected chooseCredential(): string | undefined {
    const credentials = this.params.credentials;
    if (!credentials || typeof credentials !== 'object') {
      return undefined;
    }
    return credentials[CredentialType.STRIPE_CRED];
  }

  protected async performAction(
    context?: BubbleContext
  ): Promise<Extract<StripePaymentsApiResult, { operation: T['operation'] }>> {
    void context;
    const { operation } = this.params;
    switch (operation) {
      case 'create_payment_intent':
        return this.handleCreatePaymentIntent() as Promise<
          Extract<StripePaymentsApiResult, { operation: T['operation'] }>
        >;
      case 'create_payment_link':
        return this.handleCreatePaymentLink() as Promise<
          Extract<StripePaymentsApiResult, { operation: T['operation'] }>
        >;
      case 'create_payout':
        return this.handleCreatePayout() as Promise<
          Extract<StripePaymentsApiResult, { operation: T['operation'] }>
        >;
      case 'create_refund':
        return this.handleCreateRefund() as Promise<
          Extract<StripePaymentsApiResult, { operation: T['operation'] }>
        >;
      case 'list_charges':
        return this.handleListCharges() as Promise<
          Extract<StripePaymentsApiResult, { operation: T['operation'] }>
        >;
      case 'get_balance':
        return this.handleGetBalance() as Promise<
          Extract<StripePaymentsApiResult, { operation: T['operation'] }>
        >;
      default:
        return {
          operation: operation as T['operation'],
          success: false,
          error: `Unknown operation: ${String(operation)}`,
        } as Extract<StripePaymentsApiResult, { operation: T['operation'] }>;
    }
  }

  private async handleCreatePaymentIntent(): Promise<
    Extract<StripePaymentsApiResult, { operation: 'create_payment_intent' }>
  > {
    const params = StripePaymentsApiParamsSchema.parse(this.params) as Extract<
      StripePaymentsApiParams,
      { operation: 'create_payment_intent' }
    >;
    try {
      const token = this.chooseCredential();
      if (!token) {
        return {
          operation: 'create_payment_intent',
          success: false,
          error: 'STRIPE_CRED credential not found',
        };
      }
      const url = `${trimBaseUrl(params.baseUrl)}/v1/payment_intents`;
      const body = pruneUndefined({
        amount: params.amount,
        currency: params.currency,
        automatic_payment_methods: params.automatic_payment_methods,
        confirm: params.confirm,
        customer: params.customer,
        description: params.description,
        metadata: params.metadata,
        payment_method: params.payment_method,
        receipt_email: params.receipt_email,
        statement_descriptor: params.statement_descriptor,
      });
      const response = await fetch(url, {
        method: 'POST',
        headers: this.requestHeaders(token, 'form'),
        body: encodeForm(body),
      });
      if (!response.ok) {
        const errorText = await response.text();
        return {
          operation: 'create_payment_intent',
          success: false,
          error: `stripe-payments-api API error (${response.status}): ${errorText}`,
        };
      }
      const payload = CreatePaymentIntentPayloadSchema.parse(
        await response.json()
      );
      return {
        operation: 'create_payment_intent',
        success: true,
        error: '',
        ...payload,
      };
    } catch (error) {
      return {
        operation: 'create_payment_intent',
        success: false,
        error:
          error instanceof Error ? error.message : 'Unknown error occurred',
      };
    }
  }

  private async handleCreatePaymentLink(): Promise<
    Extract<StripePaymentsApiResult, { operation: 'create_payment_link' }>
  > {
    const params = StripePaymentsApiParamsSchema.parse(this.params) as Extract<
      StripePaymentsApiParams,
      { operation: 'create_payment_link' }
    >;
    try {
      const token = this.chooseCredential();
      if (!token) {
        return {
          operation: 'create_payment_link',
          success: false,
          error: 'STRIPE_CRED credential not found',
        };
      }
      const url = `${trimBaseUrl(params.baseUrl)}/v1/payment_links`;
      const body = pruneUndefined({
        line_items: params.line_items,
        currency: params.currency,
        allow_promotion_codes: params.allow_promotion_codes,
        after_completion: params.after_completion,
        metadata: params.metadata,
      });
      const response = await fetch(url, {
        method: 'POST',
        headers: this.requestHeaders(token, 'form'),
        body: encodeForm(body),
      });
      if (!response.ok) {
        const errorText = await response.text();
        return {
          operation: 'create_payment_link',
          success: false,
          error: `stripe-payments-api API error (${response.status}): ${errorText}`,
        };
      }
      const payload = CreatePaymentLinkPayloadSchema.parse(
        await response.json()
      );
      return {
        operation: 'create_payment_link',
        success: true,
        error: '',
        ...payload,
      };
    } catch (error) {
      return {
        operation: 'create_payment_link',
        success: false,
        error:
          error instanceof Error ? error.message : 'Unknown error occurred',
      };
    }
  }

  private async handleCreatePayout(): Promise<
    Extract<StripePaymentsApiResult, { operation: 'create_payout' }>
  > {
    const params = StripePaymentsApiParamsSchema.parse(this.params) as Extract<
      StripePaymentsApiParams,
      { operation: 'create_payout' }
    >;
    try {
      const token = this.chooseCredential();
      if (!token) {
        return {
          operation: 'create_payout',
          success: false,
          error: 'STRIPE_CRED credential not found',
        };
      }
      const url = `${trimBaseUrl(params.baseUrl)}/v1/payouts`;
      const body = pruneUndefined({
        amount: params.amount,
        currency: params.currency,
        description: params.description,
        destination: params.destination,
        metadata: params.metadata,
        method: params.method,
        source_type: params.source_type,
        statement_descriptor: params.statement_descriptor,
      });
      const response = await fetch(url, {
        method: 'POST',
        headers: this.requestHeaders(token, 'form'),
        body: encodeForm(body),
      });
      if (!response.ok) {
        const errorText = await response.text();
        return {
          operation: 'create_payout',
          success: false,
          error: `stripe-payments-api API error (${response.status}): ${errorText}`,
        };
      }
      const payload = CreatePayoutPayloadSchema.parse(await response.json());
      return {
        operation: 'create_payout',
        success: true,
        error: '',
        ...payload,
      };
    } catch (error) {
      return {
        operation: 'create_payout',
        success: false,
        error:
          error instanceof Error ? error.message : 'Unknown error occurred',
      };
    }
  }

  private async handleCreateRefund(): Promise<
    Extract<StripePaymentsApiResult, { operation: 'create_refund' }>
  > {
    const params = StripePaymentsApiParamsSchema.parse(this.params) as Extract<
      StripePaymentsApiParams,
      { operation: 'create_refund' }
    >;
    try {
      const token = this.chooseCredential();
      if (!token) {
        return {
          operation: 'create_refund',
          success: false,
          error: 'STRIPE_CRED credential not found',
        };
      }
      const url = `${trimBaseUrl(params.baseUrl)}/v1/refunds`;
      const body = pruneUndefined({
        amount: params.amount,
        charge: params.charge,
        payment_intent: params.payment_intent,
        currency: params.currency,
        customer: params.customer,
        metadata: params.metadata,
        reason: params.reason,
        instructions_email: params.instructions_email,
      });
      const response = await fetch(url, {
        method: 'POST',
        headers: this.requestHeaders(token, 'form'),
        body: encodeForm(body),
      });
      if (!response.ok) {
        const errorText = await response.text();
        return {
          operation: 'create_refund',
          success: false,
          error: `stripe-payments-api API error (${response.status}): ${errorText}`,
        };
      }
      const payload = CreateRefundPayloadSchema.parse(await response.json());
      return {
        operation: 'create_refund',
        success: true,
        error: '',
        ...payload,
      };
    } catch (error) {
      return {
        operation: 'create_refund',
        success: false,
        error:
          error instanceof Error ? error.message : 'Unknown error occurred',
      };
    }
  }

  private async handleListCharges(): Promise<
    Extract<StripePaymentsApiResult, { operation: 'list_charges' }>
  > {
    const params = StripePaymentsApiParamsSchema.parse(this.params) as Extract<
      StripePaymentsApiParams,
      { operation: 'list_charges' }
    >;
    try {
      const token = this.chooseCredential();
      if (!token) {
        return {
          operation: 'list_charges',
          success: false,
          error: 'STRIPE_CRED credential not found',
        };
      }
      const query = buildQuery({
        customer: params.customer,
        ending_before: params.ending_before,
        limit: params.limit,
        payment_intent: params.payment_intent,
        starting_after: params.starting_after,
        transfer_group: params.transfer_group,
      });
      const url = `${trimBaseUrl(params.baseUrl)}/v1/charges${query}`;
      const response = await fetch(url, {
        method: 'GET',
        headers: this.requestHeaders(token),
      });
      if (!response.ok) {
        const errorText = await response.text();
        return {
          operation: 'list_charges',
          success: false,
          error: `stripe-payments-api API error (${response.status}): ${errorText}`,
        };
      }
      const payload = ListChargesPayloadSchema.parse(await response.json());
      return {
        operation: 'list_charges',
        success: true,
        error: '',
        ...payload,
      };
    } catch (error) {
      return {
        operation: 'list_charges',
        success: false,
        error:
          error instanceof Error ? error.message : 'Unknown error occurred',
      };
    }
  }

  private async handleGetBalance(): Promise<
    Extract<StripePaymentsApiResult, { operation: 'get_balance' }>
  > {
    const params = StripePaymentsApiParamsSchema.parse(this.params) as Extract<
      StripePaymentsApiParams,
      { operation: 'get_balance' }
    >;
    try {
      const token = this.chooseCredential();
      if (!token) {
        return {
          operation: 'get_balance',
          success: false,
          error: 'STRIPE_CRED credential not found',
        };
      }
      const url = `${trimBaseUrl(params.baseUrl)}/v1/balance`;
      const response = await fetch(url, {
        method: 'GET',
        headers: this.requestHeaders(token),
      });
      if (!response.ok) {
        const errorText = await response.text();
        return {
          operation: 'get_balance',
          success: false,
          error: `stripe-payments-api API error (${response.status}): ${errorText}`,
        };
      }
      const payload = GetBalancePayloadSchema.parse(await response.json());
      return { operation: 'get_balance', success: true, error: '', ...payload };
    } catch (error) {
      return {
        operation: 'get_balance',
        success: false,
        error:
          error instanceof Error ? error.message : 'Unknown error occurred',
      };
    }
  }
}
