/**
 * Zod contract (params + results) for the 'stripe-payments-api' bubble.
 *
 * GENERATED by @bubblelab/bubble-appgen from stripe-payments.yaml — do not hand-edit;
 * re-run `pnpm --filter @bubblelab/bubble-appgen generate:stripe-payments-api` instead.
 * Vendor docs: https://docs.stripe.com/api
 */

import { z } from 'zod';
import { CredentialType } from '@bubblelab/shared-schemas';

// Base credentials schema shared by every operation branch
const BaseCredentialsSchema = z
  .record(z.nativeEnum(CredentialType), z.string())
  .optional()
  .describe('Object mapping credential types to values (injected at runtime)');

/** Documented 2xx response payload of CreatePaymentIntent (statuses: 200); all fields optional because presence varies by status code. */
export const CreatePaymentIntentPayloadSchema = z.object({
  amount: z
    .number()
    .int()
    .describe(
      'Amount intended to be collected by this PaymentIntent. A positive integer representing how much to charge in the [smallest currency unit](https://docs.stripe.com/currencies#zero-decimal) (e.g., 100 c…'
    )
    .optional(),
  amount_capturable: z
    .number()
    .int()
    .describe('Amount that can be captured from this PaymentIntent.')
    .optional(),
  amount_details: z
    .union([
      z
        .record(z.string(), z.unknown())
        .describe(
          'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
        ),
      z
        .record(z.string(), z.unknown())
        .describe(
          'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
        ),
    ])
    .optional(),
  amount_received: z
    .number()
    .int()
    .describe('Amount that this PaymentIntent collects.')
    .optional(),
  application: z
    .union([
      z.string().max(5000),
      z
        .record(z.string(), z.unknown())
        .describe(
          'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
        ),
    ])
    .describe('ID of the Connect application that created the PaymentIntent.')
    .optional(),
  application_fee_amount: z
    .number()
    .int()
    .nullable()
    .describe(
      "The amount of the application fee (if any) that will be requested to be applied to the payment and transferred to the application owner's Stripe account. The amount of the application fee collected w…"
    )
    .optional(),
  automatic_payment_methods: z
    .record(z.string(), z.unknown())
    .describe(
      'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
    )
    .optional(),
  canceled_at: z
    .number()
    .int()
    .nullable()
    .describe(
      'Populated when `status` is `canceled`, this is the time at which the PaymentIntent was canceled. Measured in seconds since the Unix epoch.'
    )
    .optional(),
  cancellation_reason: z
    .enum([
      'abandoned',
      'automatic',
      'duplicate',
      'expired',
      'failed_invoice',
      'fraudulent',
      'requested_by_customer',
      'void_invoice',
    ])
    .nullable()
    .describe(
      'Reason for cancellation of this PaymentIntent, either user-provided (`duplicate`, `fraudulent`, `requested_by_customer`, or `abandoned`) or generated by Stripe internally (`failed_invoice`, `void_inv…'
    )
    .optional(),
  capture_method: z
    .enum(['automatic', 'automatic_async', 'manual'])
    .describe(
      "Controls when the funds will be captured from the customer's account."
    )
    .optional(),
  client_secret: z
    .string()
    .max(5000)
    .nullable()
    .describe(
      'The client secret of this PaymentIntent. Used for client-side retrieval using a publishable key. The client secret can be used to complete a payment from your frontend. It should not be stored, logge…'
    )
    .optional(),
  confirmation_method: z
    .enum(['automatic', 'manual'])
    .describe(
      'Describes whether we can confirm this PaymentIntent automatically, or if it requires customer action to confirm the payment.'
    )
    .optional(),
  created: z
    .number()
    .int()
    .describe(
      'Time at which the object was created. Measured in seconds since the Unix epoch.'
    )
    .optional(),
  currency: z
    .string()
    .describe(
      'Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https://stripe.com/docs/currencies).'
    )
    .optional(),
  customer: z
    .union([
      z.string().max(5000),
      z
        .record(z.string(), z.unknown())
        .describe(
          'This object represents a customer of your business. Use it to [create recurring charges](https://docs.stripe.com/invoicing/customer), [save payment](https://docs.stripe.com/payments/save-during-payme… (nested object collapsed at trim depth limit)'
        ),
      z
        .record(z.string(), z.unknown())
        .describe(
          'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
        ),
    ])
    .describe(
      'ID of the Customer this PaymentIntent belongs to, if one exists. Payment methods attached to other Customers cannot be used with this PaymentIntent. If [setup_future_usage](https://api.stripe.com#pay…'
    )
    .optional(),
  customer_account: z
    .string()
    .max(5000)
    .nullable()
    .describe(
      'ID of the Account representing the customer that this PaymentIntent belongs to, if one exists. Payment methods attached to other Accounts cannot be used with this PaymentIntent. If [setup_future_usag…'
    )
    .optional(),
  description: z
    .string()
    .max(5000)
    .nullable()
    .describe(
      'An arbitrary string attached to the object. Often useful for displaying to users.'
    )
    .optional(),
  excluded_payment_method_types: z
    .array(
      z.enum([
        'acss_debit',
        'affirm',
        'afterpay_clearpay',
        'alipay',
        'alma',
        'amazon_pay',
        'au_becs_debit',
        'bacs_debit',
        'bancontact',
        'billie',
        'bizum',
        'blik',
        'boleto',
        'card',
        'cashapp',
        'crypto',
        'customer_balance',
        'eps',
        'fpx',
        'giropay',
        'grabpay',
        'ideal',
        'kakao_pay',
        'klarna',
        'konbini',
        'kr_card',
        'mb_way',
        'mobilepay',
        'multibanco',
        'naver_pay',
        'nz_bank_account',
        'oxxo',
        'p24',
        'pay_by_bank',
        'payco',
        'paynow',
        'paypal',
        'payto',
        'pix',
        'promptpay',
        'revolut_pay',
        'samsung_pay',
        'satispay',
        'scalapay',
        'sepa_debit',
        'sofort',
        'sunbit',
        'swish',
        'twint',
        'upi',
        'us_bank_account',
        'wechat_pay',
        'zip',
      ])
    )
    .nullable()
    .describe(
      'The list of payment method types to exclude from use with this payment.'
    )
    .optional(),
  hooks: z
    .object({
      inputs: z
        .record(z.string(), z.unknown())
        .describe(
          'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
        )
        .optional(),
    })
    .optional(),
  id: z
    .string()
    .max(5000)
    .describe('Unique identifier for the object.')
    .optional(),
  last_payment_error: z
    .record(z.string(), z.unknown())
    .describe(
      'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
    )
    .optional(),
  latest_charge: z
    .union([
      z.string().max(5000),
      z
        .record(z.string(), z.unknown())
        .describe(
          'The `Charge` object represents a single attempt to move money into your Stripe account. PaymentIntent confirmation is the most common way to create Charges, but [Account Debits](https://docs.stripe.c… (nested object collapsed at trim depth limit)'
        ),
    ])
    .describe(
      'ID of the latest [Charge object](https://docs.stripe.com/api/charges) created by this PaymentIntent. This property is `null` until PaymentIntent confirmation is attempted.'
    )
    .optional(),
  livemode: z
    .boolean()
    .describe(
      'If the object exists in live mode, the value is `true`. If the object exists in test mode, the value is `false`.'
    )
    .optional(),
  managed_payments: z
    .record(z.string(), z.unknown())
    .describe(
      'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
    )
    .optional(),
  metadata: z
    .record(z.string(), z.string().max(500))
    .describe(
      'Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Learn m…'
    )
    .optional(),
  next_action: z
    .record(z.string(), z.unknown())
    .describe(
      'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
    )
    .optional(),
  object: z
    .enum(['payment_intent'])
    .describe(
      "String representing the object's type. Objects of the same type share the same value."
    )
    .optional(),
  on_behalf_of: z
    .union([
      z.string().max(5000),
      z
        .record(z.string(), z.unknown())
        .describe(
          'For new integrations, we recommend using the [Accounts v2 API](/api/v2/core/accounts), in place of /v1/accounts and /v1/customers to represent a user. This is an object representing a Stripe account.… (nested object collapsed at trim depth limit)'
        ),
    ])
    .describe(
      'You can specify the settlement merchant as the connected account using the `on_behalf_of` attribute on the charge. See the PaymentIntents [use case for connected accounts](/payments/connected-account…'
    )
    .optional(),
  payment_details: z
    .object({
      customer_reference: z
        .string()
        .max(5000)
        .nullable()
        .describe(
          'A unique value to identify the customer. This field is available only for card payments. This field is truncated to 25 alphanumeric characters, excluding spaces, before being sent to card networks.'
        )
        .optional(),
      order_reference: z
        .string()
        .max(5000)
        .nullable()
        .describe(
          'A unique value assigned by the business to identify the transaction. Required for L2 and L3 rates. For Cards, this field is truncated to 25 alphanumeric characters, excluding spaces, before being sen…'
        )
        .optional(),
    })
    .optional(),
  payment_method: z
    .union([
      z.string().max(5000),
      z
        .record(z.string(), z.unknown())
        .describe(
          "PaymentMethod objects represent your customer's payment instruments. You can use them with [PaymentIntents](https://docs.stripe.com/payments/payment-intents) to collect payments or save them to Custo… (nested object collapsed at trim depth limit)"
        ),
    ])
    .describe('ID of the payment method used in this PaymentIntent.')
    .optional(),
  payment_method_configuration_details: z
    .record(z.string(), z.unknown())
    .describe(
      'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
    )
    .optional(),
  payment_method_options: z
    .record(z.string(), z.unknown())
    .describe(
      'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
    )
    .optional(),
  payment_method_types: z
    .array(z.string().max(5000))
    .describe(
      'The list of payment method types (e.g. card) that this PaymentIntent is allowed to use. A comprehensive list of valid payment method types can be found [here](https://docs.stripe.com/api/payment_meth…'
    )
    .optional(),
  presentment_details: z
    .object({
      presentment_amount: z
        .number()
        .int()
        .describe(
          'Amount intended to be collected by this payment, denominated in `presentment_currency`.'
        ),
      presentment_currency: z
        .string()
        .max(5000)
        .describe('Currency presented to the customer during payment.'),
    })
    .optional(),
  processing: z
    .record(z.string(), z.unknown())
    .describe(
      'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
    )
    .optional(),
  receipt_email: z
    .string()
    .max(5000)
    .nullable()
    .describe(
      'Email address that the receipt for the resulting payment will be sent to. If `receipt_email` is specified for a payment in live mode, a receipt will be sent regardless of your [email settings](https:…'
    )
    .optional(),
  review: z
    .union([
      z.string().max(5000),
      z
        .record(z.string(), z.unknown())
        .describe(
          'Reviews can be used to supplement automated fraud detection with human expertise. Learn more about [Radar](/radar) and reviewing payments [here](https://docs.stripe.com/radar/reviews). (nested object collapsed at trim depth limit)'
        ),
    ])
    .describe('ID of the review associated with this PaymentIntent, if any.')
    .optional(),
  setup_future_usage: z
    .enum(['off_session', 'on_session'])
    .nullable()
    .describe(
      "Indicates that you intend to make future payments with this PaymentIntent's payment method. If you provide a Customer with the PaymentIntent, you can use this parameter to [attach the payment method]…"
    )
    .optional(),
  shipping: z
    .record(z.string(), z.unknown())
    .describe(
      'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
    )
    .optional(),
  statement_descriptor: z
    .string()
    .max(5000)
    .nullable()
    .describe(
      "Text that appears on the customer's statement as the statement descriptor for a non-card charge. This value overrides the account's default statement descriptor. For information about requirements, i…"
    )
    .optional(),
  statement_descriptor_suffix: z
    .string()
    .max(5000)
    .nullable()
    .describe(
      "Provides information about a card charge. Concatenated to the account's [statement descriptor prefix](https://docs.stripe.com/get-started/account/statement-descriptors#static) to form the complete st…"
    )
    .optional(),
  status: z
    .enum([
      'canceled',
      'processing',
      'requires_action',
      'requires_capture',
      'requires_confirmation',
      'requires_payment_method',
      'succeeded',
    ])
    .describe(
      'Status of this PaymentIntent, one of `requires_payment_method`, `requires_confirmation`, `requires_action`, `processing`, `requires_capture`, `canceled`, or `succeeded`. Read more about each PaymentI…'
    )
    .optional(),
  transfer_data: z
    .record(z.string(), z.unknown())
    .describe(
      'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
    )
    .optional(),
  transfer_group: z
    .string()
    .max(5000)
    .nullable()
    .describe(
      'A string that identifies the resulting payment as part of a group. Learn more about the [use case for connected accounts](https://docs.stripe.com/connect/separate-charges-and-transfers).'
    )
    .optional(),
});

/** Documented 2xx response payload of CreatePaymentLink (statuses: 200); all fields optional because presence varies by status code. */
export const CreatePaymentLinkPayloadSchema = z.object({
  active: z
    .boolean()
    .describe(
      "Whether the payment link's `url` is active. If `false`, customers visiting the URL will be shown a page saying that the link has been deactivated."
    )
    .optional(),
  after_completion: z
    .object({
      hosted_confirmation: z
        .record(z.string(), z.unknown())
        .describe(
          'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
        )
        .optional(),
      redirect: z
        .record(z.string(), z.unknown())
        .describe(
          'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
        )
        .optional(),
      type: z
        .enum(['hosted_confirmation', 'redirect'])
        .describe('The specified behavior after the purchase is complete.'),
    })
    .optional(),
  allow_promotion_codes: z
    .boolean()
    .describe('Whether user redeemable promotion codes are enabled.')
    .optional(),
  application: z
    .union([
      z.string().max(5000),
      z
        .record(z.string(), z.unknown())
        .describe(
          'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
        ),
      z
        .record(z.string(), z.unknown())
        .describe(
          'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
        ),
    ])
    .describe(
      'The ID of the Connect application that created the Payment Link.'
    )
    .optional(),
  application_fee_amount: z
    .number()
    .int()
    .nullable()
    .describe(
      "The amount of the application fee (if any) that will be requested to be applied to the payment and transferred to the application owner's Stripe account."
    )
    .optional(),
  application_fee_percent: z
    .number()
    .nullable()
    .describe(
      "This represents the percentage of the subscription invoice total that will be transferred to the application owner's Stripe account."
    )
    .optional(),
  automatic_tax: z
    .object({
      enabled: z
        .boolean()
        .describe(
          "If `true`, tax will be calculated automatically using the customer's location."
        ),
      liability: z
        .record(z.string(), z.unknown())
        .describe(
          'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
        )
        .optional(),
    })
    .optional(),
  billing_address_collection: z
    .enum(['auto', 'required'])
    .describe(
      "Configuration for collecting the customer's billing address. Defaults to `auto`."
    )
    .optional(),
  consent_collection: z
    .record(z.string(), z.unknown())
    .describe(
      'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
    )
    .optional(),
  currency: z
    .string()
    .describe(
      'Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https://stripe.com/docs/currencies).'
    )
    .optional(),
  custom_fields: z
    .array(
      z.object({
        dropdown: z
          .record(z.string(), z.unknown())
          .describe(
            'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
          )
          .optional(),
        key: z
          .string()
          .max(5000)
          .describe(
            'String of your choice that your integration can use to reconcile this field. Must be unique to this field, alphanumeric, and up to 200 characters.'
          ),
        label: z
          .record(z.string(), z.unknown())
          .describe(
            'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
          ),
        numeric: z
          .record(z.string(), z.unknown())
          .describe(
            'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
          )
          .optional(),
        optional: z
          .boolean()
          .describe(
            'Whether the customer is required to complete the field before completing the Checkout Session. Defaults to `false`.'
          ),
        text: z
          .record(z.string(), z.unknown())
          .describe(
            'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
          )
          .optional(),
        type: z
          .enum(['dropdown', 'numeric', 'text'])
          .describe('The type of the field.'),
      })
    )
    .describe(
      "Collect additional information from your customer using custom fields. Up to 3 fields are supported. You can't set this parameter if `ui_mode` is `custom`."
    )
    .optional(),
  custom_text: z
    .object({
      after_submit: z
        .record(z.string(), z.unknown())
        .describe(
          'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
        )
        .optional(),
      shipping_address: z
        .record(z.string(), z.unknown())
        .describe(
          'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
        )
        .optional(),
      submit: z
        .record(z.string(), z.unknown())
        .describe(
          'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
        )
        .optional(),
      terms_of_service_acceptance: z
        .record(z.string(), z.unknown())
        .describe(
          'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
        )
        .optional(),
    })
    .optional(),
  customer_creation: z
    .enum(['always', 'if_required'])
    .describe('Configuration for Customer creation during checkout.')
    .optional(),
  id: z
    .string()
    .max(5000)
    .describe('Unique identifier for the object.')
    .optional(),
  inactive_message: z
    .string()
    .max(5000)
    .nullable()
    .describe(
      'The custom message to be displayed to a customer when a payment link is no longer active.'
    )
    .optional(),
  invoice_creation: z
    .record(z.string(), z.unknown())
    .describe(
      'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
    )
    .optional(),
  line_items: z
    .object({
      data: z
        .array(
          z
            .record(z.string(), z.unknown())
            .describe(
              'A line item. (nested object collapsed at trim depth limit)'
            )
        )
        .describe('Details about each object.'),
      has_more: z
        .boolean()
        .describe(
          'True if this list has another page of items after this one that can be fetched.'
        ),
      object: z
        .enum(['list'])
        .describe(
          "String representing the object's type. Objects of the same type share the same value. Always has the value `list`."
        ),
      url: z
        .string()
        .max(5000)
        .describe('The URL where this list can be accessed.'),
    })
    .describe('The line items representing what is being sold.')
    .optional(),
  livemode: z
    .boolean()
    .describe(
      'If the object exists in live mode, the value is `true`. If the object exists in test mode, the value is `false`.'
    )
    .optional(),
  managed_payments: z
    .record(z.string(), z.unknown())
    .describe(
      'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
    )
    .optional(),
  metadata: z
    .record(z.string(), z.string().max(500))
    .describe(
      'Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.'
    )
    .optional(),
  name_collection: z
    .object({
      business: z
        .record(z.string(), z.unknown())
        .describe(
          'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
        )
        .optional(),
      individual: z
        .record(z.string(), z.unknown())
        .describe(
          'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
        )
        .optional(),
    })
    .optional(),
  object: z
    .enum(['payment_link'])
    .describe(
      "String representing the object's type. Objects of the same type share the same value."
    )
    .optional(),
  on_behalf_of: z
    .union([
      z.string().max(5000),
      z
        .record(z.string(), z.unknown())
        .describe(
          'For new integrations, we recommend using the [Accounts v2 API](/api/v2/core/accounts), in place of /v1/accounts and /v1/customers to represent a user. This is an object representing a Stripe account.… (nested object collapsed at trim depth limit)'
        ),
    ])
    .describe(
      'The account on behalf of which to charge. See the [Connect documentation](https://support.stripe.com/questions/sending-invoices-on-behalf-of-connected-accounts) for details.'
    )
    .optional(),
  optional_items: z
    .array(
      z.object({
        adjustable_quantity: z
          .record(z.string(), z.unknown())
          .describe(
            'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
          )
          .optional(),
        price: z.string().max(5000),
        quantity: z.number().int(),
      })
    )
    .nullable()
    .describe('The optional items presented to the customer at checkout.')
    .optional(),
  payment_intent_data: z
    .record(z.string(), z.unknown())
    .describe(
      'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
    )
    .optional(),
  payment_method_collection: z
    .enum(['always', 'if_required'])
    .describe(
      'Configuration for collecting a payment method during checkout. Defaults to `always`.'
    )
    .optional(),
  payment_method_options: z
    .record(z.string(), z.unknown())
    .describe(
      'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
    )
    .optional(),
  payment_method_types: z
    .array(
      z.enum([
        'affirm',
        'afterpay_clearpay',
        'alipay',
        'alma',
        'au_becs_debit',
        'bacs_debit',
        'bancontact',
        'billie',
        'bizum',
        'blik',
        'boleto',
        'card',
        'cashapp',
        'eps',
        'fpx',
        'giropay',
        'grabpay',
        'ideal',
        'klarna',
        'konbini',
        'link',
        'mb_way',
        'mobilepay',
        'multibanco',
        'oxxo',
        'p24',
        'pay_by_bank',
        'paynow',
        'paypal',
        'payto',
        'pix',
        'promptpay',
        'satispay',
        'sepa_debit',
        'sofort',
        'sunbit',
        'swish',
        'twint',
        'upi',
        'us_bank_account',
        'wechat_pay',
        'zip',
      ])
    )
    .nullable()
    .describe(
      "The list of payment method types that customers can use. When `null`, Stripe will dynamically show relevant payment methods you've enabled in your [payment method settings](https://dashboard.stripe.c…"
    )
    .optional(),
  phone_number_collection: z
    .object({
      enabled: z
        .boolean()
        .describe(
          'If `true`, a phone number will be collected during checkout.'
        ),
    })
    .optional(),
  restrictions: z
    .record(z.string(), z.unknown())
    .describe(
      'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
    )
    .optional(),
  shipping_address_collection: z
    .record(z.string(), z.unknown())
    .describe(
      'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
    )
    .optional(),
  shipping_options: z
    .array(
      z.object({
        shipping_amount: z
          .number()
          .int()
          .describe(
            'A non-negative integer in cents representing how much to charge.'
          ),
        shipping_rate: z
          .union([
            z.string().max(5000),
            z
              .record(z.string(), z.unknown())
              .describe(
                'Shipping rates describe the price of shipping presented to your customers and applied to a purchase. For more information, see [Charge for shipping](https://docs.stripe.com/payments/during-payment/ch… (nested object collapsed at trim depth limit)'
              ),
          ])
          .describe(
            'The ID of the Shipping Rate to use for this shipping option.'
          ),
      })
    )
    .describe('The shipping rate options applied to the session.')
    .optional(),
  submit_type: z
    .enum(['auto', 'book', 'donate', 'pay', 'subscribe'])
    .describe(
      'Indicates the type of transaction being performed which customizes relevant text on the page, such as the submit button.'
    )
    .optional(),
  subscription_data: z
    .record(z.string(), z.unknown())
    .describe(
      'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
    )
    .optional(),
  tax_id_collection: z
    .object({
      enabled: z
        .boolean()
        .describe(
          'Indicates whether tax ID collection is enabled for the session.'
        ),
      required: z.enum(['if_supported', 'never']),
    })
    .optional(),
  transfer_data: z
    .record(z.string(), z.unknown())
    .describe(
      'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
    )
    .optional(),
  url: z
    .string()
    .max(5000)
    .describe('The public URL that can be shared with customers.')
    .optional(),
});

/** Documented 2xx response payload of CreatePayout (statuses: 200); all fields optional because presence varies by status code. */
export const CreatePayoutPayloadSchema = z.object({
  amount: z
    .number()
    .int()
    .describe(
      'The amount (in cents (or local equivalent)) that transfers to your bank account or debit card.'
    )
    .optional(),
  application_fee: z
    .union([
      z.string().max(5000),
      z
        .record(z.string(), z.unknown())
        .describe(
          'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
        ),
    ])
    .describe(
      'The application fee (if any) for the payout. [See the Connect documentation](https://docs.stripe.com/connect/instant-payouts#monetization-and-fees) for details.'
    )
    .optional(),
  application_fee_amount: z
    .number()
    .int()
    .nullable()
    .describe(
      'The amount of the application fee (if any) requested for the payout. [See the Connect documentation](https://docs.stripe.com/connect/instant-payouts#monetization-and-fees) for details.'
    )
    .optional(),
  arrival_date: z
    .number()
    .int()
    .describe(
      'Date that you can expect the payout to arrive in the bank. This factors in delays to account for weekends or bank holidays.'
    )
    .optional(),
  automatic: z
    .boolean()
    .describe(
      "Returns `true` if the payout is created by an [automated payout schedule](https://docs.stripe.com/payouts#payout-schedule) and `false` if it's [requested manually](https://stripe.com/docs/payouts#man…"
    )
    .optional(),
  balance_transaction: z
    .union([
      z.string().max(5000),
      z
        .record(z.string(), z.unknown())
        .describe(
          'Balance transactions represent funds moving through your Stripe account. Stripe creates them for every type of transaction that enters or leaves your Stripe account balance. Related guide: [Balance t… (nested object collapsed at trim depth limit)'
        ),
    ])
    .describe(
      'ID of the balance transaction that describes the impact of this payout on your account balance.'
    )
    .optional(),
  created: z
    .number()
    .int()
    .describe(
      'Time at which the object was created. Measured in seconds since the Unix epoch.'
    )
    .optional(),
  currency: z
    .string()
    .describe(
      'Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https://stripe.com/docs/currencies).'
    )
    .optional(),
  description: z
    .string()
    .max(5000)
    .nullable()
    .describe(
      'An arbitrary string attached to the object. Often useful for displaying to users.'
    )
    .optional(),
  destination: z
    .union([
      z.string().max(5000),
      z
        .record(z.string(), z.unknown())
        .describe(
          'These bank accounts are payment methods on `Customer` objects. On the other hand [External Accounts](/api#external_accounts) are transfer destinations on `Account` objects for connected accounts. The… (nested object collapsed at trim depth limit)'
        ),
      z
        .record(z.string(), z.unknown())
        .describe(
          'You can store multiple cards on a customer in order to charge the customer later. You can also store multiple debit cards on a recipient in order to transfer to those cards later. Related guide: [Car… (nested object collapsed at trim depth limit)'
        ),
      z
        .record(z.string(), z.unknown())
        .describe(
          'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
        ),
      z
        .record(z.string(), z.unknown())
        .describe(
          'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
        ),
    ])
    .describe('ID of the bank account or card the payout is sent to.')
    .optional(),
  failure_balance_transaction: z
    .union([
      z.string().max(5000),
      z
        .record(z.string(), z.unknown())
        .describe(
          'Balance transactions represent funds moving through your Stripe account. Stripe creates them for every type of transaction that enters or leaves your Stripe account balance. Related guide: [Balance t… (nested object collapsed at trim depth limit)'
        ),
    ])
    .describe(
      'If the payout fails or cancels, this is the ID of the balance transaction that reverses the initial balance transaction and returns the funds from the failed payout back in your balance.'
    )
    .optional(),
  failure_code: z
    .string()
    .max(5000)
    .nullable()
    .describe(
      'Error code that provides a reason for a payout failure, if available. View our [list of failure codes](https://docs.stripe.com/api#payout_failures).'
    )
    .optional(),
  failure_message: z
    .string()
    .max(5000)
    .nullable()
    .describe(
      'Message that provides the reason for a payout failure, if available.'
    )
    .optional(),
  id: z
    .string()
    .max(5000)
    .describe('Unique identifier for the object.')
    .optional(),
  livemode: z
    .boolean()
    .describe(
      'If the object exists in live mode, the value is `true`. If the object exists in test mode, the value is `false`.'
    )
    .optional(),
  metadata: z
    .record(z.string(), z.string().max(500))
    .nullable()
    .describe(
      'Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.'
    )
    .optional(),
  method: z
    .string()
    .max(5000)
    .describe(
      'The method used to send this payout, which can be `standard` or `instant`. `instant` is supported for payouts to debit cards and bank accounts in certain countries. Learn more about [bank support for…'
    )
    .optional(),
  object: z
    .enum(['payout'])
    .describe(
      "String representing the object's type. Objects of the same type share the same value."
    )
    .optional(),
  original_payout: z
    .union([
      z.string().max(5000),
      z
        .record(z.string(), z.unknown())
        .describe(
          'Recursive vendor schema "payout" truncated; see the vendor API reference.'
        ),
    ])
    .describe(
      'If the payout reverses another, this is the ID of the original payout.'
    )
    .optional(),
  payout_method: z
    .string()
    .max(5000)
    .nullable()
    .describe('ID of the v2 FinancialAccount the funds are sent to.')
    .optional(),
  reconciliation_status: z
    .enum(['completed', 'in_progress', 'not_applicable'])
    .describe(
      'If `completed`, you can use the [Balance Transactions API](https://docs.stripe.com/api/balance_transactions/list#balance_transaction_list-payout) to list all balance transactions that are paid out in…'
    )
    .optional(),
  reversed_by: z
    .union([
      z.string().max(5000),
      z
        .record(z.string(), z.unknown())
        .describe(
          'Recursive vendor schema "payout" truncated; see the vendor API reference.'
        ),
    ])
    .describe(
      'If the payout reverses, this is the ID of the payout that reverses this payout.'
    )
    .optional(),
  source_type: z
    .string()
    .max(5000)
    .describe(
      'The source balance this payout came from, which can be one of the following: `card`, `fpx`, or `bank_account`.'
    )
    .optional(),
  statement_descriptor: z
    .string()
    .max(5000)
    .nullable()
    .describe(
      "Extra information about a payout that displays on the user's bank statement."
    )
    .optional(),
  status: z
    .string()
    .max(5000)
    .describe(
      "Current status of the payout: `paid`, `pending`, `in_transit`, `canceled` or `failed`. A payout is `pending` until it's submitted to the bank, when it becomes `in_transit`. The status changes to `pai…"
    )
    .optional(),
  trace_id: z
    .record(z.string(), z.unknown())
    .describe(
      'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
    )
    .optional(),
  type: z
    .enum(['bank_account', 'card'])
    .describe('Can be `bank_account` or `card`.')
    .optional(),
});

/** Documented 2xx response payload of CreateRefund (statuses: 200); all fields optional because presence varies by status code. */
export const CreateRefundPayloadSchema = z.object({
  amount: z
    .number()
    .int()
    .describe('Amount, in cents (or local equivalent).')
    .optional(),
  balance_transaction: z
    .union([
      z.string().max(5000),
      z
        .record(z.string(), z.unknown())
        .describe(
          'Balance transactions represent funds moving through your Stripe account. Stripe creates them for every type of transaction that enters or leaves your Stripe account balance. Related guide: [Balance t… (nested object collapsed at trim depth limit)'
        ),
    ])
    .describe(
      'Balance transaction that describes the impact on your account balance.'
    )
    .optional(),
  charge: z
    .union([
      z.string().max(5000),
      z
        .record(z.string(), z.unknown())
        .describe(
          'The `Charge` object represents a single attempt to move money into your Stripe account. PaymentIntent confirmation is the most common way to create Charges, but [Account Debits](https://docs.stripe.c… (nested object collapsed at trim depth limit)'
        ),
    ])
    .describe("ID of the charge that's refunded.")
    .optional(),
  created: z
    .number()
    .int()
    .describe(
      'Time at which the object was created. Measured in seconds since the Unix epoch.'
    )
    .optional(),
  currency: z
    .string()
    .describe(
      'Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https://stripe.com/docs/currencies).'
    )
    .optional(),
  description: z
    .string()
    .max(5000)
    .describe(
      'An arbitrary string attached to the object. You can use this for displaying to users (available on non-card refunds only).'
    )
    .optional(),
  destination_details: z
    .object({
      affirm: z.record(z.string(), z.unknown()).optional(),
      afterpay_clearpay: z.record(z.string(), z.unknown()).optional(),
      alipay: z.record(z.string(), z.unknown()).optional(),
      alma: z.record(z.string(), z.unknown()).optional(),
      amazon_pay: z.record(z.string(), z.unknown()).optional(),
      au_bank_transfer: z.record(z.string(), z.unknown()).optional(),
      blik: z
        .record(z.string(), z.unknown())
        .describe(
          'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
        )
        .optional(),
      br_bank_transfer: z
        .record(z.string(), z.unknown())
        .describe(
          'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
        )
        .optional(),
      card: z
        .record(z.string(), z.unknown())
        .describe(
          'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
        )
        .optional(),
      cashapp: z.record(z.string(), z.unknown()).optional(),
      crypto: z
        .record(z.string(), z.unknown())
        .describe(
          'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
        )
        .optional(),
      customer_cash_balance: z.record(z.string(), z.unknown()).optional(),
      eps: z.record(z.string(), z.unknown()).optional(),
      eu_bank_transfer: z
        .record(z.string(), z.unknown())
        .describe(
          'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
        )
        .optional(),
      gb_bank_transfer: z
        .record(z.string(), z.unknown())
        .describe(
          'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
        )
        .optional(),
      giropay: z.record(z.string(), z.unknown()).optional(),
      grabpay: z.record(z.string(), z.unknown()).optional(),
      jp_bank_transfer: z
        .record(z.string(), z.unknown())
        .describe(
          'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
        )
        .optional(),
      klarna: z.record(z.string(), z.unknown()).optional(),
      mb_way: z
        .record(z.string(), z.unknown())
        .describe(
          'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
        )
        .optional(),
      multibanco: z
        .record(z.string(), z.unknown())
        .describe(
          'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
        )
        .optional(),
      mx_bank_transfer: z
        .record(z.string(), z.unknown())
        .describe(
          'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
        )
        .optional(),
      nz_bank_transfer: z.record(z.string(), z.unknown()).optional(),
      p24: z
        .record(z.string(), z.unknown())
        .describe(
          'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
        )
        .optional(),
      paynow: z.record(z.string(), z.unknown()).optional(),
      paypal: z
        .record(z.string(), z.unknown())
        .describe(
          'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
        )
        .optional(),
      pix: z.record(z.string(), z.unknown()).optional(),
      revolut: z.record(z.string(), z.unknown()).optional(),
      scalapay: z.record(z.string(), z.unknown()).optional(),
      sofort: z.record(z.string(), z.unknown()).optional(),
      swish: z
        .record(z.string(), z.unknown())
        .describe(
          'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
        )
        .optional(),
      th_bank_transfer: z
        .record(z.string(), z.unknown())
        .describe(
          'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
        )
        .optional(),
      twint: z.record(z.string(), z.unknown()).optional(),
      type: z
        .string()
        .max(5000)
        .describe(
          'The type of transaction-specific details of the payment method used in the refund (e.g., `card`). An additional hash is included on `destination_details` with a name matching this value. It contains …'
        ),
      us_bank_transfer: z
        .record(z.string(), z.unknown())
        .describe(
          'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
        )
        .optional(),
      wechat_pay: z.record(z.string(), z.unknown()).optional(),
      zip: z.record(z.string(), z.unknown()).optional(),
    })
    .optional(),
  failure_balance_transaction: z
    .union([
      z.string().max(5000),
      z
        .record(z.string(), z.unknown())
        .describe(
          'Balance transactions represent funds moving through your Stripe account. Stripe creates them for every type of transaction that enters or leaves your Stripe account balance. Related guide: [Balance t… (nested object collapsed at trim depth limit)'
        ),
    ])
    .describe(
      'After the refund fails, this balance transaction describes the adjustment made on your account balance that reverses the initial balance transaction.'
    )
    .optional(),
  failure_reason: z
    .string()
    .max(5000)
    .describe(
      'Provides the reason for the refund failure. Possible values are: `lost_or_stolen_card`, `expired_or_canceled_card`, `charge_for_pending_refund_disputed`, `insufficient_funds`, `declined`, `merchant_r…'
    )
    .optional(),
  id: z
    .string()
    .max(5000)
    .describe('Unique identifier for the object.')
    .optional(),
  instructions_email: z
    .string()
    .max(5000)
    .describe(
      'For payment methods without native refund support (for example, Konbini, PromptPay), provide an email address for the customer to receive refund instructions.'
    )
    .optional(),
  metadata: z
    .record(z.string(), z.string().max(500))
    .nullable()
    .describe(
      'Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.'
    )
    .optional(),
  next_action: z
    .object({
      display_details: z
        .record(z.string(), z.unknown())
        .describe(
          'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
        )
        .optional(),
      type: z
        .string()
        .max(5000)
        .describe('Type of the next action to perform.'),
    })
    .optional(),
  object: z
    .enum(['refund'])
    .describe(
      "String representing the object's type. Objects of the same type share the same value."
    )
    .optional(),
  payment_intent: z
    .union([
      z.string().max(5000),
      z
        .record(z.string(), z.unknown())
        .describe(
          'A PaymentIntent guides you through the process of collecting a payment from your customer. We recommend that you create exactly one PaymentIntent for each order or customer session in your system. Yo… (nested object collapsed at trim depth limit)'
        ),
    ])
    .describe("ID of the PaymentIntent that's refunded.")
    .optional(),
  pending_reason: z
    .enum(['charge_pending', 'insufficient_funds', 'processing'])
    .describe(
      'Provides the reason for why the refund is pending. Possible values are: `processing`, `insufficient_funds`, or `charge_pending`.'
    )
    .optional(),
  presentment_details: z
    .object({
      presentment_amount: z
        .number()
        .int()
        .describe(
          'Amount intended to be collected by this payment, denominated in `presentment_currency`.'
        ),
      presentment_currency: z
        .string()
        .max(5000)
        .describe('Currency presented to the customer during payment.'),
    })
    .optional(),
  reason: z
    .enum([
      'duplicate',
      'expired_uncaptured_charge',
      'fraudulent',
      'requested_by_customer',
    ])
    .nullable()
    .describe(
      'Reason for the refund, which is either user-provided (`duplicate`, `fraudulent`, or `requested_by_customer`) or generated by Stripe internally (`expired_uncaptured_charge`).'
    )
    .optional(),
  receipt_number: z
    .string()
    .max(5000)
    .nullable()
    .describe(
      'This is the transaction number that appears on email receipts sent for this refund.'
    )
    .optional(),
  source_transfer_reversal: z
    .union([
      z.string().max(5000),
      z
        .record(z.string(), z.unknown())
        .describe(
          '[Stripe Connect](https://docs.stripe.com/connect) platforms can reverse transfers made to a connected account, either entirely or partially, and can also specify whether to refund any related applica… (nested object collapsed at trim depth limit)'
        ),
    ])
    .describe(
      "The transfer reversal that's associated with the refund. Only present if the charge came from another Stripe account."
    )
    .optional(),
  status: z
    .string()
    .max(5000)
    .nullable()
    .describe(
      'Status of the refund. This can be `pending`, `requires_action`, `succeeded`, `failed`, or `canceled`. Learn more about [failed refunds](https://docs.stripe.com/refunds#failed-refunds).'
    )
    .optional(),
  transfer_reversal: z
    .union([
      z.string().max(5000),
      z
        .record(z.string(), z.unknown())
        .describe(
          '[Stripe Connect](https://docs.stripe.com/connect) platforms can reverse transfers made to a connected account, either entirely or partially, and can also specify whether to refund any related applica… (nested object collapsed at trim depth limit)'
        ),
    ])
    .describe(
      'This refers to the transfer reversal object if the accompanying transfer reverses. This is only applicable if the charge was created using the destination parameter.'
    )
    .optional(),
});

/** Documented 2xx response payload of ListCharges (statuses: 200); all fields optional because presence varies by status code. */
export const ListChargesPayloadSchema = z.object({
  data: z
    .array(
      z
        .object({
          amount: z
            .number()
            .int()
            .describe(
              'Amount intended to be collected by this payment. A positive integer representing how much to charge in the [smallest currency unit](https://docs.stripe.com/currencies#zero-decimal) (e.g., 100 cents t…'
            ),
          amount_captured: z
            .number()
            .int()
            .describe(
              'Amount in cents (or local equivalent) captured (can be less than the amount attribute on the charge if a partial capture was made).'
            ),
          amount_refunded: z
            .number()
            .int()
            .describe(
              'Amount in cents (or local equivalent) refunded (can be less than the amount attribute on the charge if a partial refund was issued).'
            ),
          application: z
            .union([
              z.string().max(5000),
              z
                .record(z.string(), z.unknown())
                .describe(
                  'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
                ),
            ])
            .describe('ID of the Connect application that created the charge.')
            .optional(),
          application_fee: z
            .union([
              z.string().max(5000),
              z
                .record(z.string(), z.unknown())
                .describe(
                  'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
                ),
            ])
            .describe(
              'The application fee (if any) for the charge. [See the Connect documentation](https://docs.stripe.com/connect/direct-charges#collect-fees) for details.'
            )
            .optional(),
          application_fee_amount: z
            .number()
            .int()
            .nullable()
            .describe(
              'The amount of the application fee (if any) requested for the charge. [See the Connect documentation](https://docs.stripe.com/connect/direct-charges#collect-fees) for details.'
            )
            .optional(),
          balance_transaction: z
            .union([
              z.string().max(5000),
              z
                .record(z.string(), z.unknown())
                .describe(
                  'Balance transactions represent funds moving through your Stripe account. Stripe creates them for every type of transaction that enters or leaves your Stripe account balance. Related guide: [Balance t… (nested object collapsed at trim depth limit)'
                ),
            ])
            .describe(
              'ID of the balance transaction that describes the impact of this charge on your account balance (not including refunds or disputes).'
            )
            .optional(),
          billing_details: z
            .record(z.string(), z.unknown())
            .describe(
              'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
            ),
          calculated_statement_descriptor: z
            .string()
            .max(5000)
            .nullable()
            .describe(
              "The full statement descriptor that is passed to card networks, and that is displayed on your customers' credit card and bank statements. Allows you to see what the statement descriptor looks like aft…"
            )
            .optional(),
          captured: z
            .boolean()
            .describe(
              'If the charge was created without capturing, this Boolean represents whether it is still uncaptured or has since been captured.'
            ),
          created: z
            .number()
            .int()
            .describe(
              'Time at which the object was created. Measured in seconds since the Unix epoch.'
            ),
          currency: z
            .string()
            .describe(
              'Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https://stripe.com/docs/currencies).'
            ),
          customer: z
            .union([
              z.string().max(5000),
              z
                .record(z.string(), z.unknown())
                .describe(
                  'This object represents a customer of your business. Use it to [create recurring charges](https://docs.stripe.com/invoicing/customer), [save payment](https://docs.stripe.com/payments/save-during-payme… (nested object collapsed at trim depth limit)'
                ),
              z
                .record(z.string(), z.unknown())
                .describe(
                  'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
                ),
            ])
            .describe('ID of the customer this charge is for if one exists.')
            .optional(),
          description: z
            .string()
            .max(40000)
            .nullable()
            .describe(
              'An arbitrary string attached to the object. Often useful for displaying to users.'
            )
            .optional(),
          disputed: z
            .boolean()
            .describe('Whether the charge has been disputed.'),
          failure_balance_transaction: z
            .union([
              z.string().max(5000),
              z
                .record(z.string(), z.unknown())
                .describe(
                  'Balance transactions represent funds moving through your Stripe account. Stripe creates them for every type of transaction that enters or leaves your Stripe account balance. Related guide: [Balance t… (nested object collapsed at trim depth limit)'
                ),
            ])
            .describe(
              'ID of the balance transaction that describes the reversal of the balance on your account due to payment failure.'
            )
            .optional(),
          failure_code: z
            .string()
            .max(5000)
            .nullable()
            .describe(
              'Error code explaining reason for charge failure if available (see [the errors section](https://docs.stripe.com/error-codes) for a list of codes).'
            )
            .optional(),
          failure_message: z
            .string()
            .max(5000)
            .nullable()
            .describe(
              'Message to user further explaining reason for charge failure if available.'
            )
            .optional(),
          fraud_details: z
            .record(z.string(), z.unknown())
            .describe(
              'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
            )
            .optional(),
          id: z
            .string()
            .max(5000)
            .describe('Unique identifier for the object.'),
          livemode: z
            .boolean()
            .describe(
              'If the object exists in live mode, the value is `true`. If the object exists in test mode, the value is `false`.'
            ),
          metadata: z
            .record(z.string(), z.string().max(500))
            .describe(
              'Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.'
            ),
          object: z
            .enum(['charge'])
            .describe(
              "String representing the object's type. Objects of the same type share the same value."
            ),
          on_behalf_of: z
            .union([
              z.string().max(5000),
              z
                .record(z.string(), z.unknown())
                .describe(
                  'For new integrations, we recommend using the [Accounts v2 API](/api/v2/core/accounts), in place of /v1/accounts and /v1/customers to represent a user. This is an object representing a Stripe account.… (nested object collapsed at trim depth limit)'
                ),
            ])
            .describe(
              'The account (if any) the charge was made on behalf of without triggering an automatic transfer. See the [Connect documentation](https://docs.stripe.com/connect/separate-charges-and-transfers) for det…'
            )
            .optional(),
          outcome: z
            .record(z.string(), z.unknown())
            .describe(
              'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
            )
            .optional(),
          paid: z
            .boolean()
            .describe(
              '`true` if the charge succeeded, or was successfully authorized for later capture.'
            ),
          payment_intent: z
            .union([
              z.string().max(5000),
              z
                .record(z.string(), z.unknown())
                .describe(
                  'A PaymentIntent guides you through the process of collecting a payment from your customer. We recommend that you create exactly one PaymentIntent for each order or customer session in your system. Yo… (nested object collapsed at trim depth limit)'
                ),
            ])
            .describe(
              'ID of the PaymentIntent associated with this charge, if one exists.'
            )
            .optional(),
          payment_method: z
            .string()
            .max(5000)
            .nullable()
            .describe('ID of the payment method used in this charge.')
            .optional(),
          payment_method_details: z
            .record(z.string(), z.unknown())
            .describe(
              'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
            )
            .optional(),
          presentment_details: z
            .record(z.string(), z.unknown())
            .describe(
              'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
            )
            .optional(),
          radar_options: z
            .record(z.string(), z.unknown())
            .describe(
              'Options to configure Radar. See [Radar Session](https://docs.stripe.com/radar/radar-session) for more information. (nested object collapsed at trim depth limit)'
            )
            .optional(),
          receipt_email: z
            .string()
            .max(5000)
            .nullable()
            .describe(
              'This is the email address that the receipt for this charge was sent to.'
            )
            .optional(),
          receipt_number: z
            .string()
            .max(5000)
            .nullable()
            .describe(
              'This is the transaction number that appears on email receipts sent for this charge. This attribute will be `null` until a receipt has been sent.'
            )
            .optional(),
          receipt_url: z
            .string()
            .max(5000)
            .nullable()
            .describe(
              'This is the URL to view the receipt for this charge. The receipt is kept up-to-date to the latest state of the charge, including any refunds. If the charge is for an Invoice, the receipt will be styl…'
            )
            .optional(),
          refunded: z
            .boolean()
            .describe(
              'Whether the charge has been fully refunded. If the charge is only partially refunded, this attribute will still be false.'
            ),
          refunds: z
            .record(z.string(), z.unknown())
            .describe(
              'A list of refunds that have been applied to the charge. (nested object collapsed at trim depth limit)'
            )
            .optional(),
          review: z
            .union([
              z.string().max(5000),
              z
                .record(z.string(), z.unknown())
                .describe(
                  'Reviews can be used to supplement automated fraud detection with human expertise. Learn more about [Radar](/radar) and reviewing payments [here](https://docs.stripe.com/radar/reviews). (nested object collapsed at trim depth limit)'
                ),
            ])
            .describe(
              'ID of the review associated with this charge if one exists.'
            )
            .optional(),
          shipping: z
            .record(z.string(), z.unknown())
            .describe(
              'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
            )
            .optional(),
          source_transfer: z
            .union([
              z.string().max(5000),
              z
                .record(z.string(), z.unknown())
                .describe(
                  'A `Transfer` object is created when you move funds between Stripe accounts as part of Connect. Before April 6, 2017, transfers also represented movement of funds from a Stripe account to a card or ba… (nested object collapsed at trim depth limit)'
                ),
            ])
            .describe(
              'The transfer ID which created this charge. Only present if the charge came from another Stripe account. [See the Connect documentation](https://docs.stripe.com/connect/destination-charges) for detail…'
            )
            .optional(),
          statement_descriptor: z
            .string()
            .max(5000)
            .nullable()
            .describe(
              "For a non-card charge, text that appears on the customer's statement as the statement descriptor. This value overrides the account's default statement descriptor. For information about requirements, …"
            )
            .optional(),
          statement_descriptor_suffix: z
            .string()
            .max(5000)
            .nullable()
            .describe(
              "Provides information about a card charge. Concatenated to the account's [statement descriptor prefix](https://docs.stripe.com/get-started/account/statement-descriptors#static) to form the complete st…"
            )
            .optional(),
          status: z
            .enum(['failed', 'pending', 'succeeded'])
            .describe(
              'The status of the payment is either `succeeded`, `pending`, or `failed`.'
            ),
          transfer: z
            .union([
              z.string().max(5000),
              z
                .record(z.string(), z.unknown())
                .describe(
                  'A `Transfer` object is created when you move funds between Stripe accounts as part of Connect. Before April 6, 2017, transfers also represented movement of funds from a Stripe account to a card or ba… (nested object collapsed at trim depth limit)'
                ),
            ])
            .describe(
              'ID of the transfer to the `destination` account (only applicable if the charge was created using the `destination` parameter).'
            )
            .optional(),
          transfer_data: z
            .record(z.string(), z.unknown())
            .describe(
              'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
            )
            .optional(),
          transfer_group: z
            .string()
            .max(5000)
            .nullable()
            .describe(
              'A string that identifies this transaction as part of a group. See the [Connect documentation](https://docs.stripe.com/connect/separate-charges-and-transfers#transfer-options) for details.'
            )
            .optional(),
        })
        .describe(
          'The `Charge` object represents a single attempt to move money into your Stripe account. PaymentIntent confirmation is the most common way to create Charges, but [Account Debits](https://docs.stripe.c…'
        )
    )
    .optional(),
  has_more: z
    .boolean()
    .describe(
      'True if this list has another page of items after this one that can be fetched.'
    )
    .optional(),
  object: z
    .enum(['list'])
    .describe(
      "String representing the object's type. Objects of the same type share the same value. Always has the value `list`."
    )
    .optional(),
  url: z
    .string()
    .max(5000)
    .describe('The URL where this list can be accessed.')
    .optional(),
});

/** Documented 2xx response payload of GetBalance (statuses: 200); all fields optional because presence varies by status code. */
export const GetBalancePayloadSchema = z.object({
  available: z
    .array(
      z.object({
        amount: z.number().int().describe('Balance amount.'),
        currency: z
          .string()
          .describe(
            'Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https://stripe.com/docs/currencies).'
          ),
        source_types: z
          .record(z.string(), z.unknown())
          .describe(
            'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
          )
          .optional(),
      })
    )
    .describe(
      'Available funds that you can transfer or pay out automatically by Stripe or explicitly through the [Transfers API](https://api.stripe.com#transfers) or [Payouts API](https://api.stripe.com#payouts). …'
    )
    .optional(),
  connect_reserved: z
    .array(
      z.object({
        amount: z.number().int().describe('Balance amount.'),
        currency: z
          .string()
          .describe(
            'Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https://stripe.com/docs/currencies).'
          ),
        source_types: z
          .record(z.string(), z.unknown())
          .describe(
            'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
          )
          .optional(),
      })
    )
    .describe(
      'Funds held due to negative balances on connected accounts where [account.controller.requirement_collection](/api/accounts/object#account_object-controller-requirement_collection) is `application`, wh…'
    )
    .optional(),
  instant_available: z
    .array(
      z.object({
        amount: z.number().int().describe('Balance amount.'),
        currency: z
          .string()
          .describe(
            'Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https://stripe.com/docs/currencies).'
          ),
        net_available: z
          .array(
            z
              .record(z.string(), z.unknown())
              .describe(
                'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
              )
          )
          .describe('Breakdown of balance by destination.')
          .optional(),
        source_types: z
          .record(z.string(), z.unknown())
          .describe(
            'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
          )
          .optional(),
      })
    )
    .describe('Funds that you can pay out using Instant Payouts.')
    .optional(),
  issuing: z
    .object({
      available: z
        .array(
          z
            .record(z.string(), z.unknown())
            .describe(
              'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
            )
        )
        .describe('Funds that are available for use.'),
    })
    .optional(),
  livemode: z
    .boolean()
    .describe(
      'If the object exists in live mode, the value is `true`. If the object exists in test mode, the value is `false`.'
    )
    .optional(),
  object: z
    .enum(['balance'])
    .describe(
      "String representing the object's type. Objects of the same type share the same value."
    )
    .optional(),
  pending: z
    .array(
      z.object({
        amount: z.number().int().describe('Balance amount.'),
        currency: z
          .string()
          .describe(
            'Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https://stripe.com/docs/currencies).'
          ),
        source_types: z
          .record(z.string(), z.unknown())
          .describe(
            'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
          )
          .optional(),
      })
    )
    .describe(
      "Funds that aren't available in the balance yet. You can find the pending balance for each currency and each payment type in the `source_types` property."
    )
    .optional(),
  refund_and_dispute_prefunding: z
    .object({
      available: z
        .array(
          z
            .record(z.string(), z.unknown())
            .describe(
              'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
            )
        )
        .describe('Funds that are available for use.'),
      pending: z
        .array(
          z
            .record(z.string(), z.unknown())
            .describe(
              'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
            )
        )
        .describe('Funds that are pending'),
    })
    .optional(),
});

export const StripePaymentsApiParamsSchema = z.discriminatedUnion('operation', [
  z.object({
    operation: z
      .literal('create_payment_intent')
      .describe('Create a PaymentIntent'),
    baseUrl: z
      .string()
      .url()
      .describe('Stripe API base URL (e.g. https://api.stripe.com)'),
    amount: z
      .number()
      .int()
      .describe(
        'Amount intended to be collected by this PaymentIntent. A positive integer representing how much to charge in the [smallest currency unit](https://docs.stripe.com/currencies#zero-decimal) (e.g., 100 c…'
      ),
    currency: z
      .string()
      .describe(
        'Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https://stripe.com/docs/currencies).'
      ),
    automatic_payment_methods: z
      .object({
        allow_redirects: z.enum(['always', 'never']).optional(),
        enabled: z.boolean(),
      })
      .describe(
        "When you enable this parameter, this PaymentIntent accepts payment methods that you enable in the Dashboard and that are compatible with this PaymentIntent's other parameters."
      )
      .optional(),
    confirm: z
      .boolean()
      .describe(
        'Set to `true` to attempt to [confirm this PaymentIntent](https://docs.stripe.com/api/payment_intents/confirm) immediately. This parameter defaults to `false`. When creating and confirming a PaymentIn…'
      )
      .optional(),
    customer: z
      .string()
      .max(5000)
      .describe(
        'ID of the Customer this PaymentIntent belongs to, if one exists. Payment methods attached to other Customers cannot be used with this PaymentIntent. If [setup_future_usage](https://api.stripe.com#pay…'
      )
      .optional(),
    description: z
      .string()
      .max(1000)
      .describe(
        'An arbitrary string attached to the object. Often useful for displaying to users.'
      )
      .optional(),
    metadata: z
      .record(z.string(), z.string())
      .describe(
        'Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individ…'
      )
      .optional(),
    payment_method: z
      .string()
      .max(5000)
      .describe(
        'ID of the payment method (a PaymentMethod, Card, or [compatible Source](https://docs.stripe.com/payments/payment-methods/transitioning#compatibility) object) to attach to this PaymentIntent. If you o…'
      )
      .optional(),
    receipt_email: z
      .string()
      .describe(
        'Email address to send the receipt to. If you specify `receipt_email` for a payment in live mode, you send a receipt regardless of your [email settings](https://dashboard.stripe.com/account/emails).'
      )
      .optional(),
    statement_descriptor: z
      .string()
      .max(22)
      .describe(
        "Text that appears on the customer's statement as the statement descriptor for a non-card charge. This value overrides the account's default statement descriptor. For information about requirements, i…"
      )
      .optional(),
    credentials: BaseCredentialsSchema,
  }),
  z.object({
    operation: z
      .literal('create_payment_link')
      .describe('Create a payment link'),
    baseUrl: z
      .string()
      .url()
      .describe('Stripe API base URL (e.g. https://api.stripe.com)'),
    line_items: z
      .array(
        z.object({
          adjustable_quantity: z
            .record(z.string(), z.unknown())
            .describe(
              'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
            )
            .optional(),
          price: z.string().max(5000).optional(),
          price_data: z
            .record(z.string(), z.unknown())
            .describe(
              'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
            )
            .optional(),
          quantity: z.number().int(),
        })
      )
      .describe(
        'The line items representing what is being sold. Each line item represents an item being sold. Up to 20 line items are supported.'
      ),
    currency: z
      .string()
      .describe(
        "Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https://stripe.com/docs/currencies) and supported by each line item's …"
      )
      .optional(),
    allow_promotion_codes: z
      .boolean()
      .describe('Enables user redeemable promotion codes.')
      .optional(),
    after_completion: z
      .object({
        hosted_confirmation: z
          .record(z.string(), z.unknown())
          .describe(
            'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
          )
          .optional(),
        redirect: z
          .record(z.string(), z.unknown())
          .describe(
            'Vendor object (nested object collapsed at trim depth limit); see the vendor API reference for its fields.'
          )
          .optional(),
        type: z.enum(['hosted_confirmation', 'redirect']),
      })
      .describe('Behavior after the purchase is complete.')
      .optional(),
    metadata: z
      .record(z.string(), z.string())
      .describe(
        'Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individ…'
      )
      .optional(),
    credentials: BaseCredentialsSchema,
  }),
  z.object({
    operation: z.literal('create_payout').describe('Create a payout'),
    baseUrl: z
      .string()
      .url()
      .describe('Stripe API base URL (e.g. https://api.stripe.com)'),
    amount: z
      .number()
      .int()
      .describe('A positive integer in cents representing how much to payout.'),
    currency: z
      .string()
      .describe(
        'Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https://stripe.com/docs/currencies).'
      ),
    description: z
      .string()
      .max(5000)
      .describe(
        'An arbitrary string attached to the object. Often useful for displaying to users.'
      )
      .optional(),
    destination: z
      .string()
      .describe(
        "The ID of a bank account or a card to send the payout to. If you don't provide a destination, we use the default external account for the specified currency."
      )
      .optional(),
    metadata: z
      .record(z.string(), z.string())
      .describe(
        'Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individ…'
      )
      .optional(),
    method: z
      .enum(['instant', 'standard'])
      .describe(
        'The method used to send this payout, which is `standard` or `instant`. We support `instant` for payouts to debit cards and bank accounts in certain countries. Learn more about [bank support for Insta…'
      )
      .optional(),
    source_type: z
      .enum(['bank_account', 'card', 'fpx'])
      .describe(
        'The balance type of your Stripe balance to draw this payout from. Balances for different payment sources are kept separately. You can find the amounts with the Balances API. One of `bank_account`, `c…'
      )
      .optional(),
    statement_descriptor: z
      .string()
      .max(22)
      .describe(
        "A string that displays on the recipient's bank or card statement (up to 22 characters). A `statement_descriptor` that's longer than 22 characters return an error. Most banks truncate this information…"
      )
      .optional(),
    credentials: BaseCredentialsSchema,
  }),
  z.object({
    operation: z
      .literal('create_refund')
      .describe('Create customer balance refund'),
    baseUrl: z
      .string()
      .url()
      .describe('Stripe API base URL (e.g. https://api.stripe.com)'),
    amount: z.number().int().optional(),
    charge: z
      .string()
      .max(5000)
      .describe('The identifier of the charge to refund.')
      .optional(),
    payment_intent: z
      .string()
      .max(5000)
      .describe('The identifier of the PaymentIntent to refund.')
      .optional(),
    currency: z
      .string()
      .describe(
        'Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https://stripe.com/docs/currencies).'
      )
      .optional(),
    customer: z
      .string()
      .max(5000)
      .describe('Customer whose customer balance to refund from.')
      .optional(),
    metadata: z
      .union([z.record(z.string(), z.string()), z.enum([''])])
      .describe(
        'Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individ…'
      )
      .optional(),
    reason: z
      .enum(['duplicate', 'fraudulent', 'requested_by_customer'])
      .describe(
        'String indicating the reason for the refund. If set, possible values are `duplicate`, `fraudulent`, and `requested_by_customer`. If you believe the charge to be fraudulent, specifying `fraudulent` as…'
      )
      .optional(),
    instructions_email: z
      .string()
      .describe(
        'For payment methods without native refund support (e.g., Konbini, PromptPay), use this email from the customer to receive refund instructions.'
      )
      .optional(),
    credentials: BaseCredentialsSchema,
  }),
  z.object({
    operation: z.literal('list_charges').describe('List all charges'),
    baseUrl: z
      .string()
      .url()
      .describe('Stripe API base URL (e.g. https://api.stripe.com)'),
    customer: z
      .string()
      .max(5000)
      .describe(
        'Only return charges for the customer specified by this customer ID.'
      )
      .optional(),
    ending_before: z
      .string()
      .describe(
        'A cursor for use in pagination. `ending_before` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, starting with `obj_bar`, your su…'
      )
      .optional(),
    limit: z
      .number()
      .int()
      .describe(
        'A limit on the number of objects to be returned. Limit can range between 1 and 100, and the default is 10.'
      )
      .optional(),
    payment_intent: z
      .string()
      .max(5000)
      .describe(
        'Only return charges that were created by the PaymentIntent specified by this PaymentIntent ID.'
      )
      .optional(),
    starting_after: z
      .string()
      .describe(
        'A cursor for use in pagination. `starting_after` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with `obj_foo`, your sub…'
      )
      .optional(),
    transfer_group: z
      .string()
      .max(5000)
      .describe('Only return charges for this transfer group, limited to 100.')
      .optional(),
    credentials: BaseCredentialsSchema,
  }),
  z.object({
    operation: z.literal('get_balance').describe('Retrieve balance'),
    baseUrl: z
      .string()
      .url()
      .describe('Stripe API base URL (e.g. https://api.stripe.com)'),
    credentials: BaseCredentialsSchema,
  }),
]);

export const StripePaymentsApiResultSchema = z.discriminatedUnion('operation', [
  z
    .object({
      operation: z.literal('create_payment_intent'),
      success: z.boolean().describe('Whether the operation succeeded'),
      error: z.string().describe('Error message if operation failed'),
    })
    .merge(CreatePaymentIntentPayloadSchema),
  z
    .object({
      operation: z.literal('create_payment_link'),
      success: z.boolean().describe('Whether the operation succeeded'),
      error: z.string().describe('Error message if operation failed'),
    })
    .merge(CreatePaymentLinkPayloadSchema),
  z
    .object({
      operation: z.literal('create_payout'),
      success: z.boolean().describe('Whether the operation succeeded'),
      error: z.string().describe('Error message if operation failed'),
    })
    .merge(CreatePayoutPayloadSchema),
  z
    .object({
      operation: z.literal('create_refund'),
      success: z.boolean().describe('Whether the operation succeeded'),
      error: z.string().describe('Error message if operation failed'),
    })
    .merge(CreateRefundPayloadSchema),
  z
    .object({
      operation: z.literal('list_charges'),
      success: z.boolean().describe('Whether the operation succeeded'),
      error: z.string().describe('Error message if operation failed'),
    })
    .merge(ListChargesPayloadSchema),
  z
    .object({
      operation: z.literal('get_balance'),
      success: z.boolean().describe('Whether the operation succeeded'),
      error: z.string().describe('Error message if operation failed'),
    })
    .merge(GetBalancePayloadSchema),
]);

export type StripePaymentsApiParamsInput = z.input<
  typeof StripePaymentsApiParamsSchema
>;
export type StripePaymentsApiParams = z.output<
  typeof StripePaymentsApiParamsSchema
>;
export type StripePaymentsApiResult = z.output<
  typeof StripePaymentsApiResultSchema
>;

export type StripePaymentsApiCreatePaymentIntentParams = Extract<
  StripePaymentsApiParamsInput,
  { operation: 'create_payment_intent' }
>;
export type StripePaymentsApiCreatePaymentLinkParams = Extract<
  StripePaymentsApiParamsInput,
  { operation: 'create_payment_link' }
>;
export type StripePaymentsApiCreatePayoutParams = Extract<
  StripePaymentsApiParamsInput,
  { operation: 'create_payout' }
>;
export type StripePaymentsApiCreateRefundParams = Extract<
  StripePaymentsApiParamsInput,
  { operation: 'create_refund' }
>;
export type StripePaymentsApiListChargesParams = Extract<
  StripePaymentsApiParamsInput,
  { operation: 'list_charges' }
>;
export type StripePaymentsApiGetBalanceParams = Extract<
  StripePaymentsApiParamsInput,
  { operation: 'get_balance' }
>;

export type StripePaymentsApiOperationResult<
  T extends StripePaymentsApiParams['operation'],
> = Extract<StripePaymentsApiResult, { operation: T }>;
