/**
 * Doc-grounded per-operation side-effect metadata (IR-8) for the 'stripe-payments-api' bubble.
 *
 * GENERATED by @bubblelab/bubble-appgen from stripe-payments.yaml — do not hand-edit;
 * re-run `pnpm --filter @bubblelab/bubble-appgen generate:stripe-payments-api` instead.
 * Vendor docs: https://docs.stripe.com/api
 */

import type { BubbleOperationMetadata } from '@bubblelab/shared-schemas';

export const STRIPE_PAYMENTS_API_OPERATION_METADATA: BubbleOperationMetadata = {
  create_payment_intent: {
    sideEffect: 'write',
    destructive: false,
    idempotent: false,
    confidence: 0.85,
    source: 'openapi',
    citation:
      'stripe-payments.yaml#/paths/~1v1~1payment_intents/post — "Create a PaymentIntent"',
  },
  create_payment_link: {
    sideEffect: 'write',
    destructive: false,
    idempotent: false,
    confidence: 0.85,
    source: 'openapi',
    citation:
      'stripe-payments.yaml#/paths/~1v1~1payment_links/post — "Create a payment link"',
  },
  create_payout: {
    sideEffect: 'write',
    destructive: false,
    idempotent: false,
    confidence: 0.85,
    source: 'openapi',
    citation:
      'stripe-payments.yaml#/paths/~1v1~1payouts/post — "Create a payout"',
  },
  create_refund: {
    sideEffect: 'write',
    destructive: false,
    idempotent: false,
    confidence: 0.85,
    source: 'openapi',
    citation:
      'stripe-payments.yaml#/paths/~1v1~1refunds/post — "Create customer balance refund"',
  },
  list_charges: {
    sideEffect: 'read',
    destructive: false,
    idempotent: true,
    confidence: 0.85,
    source: 'openapi',
    citation:
      'stripe-payments.yaml#/paths/~1v1~1charges/get — "List all charges"',
  },
  get_balance: {
    sideEffect: 'read',
    destructive: false,
    idempotent: true,
    confidence: 0.85,
    source: 'openapi',
    citation:
      'stripe-payments.yaml#/paths/~1v1~1balance/get — "Retrieve balance"',
  },
};
