/**
 * Schema round-trip tests (fixtures = the examples shipped inside the vendor spec) for the 'stripe-payments-api' bubble.
 *
 * GENERATED by @bubblelab/bubble-appgen from stripe-payments.yaml — do not hand-edit;
 * re-run `pnpm --filter @bubblelab/bubble-appgen generate:stripe-payments-api` instead.
 * Vendor docs: https://docs.stripe.com/api
 */

import { describe, expect, it } from 'vitest';
import {
  StripePaymentsApiParamsSchema,
  StripePaymentsApiResultSchema,
} from './stripe-payments-api.schema.js';
import { STRIPE_PAYMENTS_API_OPERATION_METADATA } from './stripe-payments-api.metadata.js';

describe('stripe-payments-api generated contract', () => {
  it('create_payment_intent: accepts a spec-example request', () => {
    const result = StripePaymentsApiParamsSchema.safeParse({
      operation: 'create_payment_intent',
      baseUrl: 'https://api.stripe.com',
      amount: 0,
      currency: 'example',
    });
    expect(result.success).toBe(true);
  });

  it('create_payment_intent: rejects a type-corrupted request (currency: number)', () => {
    const result = StripePaymentsApiParamsSchema.safeParse({
      operation: 'create_payment_intent',
      baseUrl: 'https://api.stripe.com',
      amount: 0,
      currency: 12345,
    });
    expect(result.success).toBe(false);
  });

  it('create_payment_link: accepts a spec-example request', () => {
    const result = StripePaymentsApiParamsSchema.safeParse({
      operation: 'create_payment_link',
      baseUrl: 'https://api.stripe.com',
      line_items: [],
    });
    expect(result.success).toBe(true);
  });

  it('create_payment_link: rejects a type-corrupted request (currency: number)', () => {
    const result = StripePaymentsApiParamsSchema.safeParse({
      operation: 'create_payment_link',
      baseUrl: 'https://api.stripe.com',
      line_items: [],
      currency: 12345,
    });
    expect(result.success).toBe(false);
  });

  it('create_payout: accepts a spec-example request', () => {
    const result = StripePaymentsApiParamsSchema.safeParse({
      operation: 'create_payout',
      baseUrl: 'https://api.stripe.com',
      amount: 0,
      currency: 'example',
    });
    expect(result.success).toBe(true);
  });

  it('create_payout: rejects a type-corrupted request (currency: number)', () => {
    const result = StripePaymentsApiParamsSchema.safeParse({
      operation: 'create_payout',
      baseUrl: 'https://api.stripe.com',
      amount: 0,
      currency: 12345,
    });
    expect(result.success).toBe(false);
  });

  it('create_refund: accepts a spec-example request', () => {
    const result = StripePaymentsApiParamsSchema.safeParse({
      operation: 'create_refund',
      baseUrl: 'https://api.stripe.com',
    });
    expect(result.success).toBe(true);
  });

  it('create_refund: rejects a type-corrupted request (charge: number)', () => {
    const result = StripePaymentsApiParamsSchema.safeParse({
      operation: 'create_refund',
      baseUrl: 'https://api.stripe.com',
      charge: 12345,
    });
    expect(result.success).toBe(false);
  });

  it('list_charges: accepts a spec-example request', () => {
    const result = StripePaymentsApiParamsSchema.safeParse({
      operation: 'list_charges',
      baseUrl: 'https://api.stripe.com',
    });
    expect(result.success).toBe(true);
  });

  it('list_charges: rejects a type-corrupted request (customer: number)', () => {
    const result = StripePaymentsApiParamsSchema.safeParse({
      operation: 'list_charges',
      baseUrl: 'https://api.stripe.com',
      customer: 12345,
    });
    expect(result.success).toBe(false);
  });

  it('get_balance: accepts a spec-example request', () => {
    const result = StripePaymentsApiParamsSchema.safeParse({
      operation: 'get_balance',
      baseUrl: 'https://api.stripe.com',
    });
    expect(result.success).toBe(true);
  });

  it('rejects requests missing the required baseUrl', () => {
    const result = StripePaymentsApiParamsSchema.safeParse({
      operation: 'create_payment_intent',
      amount: 0,
      currency: 'example',
    });
    expect(result.success).toBe(false);
  });

  it('rejects unknown operations', () => {
    const result = StripePaymentsApiParamsSchema.safeParse({
      operation: 'not_a_real_operation',
    });
    expect(result.success).toBe(false);
  });

  it('every schema operation has cited side-effect metadata (coverage guard)', () => {
    const operations = StripePaymentsApiParamsSchema.options.map(
      (option) => option.shape.operation.value
    );
    for (const operation of operations) {
      const entry = STRIPE_PAYMENTS_API_OPERATION_METADATA[operation];
      expect(entry, `missing metadata for ${operation}`).toBeDefined();
      expect(entry.citation.length).toBeGreaterThan(0);
      expect(entry.source.length).toBeGreaterThan(0);
    }
  });
});
