/**
 * Doc-grounded per-operation side-effect metadata for the 'github' bubble (IR-8).
 *
 * GENERATED by scripts/backfill-operation-metadata.ts — regenerate with:
 *   pnpm --filter @bubblelab/bubble-core backfill:operation-metadata
 * Review the citations when the vendor API or the bubble's operations change; do not edit the
 * classifications without updating the citation that grounds them.
 *
 * Binding rule: 'write' iff the docs say the operation CREATES A NEW RECORD (even as a side
 * effect); 'read_with_side_effects' when the docs indicate mutation without record creation
 * (update/delete/mark — 'destructive' carries the delete signal); 'read' when the docs indicate
 * no mutation. The HTTP method is never the signal.
 */
import type { BubbleOperationMetadata } from '@bubblelab/shared-schemas';

export const GITHUB_OPERATION_METADATA: BubbleOperationMetadata = {
  get_file: {
    sideEffect: 'read',
    destructive: false,
    idempotent: true,
    confidence: 0.6,
    source: 'prose',
    citation:
      'https://docs.github.com/en/rest/repos/contents#get-repository-content — "Gets the contents of a file or directory in a repository."',
  },
  get_directory: {
    sideEffect: 'read',
    destructive: false,
    idempotent: true,
    confidence: 0.6,
    source: 'prose',
    citation:
      'https://docs.github.com/en/rest/repos/contents#get-repository-content — "Gets the contents of a file or directory in a repository."',
  },
  list_pull_requests: {
    sideEffect: 'read',
    destructive: false,
    idempotent: true,
    confidence: 0.6,
    source: 'prose',
    citation:
      'https://docs.github.com/en/rest/pulls/pulls#list-pull-requests — "List pull requests. Lists pull requests in a specified repository."',
  },
  get_pull_request: {
    sideEffect: 'read',
    destructive: false,
    idempotent: true,
    confidence: 0.6,
    source: 'prose',
    citation:
      'https://docs.github.com/en/rest/pulls/pulls#get-a-pull-request — "Get a pull request. Lists details of a pull request by providing its number."',
  },
  create_pr_comment: {
    sideEffect: 'write',
    destructive: false,
    idempotent: false,
    confidence: 0.6,
    source: 'prose',
    citation:
      'https://docs.github.com/en/rest/issues/comments#create-an-issue-comment — "Create an issue comment. You can use the REST API to create comments on issues and pull requests."',
  },
  list_repositories: {
    sideEffect: 'read',
    destructive: false,
    idempotent: true,
    confidence: 0.6,
    source: 'prose',
    citation:
      'https://docs.github.com/en/rest/repos/repos#list-repositories-for-the-authenticated-user — "List repositories for the authenticated user. Lists repositories that the authenticated user has explicit permission to access."',
  },
  get_repository: {
    sideEffect: 'read',
    destructive: false,
    idempotent: true,
    confidence: 0.6,
    source: 'prose',
    citation:
      'https://docs.github.com/en/rest/repos/repos#get-a-repository — "Get a repository."',
  },
  create_issue_comment: {
    sideEffect: 'write',
    destructive: false,
    idempotent: false,
    confidence: 0.6,
    source: 'prose',
    citation:
      'https://docs.github.com/en/rest/issues/comments#create-an-issue-comment — "Create an issue comment. You can use the REST API to create comments on issues and pull requests."',
  },
  create_issue: {
    sideEffect: 'write',
    destructive: false,
    idempotent: false,
    confidence: 0.6,
    source: 'prose',
    citation:
      'https://docs.github.com/en/rest/issues/issues#create-an-issue — "Create an issue. Any user with pull access to a repository can create an issue."',
  },
  list_issues: {
    sideEffect: 'read',
    destructive: false,
    idempotent: true,
    confidence: 0.6,
    source: 'prose',
    citation:
      'https://docs.github.com/en/rest/issues/issues#list-repository-issues — "List issues in a repository. Only open issues will be listed."',
  },
};
