/**
 * Doc-grounded per-operation side-effect metadata for the 'gmail' bubble (IR-8).
 *
 * GENERATED by scripts/backfill-operation-metadata.ts — regenerate with:
 *   pnpm --filter @bubblelab/bubble-core backfill:operation-metadata
 * Review the citations when the vendor API or the bubble's operations change; do not edit the
 * classifications without updating the citation that grounds them.
 *
 * Binding rule: 'write' iff the docs say the operation CREATES A NEW RECORD (even as a side
 * effect); 'read_with_side_effects' when the docs indicate mutation without record creation
 * (update/delete/mark — 'destructive' carries the delete signal); 'read' when the docs indicate
 * no mutation. The HTTP method is never the signal.
 */
import type { BubbleOperationMetadata } from '@bubblelab/shared-schemas';

export const GMAIL_OPERATION_METADATA: BubbleOperationMetadata = {
  send_email: {
    sideEffect: 'write',
    destructive: false,
    idempotent: false,
    confidence: 0.6,
    source: 'prose',
    citation:
      'https://developers.google.com/workspace/gmail/api/reference/rest/v1/users.messages/send — "Sends the specified message to the recipients in the To, Cc, and Bcc headers."',
  },
  list_emails: {
    sideEffect: 'read',
    destructive: false,
    idempotent: true,
    confidence: 0.6,
    source: 'prose',
    citation:
      'https://developers.google.com/workspace/gmail/api/reference/rest/v1/users.messages/list — "Lists the messages in the user\'s mailbox."',
  },
  get_email: {
    sideEffect: 'read',
    destructive: false,
    idempotent: true,
    confidence: 0.6,
    source: 'prose',
    citation:
      'https://developers.google.com/workspace/gmail/api/reference/rest/v1/users.messages/get — "Gets the specified message."',
  },
  search_emails: {
    sideEffect: 'read',
    destructive: false,
    idempotent: true,
    confidence: 0.6,
    source: 'prose',
    citation:
      'https://developers.google.com/workspace/gmail/api/reference/rest/v1/users.messages/list — "Lists the messages in the user\'s mailbox."',
  },
  mark_as_read: {
    sideEffect: 'read_with_side_effects',
    destructive: false,
    idempotent: true,
    confidence: 0.6,
    source: 'prose',
    citation:
      'https://developers.google.com/workspace/gmail/api/reference/rest/v1/users.messages/modify — "Modifies the labels on the specified message."',
  },
  mark_as_unread: {
    sideEffect: 'read_with_side_effects',
    destructive: false,
    idempotent: true,
    confidence: 0.6,
    source: 'prose',
    citation:
      'https://developers.google.com/workspace/gmail/api/reference/rest/v1/users.messages/modify — "Modifies the labels on the specified message."',
  },
  create_draft: {
    sideEffect: 'write',
    destructive: false,
    idempotent: false,
    confidence: 0.6,
    source: 'prose',
    citation:
      'https://developers.google.com/workspace/gmail/api/reference/rest/v1/users.drafts/create — "Creates a new draft with the DRAFT label."',
  },
  send_draft: {
    sideEffect: 'write',
    destructive: false,
    idempotent: false,
    confidence: 0.6,
    source: 'prose',
    citation:
      'https://developers.google.com/workspace/gmail/api/reference/rest/v1/users.drafts/send — "Sends the specified, existing draft to the recipients in the To, Cc, and Bcc headers."',
  },
  list_drafts: {
    sideEffect: 'read',
    destructive: false,
    idempotent: true,
    confidence: 0.6,
    source: 'prose',
    citation:
      'https://developers.google.com/workspace/gmail/api/reference/rest/v1/users.drafts/list — "Lists the drafts in the user\'s mailbox."',
  },
  delete_email: {
    sideEffect: 'read_with_side_effects',
    destructive: true,
    idempotent: true,
    confidence: 0.6,
    source: 'prose',
    citation:
      'https://developers.google.com/workspace/gmail/api/reference/rest/v1/users.messages/delete — "Immediately and permanently deletes the specified message. This operation cannot be undone."',
  },
  trash_email: {
    sideEffect: 'read_with_side_effects',
    destructive: false,
    idempotent: true,
    confidence: 0.6,
    source: 'prose',
    citation:
      'https://developers.google.com/workspace/gmail/api/reference/rest/v1/users.messages/trash — "Moves the specified message to the trash."',
  },
  list_threads: {
    sideEffect: 'read',
    destructive: false,
    idempotent: true,
    confidence: 0.6,
    source: 'prose',
    citation:
      'https://developers.google.com/workspace/gmail/api/reference/rest/v1/users.threads/list — "Lists the threads in the user\'s mailbox."',
  },
  list_labels: {
    sideEffect: 'read',
    destructive: false,
    idempotent: true,
    confidence: 0.6,
    source: 'prose',
    citation:
      'https://developers.google.com/workspace/gmail/api/reference/rest/v1/users.labels/list — "Lists all labels in the user\'s mailbox."',
  },
  create_label: {
    sideEffect: 'write',
    destructive: false,
    idempotent: false,
    confidence: 0.6,
    source: 'prose',
    citation:
      'https://developers.google.com/workspace/gmail/api/reference/rest/v1/users.labels/create — "Creates a new label."',
  },
  modify_message_labels: {
    sideEffect: 'read_with_side_effects',
    destructive: false,
    idempotent: true,
    confidence: 0.6,
    source: 'prose',
    citation:
      'https://developers.google.com/workspace/gmail/api/reference/rest/v1/users.messages/modify — "Modifies the labels on the specified message."',
  },
  modify_thread_labels: {
    sideEffect: 'read_with_side_effects',
    destructive: false,
    idempotent: true,
    confidence: 0.6,
    source: 'prose',
    citation:
      'https://developers.google.com/workspace/gmail/api/reference/rest/v1/users.threads/modify — "Modifies the labels applied to the thread. This applies to all messages in the thread."',
  },
  get_attachment: {
    sideEffect: 'read',
    destructive: false,
    idempotent: true,
    confidence: 0.6,
    source: 'prose',
    citation:
      'https://developers.google.com/workspace/gmail/api/reference/rest/v1/users.messages.attachments/get — "Gets the specified message attachment."',
  },
};
