/**
 * Doc-grounded per-operation side-effect metadata for the 'google-calendar' bubble (IR-8).
 *
 * GENERATED by scripts/backfill-operation-metadata.ts — regenerate with:
 *   pnpm --filter @bubblelab/bubble-core backfill:operation-metadata
 * Review the citations when the vendor API or the bubble's operations change; do not edit the
 * classifications without updating the citation that grounds them.
 *
 * Binding rule: 'write' iff the docs say the operation CREATES A NEW RECORD (even as a side
 * effect); 'read_with_side_effects' when the docs indicate mutation without record creation
 * (update/delete/mark — 'destructive' carries the delete signal); 'read' when the docs indicate
 * no mutation. The HTTP method is never the signal.
 */
import type { BubbleOperationMetadata } from '@bubblelab/shared-schemas';

export const GOOGLE_CALENDAR_OPERATION_METADATA: BubbleOperationMetadata = {
  list_calendars: {
    sideEffect: 'read',
    destructive: false,
    idempotent: true,
    confidence: 0.6,
    source: 'prose',
    citation:
      'https://developers.google.com/workspace/calendar/api/v3/reference/calendarList/list — "Returns the calendars on the user\'s calendar list."',
    requiredScopes: [
      'https://www.googleapis.com/auth/calendar.readonly|https://www.googleapis.com/auth/calendar|https://www.googleapis.com/auth/calendar.calendarlist|https://www.googleapis.com/auth/calendar.calendarlist.readonly',
    ],
  },
  list_events: {
    sideEffect: 'read',
    destructive: false,
    idempotent: true,
    confidence: 0.6,
    source: 'prose',
    citation:
      'https://developers.google.com/workspace/calendar/api/v3/reference/events/list — "Returns events on the specified calendar."',
    requiredScopes: [
      'https://www.googleapis.com/auth/calendar.readonly|https://www.googleapis.com/auth/calendar|https://www.googleapis.com/auth/calendar.events.readonly|https://www.googleapis.com/auth/calendar.events|https://www.googleapis.com/auth/calendar.app.created|https://www.googleapis.com/auth/calendar.events.freebusy|https://www.googleapis.com/auth/calendar.events.owned|https://www.googleapis.com/auth/calendar.events.owned.readonly|https://www.googleapis.com/auth/calendar.events.public.readonly',
    ],
  },
  get_event: {
    sideEffect: 'read',
    destructive: false,
    idempotent: true,
    confidence: 0.6,
    source: 'prose',
    citation:
      'https://developers.google.com/workspace/calendar/api/v3/reference/events/get — "Returns an event based on its Google Calendar ID."',
    requiredScopes: [
      'https://www.googleapis.com/auth/calendar.readonly|https://www.googleapis.com/auth/calendar|https://www.googleapis.com/auth/calendar.events.readonly|https://www.googleapis.com/auth/calendar.events|https://www.googleapis.com/auth/calendar.app.created|https://www.googleapis.com/auth/calendar.events.freebusy|https://www.googleapis.com/auth/calendar.events.owned|https://www.googleapis.com/auth/calendar.events.owned.readonly|https://www.googleapis.com/auth/calendar.events.public.readonly',
    ],
  },
  create_event: {
    sideEffect: 'write',
    destructive: false,
    idempotent: false,
    confidence: 0.6,
    source: 'prose',
    citation:
      'https://developers.google.com/workspace/calendar/api/v3/reference/events/insert — "Creates an event."',
    requiredScopes: [
      'https://www.googleapis.com/auth/calendar|https://www.googleapis.com/auth/calendar.events|https://www.googleapis.com/auth/calendar.app.created|https://www.googleapis.com/auth/calendar.events.owned',
    ],
  },
  update_event: {
    sideEffect: 'read_with_side_effects',
    destructive: false,
    idempotent: true,
    confidence: 0.6,
    source: 'prose',
    citation:
      'https://developers.google.com/workspace/calendar/api/v3/reference/events/update — "Updates an event."',
    requiredScopes: [
      'https://www.googleapis.com/auth/calendar|https://www.googleapis.com/auth/calendar.events|https://www.googleapis.com/auth/calendar.app.created|https://www.googleapis.com/auth/calendar.events.owned',
    ],
  },
  delete_event: {
    sideEffect: 'read_with_side_effects',
    destructive: true,
    idempotent: true,
    confidence: 0.6,
    source: 'prose',
    citation:
      'https://developers.google.com/workspace/calendar/api/v3/reference/events/delete — "Deletes an event."',
    requiredScopes: [
      'https://www.googleapis.com/auth/calendar|https://www.googleapis.com/auth/calendar.events|https://www.googleapis.com/auth/calendar.app.created|https://www.googleapis.com/auth/calendar.events.owned',
    ],
  },
};
