/**
 * Doc-grounded per-operation side-effect metadata for the 'google-drive' bubble (IR-8).
 *
 * GENERATED by scripts/backfill-operation-metadata.ts — regenerate with:
 *   pnpm --filter @bubblelab/bubble-core backfill:operation-metadata
 * Review the citations when the vendor API or the bubble's operations change; do not edit the
 * classifications without updating the citation that grounds them.
 *
 * Binding rule: 'write' iff the docs say the operation CREATES A NEW RECORD (even as a side
 * effect); 'read_with_side_effects' when the docs indicate mutation without record creation
 * (update/delete/mark — 'destructive' carries the delete signal); 'read' when the docs indicate
 * no mutation. The HTTP method is never the signal.
 */
import type { BubbleOperationMetadata } from '@bubblelab/shared-schemas';

export const GOOGLE_DRIVE_OPERATION_METADATA: BubbleOperationMetadata = {
  upload_file: {
    sideEffect: 'write',
    destructive: false,
    idempotent: false,
    confidence: 0.6,
    source: 'prose',
    citation:
      'https://developers.google.com/workspace/drive/api/reference/rest/v3/files/create — "Creates a new file."',
    requiredScopes: [
      'https://www.googleapis.com/auth/drive|https://www.googleapis.com/auth/drive.appdata|https://www.googleapis.com/auth/drive.file',
    ],
  },
  download_file: {
    sideEffect: 'read',
    destructive: false,
    idempotent: true,
    confidence: 0.6,
    source: 'prose',
    citation:
      'https://developers.google.com/workspace/drive/api/reference/rest/v3/files/get — "Gets a file\'s metadata or content by ID."',
    requiredScopes: [
      'https://www.googleapis.com/auth/drive|https://www.googleapis.com/auth/drive.appdata|https://www.googleapis.com/auth/drive.file|https://www.googleapis.com/auth/drive.meet.readonly|https://www.googleapis.com/auth/drive.metadata|https://www.googleapis.com/auth/drive.metadata.readonly|https://www.googleapis.com/auth/drive.photos.readonly|https://www.googleapis.com/auth/drive.readonly',
    ],
  },
  list_files: {
    sideEffect: 'read',
    destructive: false,
    idempotent: true,
    confidence: 0.6,
    source: 'prose',
    citation:
      'https://developers.google.com/workspace/drive/api/reference/rest/v3/files/list — "Lists the user\'s files."',
    requiredScopes: [
      'https://www.googleapis.com/auth/drive|https://www.googleapis.com/auth/drive.appdata|https://www.googleapis.com/auth/drive.file|https://www.googleapis.com/auth/drive.meet.readonly|https://www.googleapis.com/auth/drive.metadata|https://www.googleapis.com/auth/drive.metadata.readonly|https://www.googleapis.com/auth/drive.photos.readonly|https://www.googleapis.com/auth/drive.readonly',
    ],
  },
  create_folder: {
    sideEffect: 'write',
    destructive: false,
    idempotent: false,
    confidence: 0.6,
    source: 'prose',
    citation:
      'https://developers.google.com/workspace/drive/api/reference/rest/v3/files/create — "Creates a new file."',
    requiredScopes: [
      'https://www.googleapis.com/auth/drive|https://www.googleapis.com/auth/drive.appdata|https://www.googleapis.com/auth/drive.file',
    ],
  },
  delete_file: {
    sideEffect: 'read_with_side_effects',
    destructive: true,
    idempotent: true,
    confidence: 0.6,
    source: 'prose',
    citation:
      'packages/bubble-core/src/bubbles/service-bubble/google-drive.ts#operation:delete_file — "Delete a file or folder from Google Drive" (schema prose; vendor doc root: https://developers.google.com/workspace/drive/api/reference/rest/v3)',
    requiredScopes: [
      'https://www.googleapis.com/auth/drive|https://www.googleapis.com/auth/drive.appdata|https://www.googleapis.com/auth/drive.file',
    ],
  },
  get_file_info: {
    sideEffect: 'read',
    destructive: false,
    idempotent: true,
    confidence: 0.6,
    source: 'prose',
    citation:
      'https://developers.google.com/workspace/drive/api/reference/rest/v3/files/get — "Gets a file\'s metadata or content by ID."',
    requiredScopes: [
      'https://www.googleapis.com/auth/drive|https://www.googleapis.com/auth/drive.appdata|https://www.googleapis.com/auth/drive.file|https://www.googleapis.com/auth/drive.meet.readonly|https://www.googleapis.com/auth/drive.metadata|https://www.googleapis.com/auth/drive.metadata.readonly|https://www.googleapis.com/auth/drive.photos.readonly|https://www.googleapis.com/auth/drive.readonly',
    ],
  },
  share_file: {
    sideEffect: 'write',
    destructive: false,
    idempotent: false,
    confidence: 0.6,
    source: 'prose',
    citation:
      'https://developers.google.com/workspace/drive/api/reference/rest/v3/permissions/create — "Creates a permission for a file or shared drive."',
    requiredScopes: [
      'https://www.googleapis.com/auth/drive|https://www.googleapis.com/auth/drive.file',
    ],
  },
  move_file: {
    sideEffect: 'read_with_side_effects',
    destructive: false,
    idempotent: true,
    confidence: 0.6,
    source: 'prose',
    citation:
      'https://developers.google.com/workspace/drive/api/reference/rest/v3/files/update — "Updates a file\'s metadata and/or content."',
    requiredScopes: [
      'https://www.googleapis.com/auth/drive|https://www.googleapis.com/auth/drive.appdata|https://www.googleapis.com/auth/drive.file|https://www.googleapis.com/auth/drive.metadata|https://www.googleapis.com/auth/drive.scripts',
    ],
  },
  get_doc: {
    sideEffect: 'read',
    destructive: false,
    idempotent: true,
    confidence: 0.6,
    source: 'prose',
    citation:
      'https://developers.google.com/workspace/docs/api/reference/rest/v1/documents/get — "Gets the latest version of the specified document."',
    requiredScopes: [
      'https://www.googleapis.com/auth/documents|https://www.googleapis.com/auth/documents.readonly|https://www.googleapis.com/auth/drive|https://www.googleapis.com/auth/drive.readonly|https://www.googleapis.com/auth/drive.file',
    ],
  },
  update_doc: {
    sideEffect: 'read_with_side_effects',
    destructive: false,
    idempotent: true,
    confidence: 0.6,
    source: 'prose',
    citation:
      'https://developers.google.com/workspace/docs/api/reference/rest/v1/documents/batchUpdate — "Applies one or more updates to the document."',
    requiredScopes: [
      'https://www.googleapis.com/auth/documents|https://www.googleapis.com/auth/drive|https://www.googleapis.com/auth/drive.file',
    ],
  },
  replace_text: {
    sideEffect: 'read_with_side_effects',
    destructive: false,
    idempotent: true,
    confidence: 0.6,
    source: 'prose',
    citation:
      'https://developers.google.com/workspace/docs/api/reference/rest/v1/documents/batchUpdate — "Applies one or more updates to the document."',
    requiredScopes: [
      'https://www.googleapis.com/auth/documents|https://www.googleapis.com/auth/drive|https://www.googleapis.com/auth/drive.file',
    ],
  },
  copy_doc: {
    sideEffect: 'write',
    destructive: false,
    idempotent: false,
    confidence: 0.6,
    source: 'prose',
    citation:
      'https://developers.google.com/workspace/drive/api/reference/rest/v3/files/copy — "Creates a copy of a file and applies any requested updates with patch semantics."',
    requiredScopes: [
      'https://www.googleapis.com/auth/drive|https://www.googleapis.com/auth/drive.appdata|https://www.googleapis.com/auth/drive.file|https://www.googleapis.com/auth/drive.photos.readonly',
    ],
  },
};
