/**
 * Doc-grounded per-operation side-effect metadata for the 'resend' bubble (IR-8).
 *
 * GENERATED by scripts/backfill-operation-metadata.ts — regenerate with:
 *   pnpm --filter @bubblelab/bubble-core backfill:operation-metadata
 * Review the citations when the vendor API or the bubble's operations change; do not edit the
 * classifications without updating the citation that grounds them.
 *
 * Binding rule: 'write' iff the docs say the operation CREATES A NEW RECORD (even as a side
 * effect); 'read_with_side_effects' when the docs indicate mutation without record creation
 * (update/delete/mark — 'destructive' carries the delete signal); 'read' when the docs indicate
 * no mutation. The HTTP method is never the signal.
 */
import type { BubbleOperationMetadata } from '@bubblelab/shared-schemas';

export const RESEND_OPERATION_METADATA: BubbleOperationMetadata = {
  send_email: {
    sideEffect: 'write',
    destructive: false,
    idempotent: false,
    confidence: 0.6,
    source: 'prose',
    citation:
      'https://resend.com/docs/api-reference/emails/send-email — "Start sending emails through the Resend Email API."',
  },
  send_batch_emails: {
    sideEffect: 'write',
    destructive: false,
    idempotent: false,
    confidence: 0.6,
    source: 'prose',
    citation:
      'packages/bubble-core/src/bubbles/service-bubble/resend.ts#operation:send_batch_emails — "Send up to 100 batch emails in a single API call" (schema prose; vendor doc root: https://resend.com/docs/api-reference/emails)',
  },
  get_email_status: {
    sideEffect: 'read',
    destructive: false,
    idempotent: true,
    confidence: 0.6,
    source: 'prose',
    citation:
      'https://resend.com/docs/api-reference/emails/retrieve-email — "Retrieve a single email."',
  },
};
