/**
 * ServiceBubble class (raw-fetch pattern) for the 'snowflake-sql-api' bubble.
 *
 * GENERATED by @bubblelab/bubble-appgen from sqlapi.yaml — do not hand-edit;
 * re-run `pnpm --filter @bubblelab/bubble-appgen generate:snowflake-sql-api` instead.
 * Vendor docs: https://docs.snowflake.com/en/developer-guide/sql-api/intro
 */

import { ServiceBubble } from '../../../types/service-bubble-class.js';
import type { BubbleContext } from '../../../types/bubble.js';
import { CredentialType } from '@bubblelab/shared-schemas';
import { SNOWFLAKE_SQL_API_OPERATION_METADATA } from './snowflake-sql-api.metadata.js';
import {
  SnowflakeSqlApiParamsSchema,
  SnowflakeSqlApiResultSchema,
  SubmitStatementPayloadSchema,
  GetStatementStatusPayloadSchema,
  CancelStatementPayloadSchema,
  type SnowflakeSqlApiParams,
  type SnowflakeSqlApiParamsInput,
  type SnowflakeSqlApiResult,
} from './snowflake-sql-api.schema.js';

/** Strip a trailing slash so path concatenation stays canonical. */
function trimBaseUrl(url: string): string {
  return url.endsWith('/') ? url.slice(0, -1) : url;
}

/** Serialize defined query params; returns '' or '?k=v&…'. */
function buildQuery(
  params: Record<string, string | number | boolean | undefined>
): string {
  const search = new URLSearchParams();
  for (const [key, value] of Object.entries(params)) {
    if (value !== undefined) search.set(key, String(value));
  }
  const qs = search.toString();
  return qs.length > 0 ? `?${qs}` : '';
}

/** Drop undefined values before JSON body serialization. */
function pruneUndefined(
  record: Record<string, unknown>
): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(record)) {
    if (value !== undefined) out[key] = value;
  }
  return out;
}

export class SnowflakeSqlApiBubble<
  T extends SnowflakeSqlApiParamsInput = SnowflakeSqlApiParamsInput,
> extends ServiceBubble<
  T,
  Extract<SnowflakeSqlApiResult, { operation: T['operation'] }>
> {
  static readonly type = 'service' as const;
  static readonly service = 'snowflake';
  // S5 auth (openapi): inferred from securityScheme ExternalOAuth (http bearer); alternatives: KeyPair (http bearer), SnowflakeOAuth (oauth2)
  static readonly authType = 'apikey' as const;
  static readonly bubbleName = 'snowflake-sql-api';
  static readonly operationMetadata = SNOWFLAKE_SQL_API_OPERATION_METADATA;
  static readonly schema = SnowflakeSqlApiParamsSchema;
  static readonly resultSchema = SnowflakeSqlApiResultSchema;
  static readonly shortDescription =
    'Snowflake SQL API v2 integration generated from the official OpenAPI spec (submit, poll, cancel SQL statements)';
  static readonly longDescription = `
    Snowflake SQL API v2 integration generated from the official OpenAPI spec (submit, poll, cancel SQL statements)

    Operations (generated from the vendor OpenAPI spec):
    - submit_statement [side-effect: write]: Submits a SQL statement for execution.
    - get_statement_status [side-effect: read_with_side_effects]: Checks the status of the execution of a statement
    - cancel_statement [side-effect: write]: Cancels the execution of a statement.

    Credential: SNOWFLAKE_PAT (bearer token) + per-account accountUrl.
  `;
  static readonly alias = 'sf-sql';

  constructor(
    params: T = {
      operation: 'get_statement_status',
      accountUrl: 'https://org-account.snowflakecomputing.com',
      statementHandle: 'e4ce975e-f7ff-4b5e-b15e-bf25f59371ae',
    } as T,
    context?: BubbleContext
  ) {
    super(params, context);
  }

  private requestHeaders(
    token: string,
    hasBody: boolean
  ): Record<string, string> {
    const headers: Record<string, string> = {
      Authorization: `Bearer ${token}`,
      Accept: 'application/json',
      'User-Agent': 'bubblelab/1.0',
      'X-Snowflake-Authorization-Token-Type': 'PROGRAMMATIC_ACCESS_TOKEN',
    };
    if (hasBody) headers['Content-Type'] = 'application/json';
    return headers;
  }

  public async testCredential(): Promise<boolean> {
    const token = this.chooseCredential();
    if (!token) {
      throw new Error('snowflake-sql-api credentials are required');
    }
    const params = { accountUrl: this.params.accountUrl };
    // Probe: GET /api/v2/statements/{statementHandle} (get_statement_status) with a synthesized handle.
    // 401/403 mean the credential was rejected; any other status means it was accepted.
    const response = await fetch(
      `${trimBaseUrl(params.accountUrl)}/api/v2/statements/e4ce975e-f7ff-4b5e-b15e-bf25f59371ae`,
      {
        method: 'GET',
        headers: this.requestHeaders(token, false),
      }
    );
    return response.status !== 401 && response.status !== 403;
  }

  protected chooseCredential(): string | undefined {
    const credentials = this.params.credentials;
    if (!credentials || typeof credentials !== 'object') {
      return undefined;
    }
    return credentials[CredentialType.SNOWFLAKE_PAT];
  }

  protected async performAction(
    context?: BubbleContext
  ): Promise<Extract<SnowflakeSqlApiResult, { operation: T['operation'] }>> {
    void context;
    const { operation } = this.params;
    switch (operation) {
      case 'submit_statement':
        return this.handleSubmitStatement() as Promise<
          Extract<SnowflakeSqlApiResult, { operation: T['operation'] }>
        >;
      case 'get_statement_status':
        return this.handleGetStatementStatus() as Promise<
          Extract<SnowflakeSqlApiResult, { operation: T['operation'] }>
        >;
      case 'cancel_statement':
        return this.handleCancelStatement() as Promise<
          Extract<SnowflakeSqlApiResult, { operation: T['operation'] }>
        >;
      default:
        return {
          operation: operation as T['operation'],
          success: false,
          error: `Unknown operation: ${String(operation)}`,
        } as Extract<SnowflakeSqlApiResult, { operation: T['operation'] }>;
    }
  }

  private async handleSubmitStatement(): Promise<
    Extract<SnowflakeSqlApiResult, { operation: 'submit_statement' }>
  > {
    const params = SnowflakeSqlApiParamsSchema.parse(this.params) as Extract<
      SnowflakeSqlApiParams,
      { operation: 'submit_statement' }
    >;
    try {
      const token = this.chooseCredential();
      if (!token) {
        return {
          operation: 'submit_statement',
          success: false,
          error: 'SNOWFLAKE_PAT credential not found',
        };
      }
      const query = buildQuery({
        requestId: params.requestId,
        async: params.async,
        nullable: params.nullable,
      });
      const url = `${trimBaseUrl(params.accountUrl)}/api/v2/statements${query}`;
      const body = pruneUndefined({
        statement: params.statement,
        timeout: params.timeout,
        database: params.database,
        schema: params.schema,
        warehouse: params.warehouse,
        role: params.role,
        bindings: params.bindings,
        parameters: params.parameters,
      });
      const response = await fetch(url, {
        method: 'POST',
        headers: this.requestHeaders(token, true),
        body: JSON.stringify(body),
      });
      if (!response.ok) {
        const errorText = await response.text();
        return {
          operation: 'submit_statement',
          success: false,
          error: `snowflake-sql-api API error (${response.status}): ${errorText}`,
        };
      }
      const payload = SubmitStatementPayloadSchema.parse(await response.json());
      return {
        operation: 'submit_statement',
        success: true,
        error: '',
        ...payload,
      };
    } catch (error) {
      return {
        operation: 'submit_statement',
        success: false,
        error:
          error instanceof Error ? error.message : 'Unknown error occurred',
      };
    }
  }

  private async handleGetStatementStatus(): Promise<
    Extract<SnowflakeSqlApiResult, { operation: 'get_statement_status' }>
  > {
    const params = SnowflakeSqlApiParamsSchema.parse(this.params) as Extract<
      SnowflakeSqlApiParams,
      { operation: 'get_statement_status' }
    >;
    try {
      const token = this.chooseCredential();
      if (!token) {
        return {
          operation: 'get_statement_status',
          success: false,
          error: 'SNOWFLAKE_PAT credential not found',
        };
      }
      const query = buildQuery({
        requestId: params.requestId,
        partition: params.partition,
      });
      const url = `${trimBaseUrl(params.accountUrl)}/api/v2/statements/${encodeURIComponent(params.statementHandle)}${query}`;
      const response = await fetch(url, {
        method: 'GET',
        headers: this.requestHeaders(token, false),
      });
      if (!response.ok) {
        const errorText = await response.text();
        return {
          operation: 'get_statement_status',
          success: false,
          error: `snowflake-sql-api API error (${response.status}): ${errorText}`,
        };
      }
      const payload = GetStatementStatusPayloadSchema.parse(
        await response.json()
      );
      return {
        operation: 'get_statement_status',
        success: true,
        error: '',
        ...payload,
      };
    } catch (error) {
      return {
        operation: 'get_statement_status',
        success: false,
        error:
          error instanceof Error ? error.message : 'Unknown error occurred',
      };
    }
  }

  private async handleCancelStatement(): Promise<
    Extract<SnowflakeSqlApiResult, { operation: 'cancel_statement' }>
  > {
    const params = SnowflakeSqlApiParamsSchema.parse(this.params) as Extract<
      SnowflakeSqlApiParams,
      { operation: 'cancel_statement' }
    >;
    try {
      const token = this.chooseCredential();
      if (!token) {
        return {
          operation: 'cancel_statement',
          success: false,
          error: 'SNOWFLAKE_PAT credential not found',
        };
      }
      const query = buildQuery({
        requestId: params.requestId,
      });
      const url = `${trimBaseUrl(params.accountUrl)}/api/v2/statements/${encodeURIComponent(params.statementHandle)}/cancel${query}`;
      const response = await fetch(url, {
        method: 'POST',
        headers: this.requestHeaders(token, false),
      });
      if (!response.ok) {
        const errorText = await response.text();
        return {
          operation: 'cancel_statement',
          success: false,
          error: `snowflake-sql-api API error (${response.status}): ${errorText}`,
        };
      }
      const payload = CancelStatementPayloadSchema.parse(await response.json());
      return {
        operation: 'cancel_statement',
        success: true,
        error: '',
        ...payload,
      };
    } catch (error) {
      return {
        operation: 'cancel_statement',
        success: false,
        error:
          error instanceof Error ? error.message : 'Unknown error occurred',
      };
    }
  }
}
