/**
 * Zod contract (params + results) for the 'snowflake-sql-api' bubble.
 *
 * GENERATED by @bubblelab/bubble-appgen from sqlapi.yaml — do not hand-edit;
 * re-run `pnpm --filter @bubblelab/bubble-appgen generate:snowflake-sql-api` instead.
 * Vendor docs: https://docs.snowflake.com/en/developer-guide/sql-api/intro
 */

import { z } from 'zod';
import { CredentialType } from '@bubblelab/shared-schemas';

// Base credentials schema shared by every operation branch
const BaseCredentialsSchema = z
  .record(z.nativeEnum(CredentialType), z.string())
  .optional()
  .describe('Object mapping credential types to values (injected at runtime)');

/** Documented 2xx response payload of SubmitStatement (statuses: 200, 202); all fields optional because presence varies by status code. */
export const SubmitStatementPayloadSchema = z.object({
  code: z.string().optional(),
  sqlState: z.string().optional(),
  message: z.string().optional(),
  statementHandle: z.string().uuid().optional(),
  createdOn: z
    .number()
    .int()
    .describe(
      'Timestamp that specifies when the statement execution started.‌ The timestamp is expressed in milliseconds since the epoch.‌'
    )
    .optional(),
  statementStatusUrl: z.string().optional(),
  resultSetMetaData: z
    .object({
      format: z
        .enum(['jsonv2'])
        .describe(
          'For v2 endpoints the only possible value for this field is jsonv2.'
        )
        .optional(),
      numRows: z
        .number()
        .int()
        .describe('The total number of rows of results.')
        .optional(),
      rowType: z
        .array(
          z.object({
            name: z.string().optional(),
            type: z.string().optional(),
            length: z.number().int().min(0).optional(),
            precision: z.number().int().min(0).optional(),
            scale: z.number().int().min(0).optional(),
            nullable: z.boolean().optional(),
          })
        )
        .optional(),
      partitionInfo: z
        .array(
          z.object({
            rowCount: z
              .number()
              .int()
              .min(0)
              .describe('Number of rows in the partition.')
              .optional(),
            compressedSize: z
              .number()
              .int()
              .min(0)
              .describe(
                'the partition size before the decompression. This may or may not be present in the partitionInfo. Uncompressed size would always be there.'
              )
              .optional(),
            uncompressedSize: z
              .number()
              .int()
              .min(0)
              .describe('the partition size after the decompression')
              .optional(),
          })
        )
        .describe('Partition information')
        .optional(),
      nullable: z
        .boolean()
        .describe(
          "false if null is replaced with a string 'null' otherwise false"
        )
        .optional(),
      parameters: z
        .object({
          binary_output_format: z.string().optional(),
          date_output_format: z.string().optional(),
          time_output_format: z.string().optional(),
          timestamp_output_format: z.string().optional(),
          timestamp_ltz_output_format: z.string().optional(),
          timestamp_ntz_output_format: z.string().optional(),
          timestamp_tz_output_format: z.string().optional(),
          multi_statement_count: z.number().int().optional(),
        })
        .optional(),
    })
    .optional(),
  data: z
    .array(z.array(z.string().nullable()))
    .describe('Result set data.')
    .optional(),
  stats: z
    .object({
      numRowsInserted: z
        .number()
        .int()
        .min(0)
        .describe('Number of rows that were inserted.')
        .optional(),
      numRowsUpdated: z
        .number()
        .int()
        .min(0)
        .describe('Number of rows that were updated.')
        .optional(),
      numRowsDeleted: z
        .number()
        .int()
        .min(0)
        .describe('Number of rows that were deleted.')
        .optional(),
      numDuplicateRowsUpdated: z
        .number()
        .int()
        .min(0)
        .describe('Number of duplicate rows that were updated.')
        .optional(),
    })
    .describe('these stats might not be available for each request.')
    .optional(),
});

/** Documented 2xx response payload of GetStatementStatus (statuses: 200, 202); all fields optional because presence varies by status code. */
export const GetStatementStatusPayloadSchema = z.object({
  code: z.string().optional(),
  sqlState: z.string().optional(),
  message: z.string().optional(),
  statementHandle: z.string().uuid().optional(),
  createdOn: z
    .number()
    .int()
    .describe(
      'Timestamp that specifies when the statement execution started.‌ The timestamp is expressed in milliseconds since the epoch.‌'
    )
    .optional(),
  statementStatusUrl: z.string().optional(),
  resultSetMetaData: z
    .object({
      format: z
        .enum(['jsonv2'])
        .describe(
          'For v2 endpoints the only possible value for this field is jsonv2.'
        )
        .optional(),
      numRows: z
        .number()
        .int()
        .describe('The total number of rows of results.')
        .optional(),
      rowType: z
        .array(
          z.object({
            name: z.string().optional(),
            type: z.string().optional(),
            length: z.number().int().min(0).optional(),
            precision: z.number().int().min(0).optional(),
            scale: z.number().int().min(0).optional(),
            nullable: z.boolean().optional(),
          })
        )
        .optional(),
      partitionInfo: z
        .array(
          z.object({
            rowCount: z
              .number()
              .int()
              .min(0)
              .describe('Number of rows in the partition.')
              .optional(),
            compressedSize: z
              .number()
              .int()
              .min(0)
              .describe(
                'the partition size before the decompression. This may or may not be present in the partitionInfo. Uncompressed size would always be there.'
              )
              .optional(),
            uncompressedSize: z
              .number()
              .int()
              .min(0)
              .describe('the partition size after the decompression')
              .optional(),
          })
        )
        .describe('Partition information')
        .optional(),
      nullable: z
        .boolean()
        .describe(
          "false if null is replaced with a string 'null' otherwise false"
        )
        .optional(),
      parameters: z
        .object({
          binary_output_format: z.string().optional(),
          date_output_format: z.string().optional(),
          time_output_format: z.string().optional(),
          timestamp_output_format: z.string().optional(),
          timestamp_ltz_output_format: z.string().optional(),
          timestamp_ntz_output_format: z.string().optional(),
          timestamp_tz_output_format: z.string().optional(),
          multi_statement_count: z.number().int().optional(),
        })
        .optional(),
    })
    .optional(),
  data: z
    .array(z.array(z.string().nullable()))
    .describe('Result set data.')
    .optional(),
  stats: z
    .object({
      numRowsInserted: z
        .number()
        .int()
        .min(0)
        .describe('Number of rows that were inserted.')
        .optional(),
      numRowsUpdated: z
        .number()
        .int()
        .min(0)
        .describe('Number of rows that were updated.')
        .optional(),
      numRowsDeleted: z
        .number()
        .int()
        .min(0)
        .describe('Number of rows that were deleted.')
        .optional(),
      numDuplicateRowsUpdated: z
        .number()
        .int()
        .min(0)
        .describe('Number of duplicate rows that were updated.')
        .optional(),
    })
    .describe('these stats might not be available for each request.')
    .optional(),
});

/** Documented 2xx response payload of CancelStatement (statuses: 200); all fields optional because presence varies by status code. */
export const CancelStatementPayloadSchema = z.object({
  code: z.string().optional(),
  sqlState: z.string().optional(),
  message: z.string().optional(),
  statementHandle: z.string().uuid().optional(),
  statementStatusUrl: z.string().optional(),
});

export const SnowflakeSqlApiParamsSchema = z.discriminatedUnion('operation', [
  z.object({
    operation: z
      .literal('submit_statement')
      .describe('Submits a SQL statement for execution.'),
    accountUrl: z
      .string()
      .url()
      .describe(
        'Per-account Snowflake base URL (e.g. https://org-account.snowflakecomputing.com)'
      ),
    statement: z
      .string()
      .describe(
        'SQL statement or batch of SQL statements to execute. You can specify query, DML and DDL statements. The following statements are not supported: PUT, GET, USE, ALTER SESSION, BEGIN, COMMIT, ROLLBACK, statements that set session variables, and statements that create temporary tables and stages.'
      )
      .optional(),
    timeout: z
      .number()
      .int()
      .min(0)
      .describe(
        'Timeout in seconds for statement execution. If the execution of a statement takes longer than the specified timeout, the execution is automatically canceled. To set the timeout to the maximum value (604800 seconds), set timeout to 0.'
      )
      .optional(),
    database: z
      .string()
      .describe(
        'Database in which the statement should be executed. The value in this field is case-sensitive.'
      )
      .optional(),
    schema: z
      .string()
      .describe(
        'Schema in which the statement should be executed. The value in this field is case-sensitive.'
      )
      .optional(),
    warehouse: z
      .string()
      .describe(
        'Warehouse to use when executing the statement. The value in this field is case-sensitive.'
      )
      .optional(),
    role: z
      .string()
      .describe(
        'Role to use when executing the statement. The value in this field is case-sensitive.'
      )
      .optional(),
    bindings: z
      .record(z.string(), z.unknown())
      .describe(
        "Values of bind variables in the SQL statement. When executing the statement, Snowflake replaces placeholders ('?' and ':name') in the statement with these specified values."
      )
      .optional(),
    parameters: z
      .object({
        timezone: z
          .string()
          .describe('Time zone to use when executing the statement.')
          .optional(),
        query_tag: z
          .string()
          .describe(
            'Query tag that you want to associate with the SQL statement.'
          )
          .optional(),
        binary_output_format: z
          .string()
          .describe('Output format for binary values.')
          .optional(),
        date_output_format: z
          .string()
          .describe('Output format for DATE values.')
          .optional(),
        time_output_format: z
          .string()
          .describe('Output format for TIME values.')
          .optional(),
        timestamp_output_format: z
          .string()
          .describe('Output format for TIMESTAMP values.')
          .optional(),
        timestamp_ltz_output_format: z
          .string()
          .describe('Output format for TIMESTAMP_LTZ values.')
          .optional(),
        timestamp_ntz_output_format: z
          .string()
          .describe('Output format for TIMESTAMP_NTZ values.')
          .optional(),
        timestamp_tz_output_format: z
          .string()
          .describe('Output format for TIMESTAMP_TZ values.')
          .optional(),
        multi_statement_count: z
          .number()
          .int()
          .describe(
            'Number of statements to execute when using multi-statement capability. 0 implies variable number of statements. Negative numbers are not allowed.'
          )
          .optional(),
      })
      .describe(
        'Session parameters that should be set before executing the statement.'
      )
      .optional(),
    requestId: z
      .string()
      .uuid()
      .describe(
        'Unique ID of the API request. This ensures that the execution is idempotent. If not specified, a new UUID is generated and assigned.'
      )
      .optional(),
    async: z
      .boolean()
      .describe(
        'Set to true to execute the statement asynchronously and return the statement handle. If the parameter is not specified or is set to false, a statement is executed and the first result is returned if the execution is completed in 45 seconds. If the statement execution takes longer to complete, the statement handle is returned.'
      )
      .optional(),
    nullable: z
      .boolean()
      .describe(
        "Set to true to execute the statement to generate the result set including null. If the parameter is set to false, the result set value null will be replaced with a string 'null'."
      )
      .optional(),
    credentials: BaseCredentialsSchema,
  }),
  z.object({
    operation: z
      .literal('get_statement_status')
      .describe('Checks the status of the execution of a statement'),
    accountUrl: z
      .string()
      .url()
      .describe(
        'Per-account Snowflake base URL (e.g. https://org-account.snowflakecomputing.com)'
      ),
    statementHandle: z
      .string()
      .uuid()
      .describe(
        'The handle of the statement that you want to use (e.g. to fetch the result set or cancel execution).'
      ),
    requestId: z
      .string()
      .uuid()
      .describe(
        'Unique ID of the API request. This ensures that the execution is idempotent. If not specified, a new UUID is generated and assigned.'
      )
      .optional(),
    partition: z
      .number()
      .int()
      .min(0)
      .describe(
        'Number of the partition of results to return. The number can range from 0 to the total number of partitions minus 1.'
      )
      .optional(),
    credentials: BaseCredentialsSchema,
  }),
  z.object({
    operation: z
      .literal('cancel_statement')
      .describe('Cancels the execution of a statement.'),
    accountUrl: z
      .string()
      .url()
      .describe(
        'Per-account Snowflake base URL (e.g. https://org-account.snowflakecomputing.com)'
      ),
    statementHandle: z
      .string()
      .uuid()
      .describe(
        'The handle of the statement that you want to use (e.g. to fetch the result set or cancel execution).'
      ),
    requestId: z
      .string()
      .uuid()
      .describe(
        'Unique ID of the API request. This ensures that the execution is idempotent. If not specified, a new UUID is generated and assigned.'
      )
      .optional(),
    credentials: BaseCredentialsSchema,
  }),
]);

export const SnowflakeSqlApiResultSchema = z.discriminatedUnion('operation', [
  z
    .object({
      operation: z.literal('submit_statement'),
      success: z.boolean().describe('Whether the operation succeeded'),
      error: z.string().describe('Error message if operation failed'),
    })
    .merge(SubmitStatementPayloadSchema),
  z
    .object({
      operation: z.literal('get_statement_status'),
      success: z.boolean().describe('Whether the operation succeeded'),
      error: z.string().describe('Error message if operation failed'),
    })
    .merge(GetStatementStatusPayloadSchema),
  z
    .object({
      operation: z.literal('cancel_statement'),
      success: z.boolean().describe('Whether the operation succeeded'),
      error: z.string().describe('Error message if operation failed'),
    })
    .merge(CancelStatementPayloadSchema),
]);

export type SnowflakeSqlApiParamsInput = z.input<
  typeof SnowflakeSqlApiParamsSchema
>;
export type SnowflakeSqlApiParams = z.output<
  typeof SnowflakeSqlApiParamsSchema
>;
export type SnowflakeSqlApiResult = z.output<
  typeof SnowflakeSqlApiResultSchema
>;

export type SnowflakeSqlApiSubmitStatementParams = Extract<
  SnowflakeSqlApiParamsInput,
  { operation: 'submit_statement' }
>;
export type SnowflakeSqlApiGetStatementStatusParams = Extract<
  SnowflakeSqlApiParamsInput,
  { operation: 'get_statement_status' }
>;
export type SnowflakeSqlApiCancelStatementParams = Extract<
  SnowflakeSqlApiParamsInput,
  { operation: 'cancel_statement' }
>;

export type SnowflakeSqlApiOperationResult<
  T extends SnowflakeSqlApiParams['operation'],
> = Extract<SnowflakeSqlApiResult, { operation: T }>;
