/**
 * Doc-grounded per-operation side-effect metadata (IR-8) for the 'snowflake-sql-api' bubble.
 *
 * GENERATED by @bubblelab/bubble-appgen from sqlapi.yaml — do not hand-edit;
 * re-run `pnpm --filter @bubblelab/bubble-appgen generate:snowflake-sql-api` instead.
 * Vendor docs: https://docs.snowflake.com/en/developer-guide/sql-api/intro
 */

import type { BubbleOperationMetadata } from '@bubblelab/shared-schemas';

export const SNOWFLAKE_SQL_API_OPERATION_METADATA: BubbleOperationMetadata = {
  submit_statement: {
    sideEffect: 'write',
    destructive: false,
    idempotent: false,
    confidence: 0.85,
    source: 'openapi',
    citation:
      'sqlapi.yaml#/paths/~1api~1v2~1statements/post — "Submits a SQL statement for execution." — carrier operation: executes caller-supplied SQL; fail-safe write until statement-level verb refinement is applied',
  },
  get_statement_status: {
    sideEffect: 'read_with_side_effects',
    destructive: false,
    idempotent: true,
    confidence: 0.85,
    source: 'openapi',
    citation:
      'sqlapi.yaml#/paths/~1api~1v2~1statements~1{statementHandle}/get — "Checks the status of the execution of a statement"',
  },
  cancel_statement: {
    sideEffect: 'write',
    destructive: false,
    idempotent: false,
    confidence: 0.2,
    source: 'openapi',
    citation:
      'sqlapi.yaml#/paths/~1api~1v2~1statements~1{statementHandle}~1cancel/post — no doc signal in "Cancels the execution of a statement."; fail-safe write pending human review',
    unverified: true,
  },
};
