/**
 * Schema round-trip tests (fixtures = the examples shipped inside the vendor spec) for the 'snowflake-sql-api' bubble.
 *
 * GENERATED by @bubblelab/bubble-appgen from sqlapi.yaml — do not hand-edit;
 * re-run `pnpm --filter @bubblelab/bubble-appgen generate:snowflake-sql-api` instead.
 * Vendor docs: https://docs.snowflake.com/en/developer-guide/sql-api/intro
 */

import { describe, expect, it } from 'vitest';
import {
  SnowflakeSqlApiParamsSchema,
  SnowflakeSqlApiResultSchema,
} from './snowflake-sql-api.schema.js';
import { SNOWFLAKE_SQL_API_OPERATION_METADATA } from './snowflake-sql-api.metadata.js';

describe('snowflake-sql-api generated contract', () => {
  it('submit_statement: accepts a spec-example request', () => {
    const result = SnowflakeSqlApiParamsSchema.safeParse({
      operation: 'submit_statement',
      accountUrl: 'https://org-account.snowflakecomputing.com',
      statement: 'select * from T where c1=?',
      timeout: 10,
      database: 'TESTDB',
      schema: 'TESTSCHEMA',
      warehouse: 'TESTWH',
      bindings: { '1': { type: 'FIXED', value: '123' } },
    });
    expect(result.success).toBe(true);
  });

  it('submit_statement: rejects a type-corrupted request (requestId: number)', () => {
    const result = SnowflakeSqlApiParamsSchema.safeParse({
      operation: 'submit_statement',
      accountUrl: 'https://org-account.snowflakecomputing.com',
      statement: 'select * from T where c1=?',
      timeout: 10,
      database: 'TESTDB',
      schema: 'TESTSCHEMA',
      warehouse: 'TESTWH',
      bindings: { '1': { type: 'FIXED', value: '123' } },
      requestId: 12345,
    });
    expect(result.success).toBe(false);
  });

  it('submit_statement: spec 202-response example parses through the result schema', () => {
    const result = SnowflakeSqlApiResultSchema.safeParse({
      operation: 'submit_statement',
      success: true,
      error: '',
      code: '000000',
      sqlState: '00000',
      message: 'successfully executed',
      statementHandle: 'e4ce975e-f7ff-4b5e-b15e-bf25f59371ae',
      createdOn: 1597090533987,
    });
    expect(result.success).toBe(true);
  });

  it('get_statement_status: accepts a spec-example request', () => {
    const result = SnowflakeSqlApiParamsSchema.safeParse({
      operation: 'get_statement_status',
      accountUrl: 'https://org-account.snowflakecomputing.com',
      statementHandle: 'e4ce975e-f7ff-4b5e-b15e-bf25f59371ae',
    });
    expect(result.success).toBe(true);
  });

  it('get_statement_status: rejects a type-corrupted request (statementHandle: number)', () => {
    const result = SnowflakeSqlApiParamsSchema.safeParse({
      operation: 'get_statement_status',
      accountUrl: 'https://org-account.snowflakecomputing.com',
      statementHandle: 12345,
    });
    expect(result.success).toBe(false);
  });

  it('get_statement_status: spec 202-response example parses through the result schema', () => {
    const result = SnowflakeSqlApiResultSchema.safeParse({
      operation: 'get_statement_status',
      success: true,
      error: '',
      code: '000000',
      sqlState: '00000',
      message: 'successfully executed',
      statementHandle: 'e4ce975e-f7ff-4b5e-b15e-bf25f59371ae',
      createdOn: 1597090533987,
    });
    expect(result.success).toBe(true);
  });

  it('cancel_statement: accepts a spec-example request', () => {
    const result = SnowflakeSqlApiParamsSchema.safeParse({
      operation: 'cancel_statement',
      accountUrl: 'https://org-account.snowflakecomputing.com',
      statementHandle: 'e4ce975e-f7ff-4b5e-b15e-bf25f59371ae',
    });
    expect(result.success).toBe(true);
  });

  it('cancel_statement: rejects a type-corrupted request (statementHandle: number)', () => {
    const result = SnowflakeSqlApiParamsSchema.safeParse({
      operation: 'cancel_statement',
      accountUrl: 'https://org-account.snowflakecomputing.com',
      statementHandle: 12345,
    });
    expect(result.success).toBe(false);
  });

  it('cancel_statement: spec 200-response example parses through the result schema', () => {
    const result = SnowflakeSqlApiResultSchema.safeParse({
      operation: 'cancel_statement',
      success: true,
      error: '',
      message: 'successfully canceled',
      statementHandle: '536fad38-b564-4dc5-9892-a4543504df6c',
    });
    expect(result.success).toBe(true);
  });

  it('rejects requests missing the required accountUrl', () => {
    const result = SnowflakeSqlApiParamsSchema.safeParse({
      operation: 'submit_statement',
    });
    expect(result.success).toBe(false);
  });

  it('rejects unknown operations', () => {
    const result = SnowflakeSqlApiParamsSchema.safeParse({
      operation: 'not_a_real_operation',
    });
    expect(result.success).toBe(false);
  });

  it('every schema operation has cited side-effect metadata (coverage guard)', () => {
    const operations = SnowflakeSqlApiParamsSchema.options.map(
      (option) => option.shape.operation.value
    );
    for (const operation of operations) {
      const entry = SNOWFLAKE_SQL_API_OPERATION_METADATA[operation];
      expect(entry, `missing metadata for ${operation}`).toBeDefined();
      expect(entry.citation.length).toBeGreaterThan(0);
      expect(entry.source.length).toBeGreaterThan(0);
    }
  });
});
