/**
 * Proof of concept for BACKFILL-METHOD.md §7.1: doc prose → side-effect hint on ONE real
 * operation, using the shipped classifier (no mocks, no HTTP method as signal).
 *
 * Operation: Databricks cluster events. The HTTP verb is POST (verified:
 * databricks-sdk-go/service/compute/impl.go sends http.MethodPost to /api/2.1/clusters/events),
 * but the vendor prose says it retrieves. Doc-grounded classification yields `read`;
 * method-based classification would have wrongly yielded `write`.
 *
 * Run from the repo root (tsx erases the classifier's type-only imports, so no build needed):
 *   pnpm tsx docs/plan/poc/classify-real-operation.ts
 *
 * Expected output:
 *   {
 *     "sideEffect": "read",
 *     "destructive": false,
 *     "idempotent": true,
 *     "confidence": 0.6,
 *     "source": "prose",
 *     "citation": "https://docs.databricks.com/api/workspace/clusters/events — \"Retrieves a list of events about the activity of a cluster. This API is paginated.\" (prose from databricks-sdk-go service/compute/api.go, generated by Databricks SDK Code Generator)"
 *   }
 */
import {
  classifySideEffect,
  type DocProseEvidence,
} from '../../../packages/bubble-core/src/utils/side-effect-classifier.js';

// The vendor's own operation prose, quoted verbatim from the official SDK docstring
// (databricks-sdk-go service/compute/api.go; the docs site is SPA-rendered and unfetchable).
const evidence: DocProseEvidence = {
  kind: 'prose',
  docText:
    'Retrieves a list of events about the activity of a cluster. This API is paginated. ' +
    'If there are more events to read, the response includes all the parameters necessary ' +
    'to request the next page of events.',
  citation:
    'https://docs.databricks.com/api/workspace/clusters/events — "Retrieves a list of events ' +
    'about the activity of a cluster. This API is paginated." (prose from databricks-sdk-go ' +
    'service/compute/api.go, generated by Databricks SDK Code Generator)',
};

const metadata = classifySideEffect([evidence]);

console.log('Operation: databricks cluster_events (HTTP verb: POST /api/2.1/clusters/events)');
console.log(JSON.stringify(metadata, null, 2));

if (metadata.sideEffect !== 'read') {
  throw new Error(
    `expected 'read' (a POST that only reads), got '${metadata.sideEffect}'`
  );
}
console.log(
  'PASS: POST-that-reads classified as read from vendor prose; the HTTP method was never consulted.'
);
