/**
 * Public exports for the 'kraken-spot-api' bubble.
 *
 * GENERATED by @bubblelab/bubble-appgen from kraken-spot.yaml — do not hand-edit;
 * re-run `pnpm --filter @bubblelab/bubble-appgen generate:kraken-spot-api` instead.
 * Vendor docs: https://docs.kraken.com/api/docs/guides/spot-rest-intro/
 */

export { KrakenSpotApiBubble } from './kraken-spot-api.js';
export { KRAKEN_SPOT_API_OPERATION_METADATA } from './kraken-spot-api.metadata.js';
export {
  KrakenSpotApiParamsSchema,
  KrakenSpotApiResultSchema,
  type KrakenSpotApiParams,
  type KrakenSpotApiResult,
  type KrakenSpotApiParamsInput,
} from './kraken-spot-api.schema.js';
