/**
 * Schema round-trip tests (fixtures = the examples shipped inside the vendor spec) for the 'kraken-spot-api' bubble.
 *
 * GENERATED by @bubblelab/bubble-appgen from kraken-spot.yaml — do not hand-edit;
 * re-run `pnpm --filter @bubblelab/bubble-appgen generate:kraken-spot-api` instead.
 * Vendor docs: https://docs.kraken.com/api/docs/guides/spot-rest-intro/
 */

import { describe, expect, it } from 'vitest';
import {
  KrakenSpotApiParamsSchema,
  KrakenSpotApiResultSchema,
} from './kraken-spot-api.schema.js';
import { KRAKEN_SPOT_API_OPERATION_METADATA } from './kraken-spot-api.metadata.js';

describe('kraken-spot-api generated contract', () => {
  it('get_ticker_information: accepts a spec-example request', () => {
    const result = KrakenSpotApiParamsSchema.safeParse({
      operation: 'get_ticker_information',
      baseUrl: 'https://api.kraken.com/0',
    });
    expect(result.success).toBe(true);
  });

  it('get_ticker_information: rejects a type-corrupted request (pair: number)', () => {
    const result = KrakenSpotApiParamsSchema.safeParse({
      operation: 'get_ticker_information',
      baseUrl: 'https://api.kraken.com/0',
      pair: 12345,
    });
    expect(result.success).toBe(false);
  });

  it('get_ohlc_data: accepts a spec-example request', () => {
    const result = KrakenSpotApiParamsSchema.safeParse({
      operation: 'get_ohlc_data',
      baseUrl: 'https://api.kraken.com/0',
      pair: 'example',
    });
    expect(result.success).toBe(true);
  });

  it('get_ohlc_data: rejects a type-corrupted request (pair: number)', () => {
    const result = KrakenSpotApiParamsSchema.safeParse({
      operation: 'get_ohlc_data',
      baseUrl: 'https://api.kraken.com/0',
      pair: 12345,
    });
    expect(result.success).toBe(false);
  });

  it('get_order_book: accepts a spec-example request', () => {
    const result = KrakenSpotApiParamsSchema.safeParse({
      operation: 'get_order_book',
      baseUrl: 'https://api.kraken.com/0',
      pair: 'example',
    });
    expect(result.success).toBe(true);
  });

  it('get_order_book: rejects a type-corrupted request (pair: number)', () => {
    const result = KrakenSpotApiParamsSchema.safeParse({
      operation: 'get_order_book',
      baseUrl: 'https://api.kraken.com/0',
      pair: 12345,
    });
    expect(result.success).toBe(false);
  });

  it('get_recent_trades: accepts a spec-example request', () => {
    const result = KrakenSpotApiParamsSchema.safeParse({
      operation: 'get_recent_trades',
      baseUrl: 'https://api.kraken.com/0',
      pair: 'example',
    });
    expect(result.success).toBe(true);
  });

  it('get_recent_trades: rejects a type-corrupted request (pair: number)', () => {
    const result = KrakenSpotApiParamsSchema.safeParse({
      operation: 'get_recent_trades',
      baseUrl: 'https://api.kraken.com/0',
      pair: 12345,
    });
    expect(result.success).toBe(false);
  });

  it('get_system_status: accepts a spec-example request', () => {
    const result = KrakenSpotApiParamsSchema.safeParse({
      operation: 'get_system_status',
      baseUrl: 'https://api.kraken.com/0',
    });
    expect(result.success).toBe(true);
  });

  it('get_server_time: accepts a spec-example request', () => {
    const result = KrakenSpotApiParamsSchema.safeParse({
      operation: 'get_server_time',
      baseUrl: 'https://api.kraken.com/0',
    });
    expect(result.success).toBe(true);
  });

  it('rejects requests missing the required baseUrl', () => {
    const result = KrakenSpotApiParamsSchema.safeParse({
      operation: 'get_ticker_information',
    });
    expect(result.success).toBe(false);
  });

  it('rejects unknown operations', () => {
    const result = KrakenSpotApiParamsSchema.safeParse({
      operation: 'not_a_real_operation',
    });
    expect(result.success).toBe(false);
  });

  it('every schema operation has cited side-effect metadata (coverage guard)', () => {
    const operations = KrakenSpotApiParamsSchema.options.map(
      (option) => option.shape.operation.value
    );
    for (const operation of operations) {
      const entry = KRAKEN_SPOT_API_OPERATION_METADATA[operation];
      expect(entry, `missing metadata for ${operation}`).toBeDefined();
      expect(entry.citation.length).toBeGreaterThan(0);
      expect(entry.source.length).toBeGreaterThan(0);
    }
  });
});
