/**
 * ServiceBubble class (raw-fetch pattern) for the 'kraken-spot-api' bubble.
 *
 * GENERATED by @bubblelab/bubble-appgen from kraken-spot.yaml — do not hand-edit;
 * re-run `pnpm --filter @bubblelab/bubble-appgen generate:kraken-spot-api` instead.
 * Vendor docs: https://docs.kraken.com/api/docs/guides/spot-rest-intro/
 */

import { ServiceBubble } from '../../../types/service-bubble-class.js';
import type { BubbleContext } from '../../../types/bubble.js';
import { CredentialType } from '@bubblelab/shared-schemas';
import { KRAKEN_SPOT_API_OPERATION_METADATA } from './kraken-spot-api.metadata.js';
import {
  KrakenSpotApiParamsSchema,
  KrakenSpotApiResultSchema,
  GetTickerInformationPayloadSchema,
  GetOhlcDataPayloadSchema,
  GetOrderBookPayloadSchema,
  GetRecentTradesPayloadSchema,
  GetSystemStatusPayloadSchema,
  GetServerTimePayloadSchema,
  type KrakenSpotApiParams,
  type KrakenSpotApiParamsInput,
  type KrakenSpotApiResult,
} from './kraken-spot-api.schema.js';

/** Strip a trailing slash so path concatenation stays canonical. */
function trimBaseUrl(url: string): string {
  return url.endsWith('/') ? url.slice(0, -1) : url;
}

/** Serialize defined query params; returns '' or '?k=v&…'. */
function buildQuery(
  params: Record<string, string | number | boolean | undefined>
): string {
  const search = new URLSearchParams();
  for (const [key, value] of Object.entries(params)) {
    if (value !== undefined) search.set(key, String(value));
  }
  const qs = search.toString();
  return qs.length > 0 ? `?${qs}` : '';
}

export class KrakenSpotApiBubble<
  T extends KrakenSpotApiParamsInput = KrakenSpotApiParamsInput,
> extends ServiceBubble<
  T,
  Extract<KrakenSpotApiResult, { operation: T['operation'] }>
> {
  static readonly type = 'service' as const;
  static readonly service = 'kraken';
  static readonly authType = 'apikey' as const;
  static readonly bubbleName = 'kraken-spot-api';
  static readonly operationMetadata = KRAKEN_SPOT_API_OPERATION_METADATA;
  static readonly schema = KrakenSpotApiParamsSchema;
  static readonly resultSchema = KrakenSpotApiResultSchema;
  static readonly shortDescription =
    'Kraken Spot REST API public market-data integration generated from the official OpenAPI spec (ticker, OHLC candles, order book, recent trades, system status, server time)';
  static readonly longDescription = `
    Kraken Spot REST API public market-data integration generated from the official OpenAPI spec (ticker, OHLC candles, order book, recent trades, system status, server time)

    Operations (generated from the vendor OpenAPI spec):
    - get_ticker_information [side-effect: read]: Get Ticker Information
    - get_ohlc_data [side-effect: read]: Get OHLC Data
    - get_order_book [side-effect: read]: Get Order Book
    - get_recent_trades [side-effect: read]: Get Recent Trades
    - get_system_status [side-effect: read]: Get System Status
    - get_server_time [side-effect: read]: Get Server Time

    Credential: KRAKEN_API_KEY (bearer token) + per-account baseUrl.
  `;
  static readonly alias = 'kraken-md';

  constructor(
    params: T = {
      operation: 'get_ticker_information',
      baseUrl: 'https://api.kraken.com/0',
    } as T,
    context?: BubbleContext
  ) {
    super(params, context);
  }

  private requestHeaders(
    token: string,
    hasBody: boolean
  ): Record<string, string> {
    const headers: Record<string, string> = {
      Authorization: `Bearer ${token}`,
      Accept: 'application/json',
      'User-Agent': 'bubblelab/1.0',
    };
    if (hasBody) headers['Content-Type'] = 'application/json';
    return headers;
  }

  public async testCredential(): Promise<boolean> {
    const token = this.chooseCredential();
    if (!token) {
      throw new Error('kraken-spot-api credentials are required');
    }
    const params = { baseUrl: this.params.baseUrl };
    // Probe: GET /public/Ticker (get_ticker_information) with a synthesized handle.
    // 401/403 mean the credential was rejected; any other status means it was accepted.
    const response = await fetch(
      `${trimBaseUrl(params.baseUrl)}/public/Ticker`,
      {
        method: 'GET',
        headers: this.requestHeaders(token, false),
      }
    );
    return response.status !== 401 && response.status !== 403;
  }

  protected chooseCredential(): string | undefined {
    const credentials = this.params.credentials;
    if (!credentials || typeof credentials !== 'object') {
      return undefined;
    }
    return credentials[CredentialType.KRAKEN_API_KEY];
  }

  protected async performAction(
    context?: BubbleContext
  ): Promise<Extract<KrakenSpotApiResult, { operation: T['operation'] }>> {
    void context;
    const { operation } = this.params;
    switch (operation) {
      case 'get_ticker_information':
        return this.handleGetTickerInformation() as Promise<
          Extract<KrakenSpotApiResult, { operation: T['operation'] }>
        >;
      case 'get_ohlc_data':
        return this.handleGetOhlcData() as Promise<
          Extract<KrakenSpotApiResult, { operation: T['operation'] }>
        >;
      case 'get_order_book':
        return this.handleGetOrderBook() as Promise<
          Extract<KrakenSpotApiResult, { operation: T['operation'] }>
        >;
      case 'get_recent_trades':
        return this.handleGetRecentTrades() as Promise<
          Extract<KrakenSpotApiResult, { operation: T['operation'] }>
        >;
      case 'get_system_status':
        return this.handleGetSystemStatus() as Promise<
          Extract<KrakenSpotApiResult, { operation: T['operation'] }>
        >;
      case 'get_server_time':
        return this.handleGetServerTime() as Promise<
          Extract<KrakenSpotApiResult, { operation: T['operation'] }>
        >;
      default:
        return {
          operation: operation as T['operation'],
          success: false,
          error: `Unknown operation: ${String(operation)}`,
        } as Extract<KrakenSpotApiResult, { operation: T['operation'] }>;
    }
  }

  private async handleGetTickerInformation(): Promise<
    Extract<KrakenSpotApiResult, { operation: 'get_ticker_information' }>
  > {
    const params = KrakenSpotApiParamsSchema.parse(this.params) as Extract<
      KrakenSpotApiParams,
      { operation: 'get_ticker_information' }
    >;
    try {
      const token = this.chooseCredential();
      if (!token) {
        return {
          operation: 'get_ticker_information',
          success: false,
          error: 'KRAKEN_API_KEY credential not found',
        };
      }
      const query = buildQuery({
        pair: params.pair,
      });
      const url = `${trimBaseUrl(params.baseUrl)}/public/Ticker${query}`;
      const response = await fetch(url, {
        method: 'GET',
        headers: this.requestHeaders(token, false),
      });
      if (!response.ok) {
        const errorText = await response.text();
        return {
          operation: 'get_ticker_information',
          success: false,
          error: `kraken-spot-api API error (${response.status}): ${errorText}`,
        };
      }
      const payload = GetTickerInformationPayloadSchema.parse(
        await response.json()
      );
      return {
        operation: 'get_ticker_information',
        success: true,
        error: '',
        ...payload,
      };
    } catch (error) {
      return {
        operation: 'get_ticker_information',
        success: false,
        error:
          error instanceof Error ? error.message : 'Unknown error occurred',
      };
    }
  }

  private async handleGetOhlcData(): Promise<
    Extract<KrakenSpotApiResult, { operation: 'get_ohlc_data' }>
  > {
    const params = KrakenSpotApiParamsSchema.parse(this.params) as Extract<
      KrakenSpotApiParams,
      { operation: 'get_ohlc_data' }
    >;
    try {
      const token = this.chooseCredential();
      if (!token) {
        return {
          operation: 'get_ohlc_data',
          success: false,
          error: 'KRAKEN_API_KEY credential not found',
        };
      }
      const query = buildQuery({
        pair: params.pair,
        interval: params.interval,
        since: params.since,
      });
      const url = `${trimBaseUrl(params.baseUrl)}/public/OHLC${query}`;
      const response = await fetch(url, {
        method: 'GET',
        headers: this.requestHeaders(token, false),
      });
      if (!response.ok) {
        const errorText = await response.text();
        return {
          operation: 'get_ohlc_data',
          success: false,
          error: `kraken-spot-api API error (${response.status}): ${errorText}`,
        };
      }
      const payload = GetOhlcDataPayloadSchema.parse(await response.json());
      return {
        operation: 'get_ohlc_data',
        success: true,
        error: '',
        ...payload,
      };
    } catch (error) {
      return {
        operation: 'get_ohlc_data',
        success: false,
        error:
          error instanceof Error ? error.message : 'Unknown error occurred',
      };
    }
  }

  private async handleGetOrderBook(): Promise<
    Extract<KrakenSpotApiResult, { operation: 'get_order_book' }>
  > {
    const params = KrakenSpotApiParamsSchema.parse(this.params) as Extract<
      KrakenSpotApiParams,
      { operation: 'get_order_book' }
    >;
    try {
      const token = this.chooseCredential();
      if (!token) {
        return {
          operation: 'get_order_book',
          success: false,
          error: 'KRAKEN_API_KEY credential not found',
        };
      }
      const query = buildQuery({
        pair: params.pair,
        count: params.count,
      });
      const url = `${trimBaseUrl(params.baseUrl)}/public/Depth${query}`;
      const response = await fetch(url, {
        method: 'GET',
        headers: this.requestHeaders(token, false),
      });
      if (!response.ok) {
        const errorText = await response.text();
        return {
          operation: 'get_order_book',
          success: false,
          error: `kraken-spot-api API error (${response.status}): ${errorText}`,
        };
      }
      const payload = GetOrderBookPayloadSchema.parse(await response.json());
      return {
        operation: 'get_order_book',
        success: true,
        error: '',
        ...payload,
      };
    } catch (error) {
      return {
        operation: 'get_order_book',
        success: false,
        error:
          error instanceof Error ? error.message : 'Unknown error occurred',
      };
    }
  }

  private async handleGetRecentTrades(): Promise<
    Extract<KrakenSpotApiResult, { operation: 'get_recent_trades' }>
  > {
    const params = KrakenSpotApiParamsSchema.parse(this.params) as Extract<
      KrakenSpotApiParams,
      { operation: 'get_recent_trades' }
    >;
    try {
      const token = this.chooseCredential();
      if (!token) {
        return {
          operation: 'get_recent_trades',
          success: false,
          error: 'KRAKEN_API_KEY credential not found',
        };
      }
      const query = buildQuery({
        pair: params.pair,
        since: params.since,
        count: params.count,
      });
      const url = `${trimBaseUrl(params.baseUrl)}/public/Trades${query}`;
      const response = await fetch(url, {
        method: 'GET',
        headers: this.requestHeaders(token, false),
      });
      if (!response.ok) {
        const errorText = await response.text();
        return {
          operation: 'get_recent_trades',
          success: false,
          error: `kraken-spot-api API error (${response.status}): ${errorText}`,
        };
      }
      const payload = GetRecentTradesPayloadSchema.parse(await response.json());
      return {
        operation: 'get_recent_trades',
        success: true,
        error: '',
        ...payload,
      };
    } catch (error) {
      return {
        operation: 'get_recent_trades',
        success: false,
        error:
          error instanceof Error ? error.message : 'Unknown error occurred',
      };
    }
  }

  private async handleGetSystemStatus(): Promise<
    Extract<KrakenSpotApiResult, { operation: 'get_system_status' }>
  > {
    const params = KrakenSpotApiParamsSchema.parse(this.params) as Extract<
      KrakenSpotApiParams,
      { operation: 'get_system_status' }
    >;
    try {
      const token = this.chooseCredential();
      if (!token) {
        return {
          operation: 'get_system_status',
          success: false,
          error: 'KRAKEN_API_KEY credential not found',
        };
      }
      const url = `${trimBaseUrl(params.baseUrl)}/public/SystemStatus`;
      const response = await fetch(url, {
        method: 'GET',
        headers: this.requestHeaders(token, false),
      });
      if (!response.ok) {
        const errorText = await response.text();
        return {
          operation: 'get_system_status',
          success: false,
          error: `kraken-spot-api API error (${response.status}): ${errorText}`,
        };
      }
      const payload = GetSystemStatusPayloadSchema.parse(await response.json());
      return {
        operation: 'get_system_status',
        success: true,
        error: '',
        ...payload,
      };
    } catch (error) {
      return {
        operation: 'get_system_status',
        success: false,
        error:
          error instanceof Error ? error.message : 'Unknown error occurred',
      };
    }
  }

  private async handleGetServerTime(): Promise<
    Extract<KrakenSpotApiResult, { operation: 'get_server_time' }>
  > {
    const params = KrakenSpotApiParamsSchema.parse(this.params) as Extract<
      KrakenSpotApiParams,
      { operation: 'get_server_time' }
    >;
    try {
      const token = this.chooseCredential();
      if (!token) {
        return {
          operation: 'get_server_time',
          success: false,
          error: 'KRAKEN_API_KEY credential not found',
        };
      }
      const url = `${trimBaseUrl(params.baseUrl)}/public/Time`;
      const response = await fetch(url, {
        method: 'GET',
        headers: this.requestHeaders(token, false),
      });
      if (!response.ok) {
        const errorText = await response.text();
        return {
          operation: 'get_server_time',
          success: false,
          error: `kraken-spot-api API error (${response.status}): ${errorText}`,
        };
      }
      const payload = GetServerTimePayloadSchema.parse(await response.json());
      return {
        operation: 'get_server_time',
        success: true,
        error: '',
        ...payload,
      };
    } catch (error) {
      return {
        operation: 'get_server_time',
        success: false,
        error:
          error instanceof Error ? error.message : 'Unknown error occurred',
      };
    }
  }
}
