/**
 * Doc-grounded per-operation side-effect metadata (IR-8) for the 'kraken-spot-api' bubble.
 *
 * GENERATED by @bubblelab/bubble-appgen from kraken-spot.yaml — do not hand-edit;
 * re-run `pnpm --filter @bubblelab/bubble-appgen generate:kraken-spot-api` instead.
 * Vendor docs: https://docs.kraken.com/api/docs/guides/spot-rest-intro/
 */

import type { BubbleOperationMetadata } from '@bubblelab/shared-schemas';

export const KRAKEN_SPOT_API_OPERATION_METADATA: BubbleOperationMetadata = {
  get_ticker_information: {
    sideEffect: 'read',
    destructive: false,
    idempotent: true,
    confidence: 0.85,
    source: 'openapi',
    citation:
      'kraken-spot.yaml#/paths/~1public~1Ticker/get — "Get Ticker Information"',
  },
  get_ohlc_data: {
    sideEffect: 'read',
    destructive: false,
    idempotent: true,
    confidence: 0.85,
    source: 'openapi',
    citation: 'kraken-spot.yaml#/paths/~1public~1OHLC/get — "Get OHLC Data"',
  },
  get_order_book: {
    sideEffect: 'read',
    destructive: false,
    idempotent: true,
    confidence: 0.85,
    source: 'openapi',
    citation: 'kraken-spot.yaml#/paths/~1public~1Depth/get — "Get Order Book"',
  },
  get_recent_trades: {
    sideEffect: 'read',
    destructive: false,
    idempotent: true,
    confidence: 0.85,
    source: 'openapi',
    citation:
      'kraken-spot.yaml#/paths/~1public~1Trades/get — "Get Recent Trades"',
  },
  get_system_status: {
    sideEffect: 'read',
    destructive: false,
    idempotent: true,
    confidence: 0.85,
    source: 'openapi',
    citation:
      'kraken-spot.yaml#/paths/~1public~1SystemStatus/get — "Get System Status"',
  },
  get_server_time: {
    sideEffect: 'read',
    destructive: false,
    idempotent: true,
    confidence: 0.85,
    source: 'openapi',
    citation: 'kraken-spot.yaml#/paths/~1public~1Time/get — "Get Server Time"',
  },
};
