/**
 * Zod contract (params + results) for the 'kraken-spot-api' bubble.
 *
 * GENERATED by @bubblelab/bubble-appgen from kraken-spot.yaml — do not hand-edit;
 * re-run `pnpm --filter @bubblelab/bubble-appgen generate:kraken-spot-api` instead.
 * Vendor docs: https://docs.kraken.com/api/docs/guides/spot-rest-intro/
 */

import { z } from 'zod';
import { CredentialType } from '@bubblelab/shared-schemas';

// Base credentials schema shared by every operation branch
const BaseCredentialsSchema = z
  .record(z.nativeEnum(CredentialType), z.string())
  .optional()
  .describe('Object mapping credential types to values (injected at runtime)');

/** Documented 2xx response payload of getTickerInformation (statuses: 200); all fields optional because presence varies by status code. */
export const GetTickerInformationPayloadSchema = z.object({
  result: z
    .record(
      z.string(),
      z
        .object({
          a: z
            .array(z.string())
            .describe('Ask `[<price>, <whole lot volume>, <lot volume>]`')
            .optional(),
          b: z
            .array(z.string())
            .describe('Bid `[<price>, <whole lot volume>, <lot volume>]`')
            .optional(),
          c: z
            .array(z.string())
            .describe('Last trade closed `[<price>, <lot volume>]`')
            .optional(),
          v: z
            .array(z.string())
            .describe('Volume `[<today>, <last 24 hours>]`')
            .optional(),
          p: z
            .array(z.string())
            .describe(
              'Volume weighted average price `[<today>, <last 24 hours>]`'
            )
            .optional(),
          t: z
            .array(z.number().int())
            .describe('Number of trades `[<today>, <last 24 hours>]`')
            .optional(),
          l: z
            .array(z.string())
            .describe('Low `[<today>, <last 24 hours>]`')
            .optional(),
          h: z
            .array(z.string())
            .describe('High `[<today>, <last 24 hours>]`')
            .optional(),
          o: z.string().describe("Today's opening price").optional(),
        })
        .describe('Asset Ticker Info')
    )
    .optional(),
});

/** Documented 2xx response payload of getOhlcData (statuses: 200); all fields optional because presence varies by status code. */
export const GetOhlcDataPayloadSchema = z.object({
  result: z
    .object({
      last: z
        .number()
        .int()
        .describe(
          'ID to be used as since when polling for new, committed OHLC data'
        )
        .optional(),
    })
    .optional(),
});

/** Documented 2xx response payload of getOrderBook (statuses: 200); all fields optional because presence varies by status code. */
export const GetOrderBookPayloadSchema = z.object({
  result: z
    .record(
      z.string(),
      z
        .object({
          asks: z
            .array(z.array(z.union([z.string(), z.number().int()])))
            .describe(
              'Ask side array of entries `[<price>, <volume>, <timestamp>]`'
            )
            .optional(),
          bids: z
            .array(z.array(z.union([z.string(), z.number().int()])))
            .describe(
              'Bid side array of entries `[<price>, <volume>, <timestamp>]`'
            )
            .optional(),
        })
        .describe('Asset Pair Order Book Entries')
    )
    .optional(),
});

/** Documented 2xx response payload of getRecentTrades (statuses: 200); all fields optional because presence varies by status code. */
export const GetRecentTradesPayloadSchema = z.object({
  result: z
    .object({
      last: z
        .string()
        .describe('ID to be used as since when polling for new trade data')
        .optional(),
    })
    .optional(),
});

/** Documented 2xx response payload of getSystemStatus (statuses: 200); all fields optional because presence varies by status code. */
export const GetSystemStatusPayloadSchema = z.object({
  result: z
    .object({
      status: z
        .enum(['online', 'maintenance', 'cancel_only', 'post_only'])
        .describe(
          'Current system status: * `online` Kraken is operating normally. All order types may be submitted and trades can occur. * `maintenance` The exchange is offline. No new orders or cancellations may be s…'
        )
        .optional(),
      timestamp: z.string().describe('Current timestamp (RFC3339)').optional(),
    })
    .optional(),
});

/** Documented 2xx response payload of getServerTime (statuses: 200); all fields optional because presence varies by status code. */
export const GetServerTimePayloadSchema = z.object({
  result: z
    .object({
      unixtime: z.number().int().describe('Unix timestamp').optional(),
      rfc1123: z.string().describe('RFC 1123 time format').optional(),
    })
    .optional(),
});

export const KrakenSpotApiParamsSchema = z.discriminatedUnion('operation', [
  z.object({
    operation: z
      .literal('get_ticker_information')
      .describe('Get Ticker Information'),
    baseUrl: z
      .string()
      .url()
      .describe(
        'Kraken REST API base URL including the version prefix (e.g. https://api.kraken.com/0)'
      ),
    pair: z
      .string()
      .describe(
        'Asset pair to get data for (optional, default: all tradeable exchange pairs)'
      )
      .optional(),
    credentials: BaseCredentialsSchema,
  }),
  z.object({
    operation: z.literal('get_ohlc_data').describe('Get OHLC Data'),
    baseUrl: z
      .string()
      .url()
      .describe(
        'Kraken REST API base URL including the version prefix (e.g. https://api.kraken.com/0)'
      ),
    pair: z.string().describe('Asset pair to get data for'),
    interval: z
      .number()
      .int()
      .describe('Time frame interval in minutes')
      .optional(),
    since: z
      .number()
      .int()
      .describe(
        'Return OHLC entries since the given timestamp (intended for incremental updates)'
      )
      .optional(),
    credentials: BaseCredentialsSchema,
  }),
  z.object({
    operation: z.literal('get_order_book').describe('Get Order Book'),
    baseUrl: z
      .string()
      .url()
      .describe(
        'Kraken REST API base URL including the version prefix (e.g. https://api.kraken.com/0)'
      ),
    pair: z.string().describe('Asset pair to get data for'),
    count: z
      .number()
      .int()
      .min(1)
      .max(500)
      .describe('Maximum number of asks/bids')
      .optional(),
    credentials: BaseCredentialsSchema,
  }),
  z.object({
    operation: z.literal('get_recent_trades').describe('Get Recent Trades'),
    baseUrl: z
      .string()
      .url()
      .describe(
        'Kraken REST API base URL including the version prefix (e.g. https://api.kraken.com/0)'
      ),
    pair: z.string().describe('Asset pair to get data for'),
    since: z
      .string()
      .describe('Return trade data since given timestamp')
      .optional(),
    count: z
      .number()
      .int()
      .min(1)
      .max(1000)
      .describe('Return specific number of trades, up to 1000')
      .optional(),
    credentials: BaseCredentialsSchema,
  }),
  z.object({
    operation: z.literal('get_system_status').describe('Get System Status'),
    baseUrl: z
      .string()
      .url()
      .describe(
        'Kraken REST API base URL including the version prefix (e.g. https://api.kraken.com/0)'
      ),
    credentials: BaseCredentialsSchema,
  }),
  z.object({
    operation: z.literal('get_server_time').describe('Get Server Time'),
    baseUrl: z
      .string()
      .url()
      .describe(
        'Kraken REST API base URL including the version prefix (e.g. https://api.kraken.com/0)'
      ),
    credentials: BaseCredentialsSchema,
  }),
]);

export const KrakenSpotApiResultSchema = z.discriminatedUnion('operation', [
  z
    .object({
      operation: z.literal('get_ticker_information'),
      success: z.boolean().describe('Whether the operation succeeded'),
      error: z.string().describe('Error message if operation failed'),
    })
    .merge(GetTickerInformationPayloadSchema),
  z
    .object({
      operation: z.literal('get_ohlc_data'),
      success: z.boolean().describe('Whether the operation succeeded'),
      error: z.string().describe('Error message if operation failed'),
    })
    .merge(GetOhlcDataPayloadSchema),
  z
    .object({
      operation: z.literal('get_order_book'),
      success: z.boolean().describe('Whether the operation succeeded'),
      error: z.string().describe('Error message if operation failed'),
    })
    .merge(GetOrderBookPayloadSchema),
  z
    .object({
      operation: z.literal('get_recent_trades'),
      success: z.boolean().describe('Whether the operation succeeded'),
      error: z.string().describe('Error message if operation failed'),
    })
    .merge(GetRecentTradesPayloadSchema),
  z
    .object({
      operation: z.literal('get_system_status'),
      success: z.boolean().describe('Whether the operation succeeded'),
      error: z.string().describe('Error message if operation failed'),
    })
    .merge(GetSystemStatusPayloadSchema),
  z
    .object({
      operation: z.literal('get_server_time'),
      success: z.boolean().describe('Whether the operation succeeded'),
      error: z.string().describe('Error message if operation failed'),
    })
    .merge(GetServerTimePayloadSchema),
]);

export type KrakenSpotApiParamsInput = z.input<
  typeof KrakenSpotApiParamsSchema
>;
export type KrakenSpotApiParams = z.output<typeof KrakenSpotApiParamsSchema>;
export type KrakenSpotApiResult = z.output<typeof KrakenSpotApiResultSchema>;

export type KrakenSpotApiGetTickerInformationParams = Extract<
  KrakenSpotApiParamsInput,
  { operation: 'get_ticker_information' }
>;
export type KrakenSpotApiGetOhlcDataParams = Extract<
  KrakenSpotApiParamsInput,
  { operation: 'get_ohlc_data' }
>;
export type KrakenSpotApiGetOrderBookParams = Extract<
  KrakenSpotApiParamsInput,
  { operation: 'get_order_book' }
>;
export type KrakenSpotApiGetRecentTradesParams = Extract<
  KrakenSpotApiParamsInput,
  { operation: 'get_recent_trades' }
>;
export type KrakenSpotApiGetSystemStatusParams = Extract<
  KrakenSpotApiParamsInput,
  { operation: 'get_system_status' }
>;
export type KrakenSpotApiGetServerTimeParams = Extract<
  KrakenSpotApiParamsInput,
  { operation: 'get_server_time' }
>;

export type KrakenSpotApiOperationResult<
  T extends KrakenSpotApiParams['operation'],
> = Extract<KrakenSpotApiResult, { operation: T }>;
