/**
 * Schema round-trip tests (fixtures = the examples shipped inside the vendor spec) for the 'bigquery' bubble.
 *
 * GENERATED by @bubblelab/bubble-appgen from bigquery-v2.openapi.json — do not hand-edit;
 * re-run `pnpm --filter @bubblelab/bubble-appgen generate:bigquery` instead.
 * Vendor docs: https://cloud.google.com/bigquery/docs/reference/rest
 */

import { describe, expect, it } from 'vitest';
import {
  BigQueryParamsSchema,
  BigQueryResultSchema,
} from './bigquery.schema.js';
import { BIGQUERY_OPERATION_METADATA } from './bigquery.metadata.js';

describe('bigquery generated contract', () => {
  it('jobs_query: accepts a spec-example request', () => {
    const result = BigQueryParamsSchema.safeParse({
      operation: 'jobs_query',
      endpointUrl: 'https://bigquery.googleapis.com/bigquery/v2',
      projectId: 'example',
      query: 'example',
    });
    expect(result.success).toBe(true);
  });

  it('jobs_query: rejects a type-corrupted request (projectId: number)', () => {
    const result = BigQueryParamsSchema.safeParse({
      operation: 'jobs_query',
      endpointUrl: 'https://bigquery.googleapis.com/bigquery/v2',
      projectId: 12345,
      query: 'example',
    });
    expect(result.success).toBe(false);
  });

  it('jobs_get_query_results: accepts a spec-example request', () => {
    const result = BigQueryParamsSchema.safeParse({
      operation: 'jobs_get_query_results',
      endpointUrl: 'https://bigquery.googleapis.com/bigquery/v2',
      projectId: 'example',
      jobId: 'example',
    });
    expect(result.success).toBe(true);
  });

  it('jobs_get_query_results: rejects a type-corrupted request (projectId: number)', () => {
    const result = BigQueryParamsSchema.safeParse({
      operation: 'jobs_get_query_results',
      endpointUrl: 'https://bigquery.googleapis.com/bigquery/v2',
      projectId: 12345,
      jobId: 'example',
    });
    expect(result.success).toBe(false);
  });

  it('tabledata_insert_all: accepts a spec-example request', () => {
    const result = BigQueryParamsSchema.safeParse({
      operation: 'tabledata_insert_all',
      endpointUrl: 'https://bigquery.googleapis.com/bigquery/v2',
      projectId: 'example',
      datasetId: 'example',
      tableId: 'example',
    });
    expect(result.success).toBe(true);
  });

  it('tabledata_insert_all: rejects a type-corrupted request (projectId: number)', () => {
    const result = BigQueryParamsSchema.safeParse({
      operation: 'tabledata_insert_all',
      endpointUrl: 'https://bigquery.googleapis.com/bigquery/v2',
      projectId: 12345,
      datasetId: 'example',
      tableId: 'example',
    });
    expect(result.success).toBe(false);
  });

  it('datasets_list: accepts a spec-example request', () => {
    const result = BigQueryParamsSchema.safeParse({
      operation: 'datasets_list',
      endpointUrl: 'https://bigquery.googleapis.com/bigquery/v2',
      projectId: 'example',
    });
    expect(result.success).toBe(true);
  });

  it('datasets_list: rejects a type-corrupted request (projectId: number)', () => {
    const result = BigQueryParamsSchema.safeParse({
      operation: 'datasets_list',
      endpointUrl: 'https://bigquery.googleapis.com/bigquery/v2',
      projectId: 12345,
    });
    expect(result.success).toBe(false);
  });

  it('tables_list: accepts a spec-example request', () => {
    const result = BigQueryParamsSchema.safeParse({
      operation: 'tables_list',
      endpointUrl: 'https://bigquery.googleapis.com/bigquery/v2',
      projectId: 'example',
      datasetId: 'example',
    });
    expect(result.success).toBe(true);
  });

  it('tables_list: rejects a type-corrupted request (projectId: number)', () => {
    const result = BigQueryParamsSchema.safeParse({
      operation: 'tables_list',
      endpointUrl: 'https://bigquery.googleapis.com/bigquery/v2',
      projectId: 12345,
      datasetId: 'example',
    });
    expect(result.success).toBe(false);
  });

  it('rejects requests missing the required endpointUrl', () => {
    const result = BigQueryParamsSchema.safeParse({
      operation: 'jobs_query',
      projectId: 'example',
      query: 'example',
    });
    expect(result.success).toBe(false);
  });

  it('rejects unknown operations', () => {
    const result = BigQueryParamsSchema.safeParse({
      operation: 'not_a_real_operation',
    });
    expect(result.success).toBe(false);
  });

  it('every schema operation has cited side-effect metadata (coverage guard)', () => {
    const operations = BigQueryParamsSchema.options.map(
      (option) => option.shape.operation.value
    );
    for (const operation of operations) {
      const entry = BIGQUERY_OPERATION_METADATA[operation];
      expect(entry, `missing metadata for ${operation}`).toBeDefined();
      expect(entry.citation.length).toBeGreaterThan(0);
      expect(entry.source.length).toBeGreaterThan(0);
    }
  });
});
