/**
 * Zod contract (params + results) for the 'bigquery' bubble.
 *
 * GENERATED by @bubblelab/bubble-appgen from bigquery-v2.openapi.json — do not hand-edit;
 * re-run `pnpm --filter @bubblelab/bubble-appgen generate:bigquery` instead.
 * Vendor docs: https://cloud.google.com/bigquery/docs/reference/rest
 */

import { z } from 'zod';
import { CredentialType } from '@bubblelab/shared-schemas';

// Base credentials schema shared by every operation branch
const BaseCredentialsSchema = z
  .record(z.nativeEnum(CredentialType), z.string())
  .optional()
  .describe('Object mapping credential types to values (injected at runtime)');

/** Documented 2xx response payload of JobsQuery (statuses: 200); all fields optional because presence varies by status code. */
export const JobsQueryPayloadSchema = z.object({
  arrowRecordBatch: z
    .object({
      serializedRecordBatch: z
        .string()
        .describe('IPC-serialized Arrow RecordBatch.')
        .optional(),
    })
    .describe('Output only. Serialized row data in Arrow RecordBatch format.')
    .optional(),
  arrowSchema: z
    .object({
      serializedSchema: z
        .string()
        .describe('IPC serialized Arrow schema.')
        .optional(),
    })
    .describe('Output only. Arrow schema')
    .optional(),
  cacheHit: z
    .boolean()
    .describe('Whether the query result was fetched from the query cache.')
    .optional(),
  creationTime: z
    .string()
    .describe(
      'Output only. Creation time of this query, in milliseconds since the epoch. This field will be present on all queries.'
    )
    .optional(),
  dmlStats: z
    .object({
      deletedRowCount: z
        .string()
        .describe(
          'Output only. Number of deleted Rows. populated by DML DELETE, MERGE and TRUNCATE statements.'
        )
        .optional(),
      dmlMode: z
        .enum([
          'DML_MODE_UNSPECIFIED',
          'COARSE_GRAINED_DML',
          'FINE_GRAINED_DML',
        ])
        .describe('Output only. DML mode used.')
        .optional(),
      fineGrainedDmlUnusedReason: z
        .enum([
          'FINE_GRAINED_DML_UNUSED_REASON_UNSPECIFIED',
          'MAX_PARTITION_SIZE_EXCEEDED',
          'TABLE_NOT_ENROLLED',
          'DML_IN_MULTI_STATEMENT_TRANSACTION',
        ])
        .describe(
          'Output only. Reason for disabling fine-grained DML if applicable.'
        )
        .optional(),
      insertedRowCount: z
        .string()
        .describe(
          'Output only. Number of inserted Rows. Populated by DML INSERT and MERGE statements'
        )
        .optional(),
      updatedRowCount: z
        .string()
        .describe(
          'Output only. Number of updated Rows. Populated by DML UPDATE and MERGE statements.'
        )
        .optional(),
    })
    .describe(
      'Output only. Detailed statistics for DML statements INSERT, UPDATE, DELETE, MERGE or TRUNCATE.'
    )
    .optional(),
  endTime: z
    .string()
    .describe(
      'Output only. End time of this query, in milliseconds since the epoch. This field will be present whenever a query job is in the DONE state.'
    )
    .optional(),
  errors: z
    .array(
      z
        .object({
          debugInfo: z
            .string()
            .describe(
              'Debugging information. This property is internal to Google and should not be used.'
            )
            .optional(),
          location: z
            .string()
            .describe('Specifies where the error occurred, if present.')
            .optional(),
          message: z
            .string()
            .describe('A human-readable description of the error.')
            .optional(),
          reason: z
            .string()
            .describe('A short error code that summarizes the error.')
            .optional(),
        })
        .describe('Error details.')
    )
    .describe(
      'Output only. The first errors or warnings encountered during the running of the job. The final message includes the number of errors that caused the process to stop. Errors here do not necessarily mean that the job has completed or was unsuccessful. For more information about error messages, see [Error messages](https://cloud.google.com/bigquery/docs/error-messages).'
    )
    .optional(),
  jobComplete: z
    .boolean()
    .describe(
      'Whether the query has completed or not. If rows or totalRows are present, this will always be true. If this is false, totalRows will not be available.'
    )
    .optional(),
  jobCreationReason: z
    .object({
      code: z
        .enum([
          'CODE_UNSPECIFIED',
          'REQUESTED',
          'LONG_RUNNING',
          'LARGE_RESULTS',
          'OTHER',
        ])
        .describe(
          'Output only. Specifies the high level reason why a Job was created.'
        )
        .optional(),
    })
    .describe(
      'Optional. The reason why a Job was created. Only relevant when a job_reference is present in the response. If job_reference is not present it will always be unset.'
    )
    .optional(),
  jobReference: z
    .object({
      jobId: z
        .string()
        .describe(
          'Required. The ID of the job. The ID must contain only letters (a-z, A-Z), numbers (0-9), underscores (_), or dashes (-). The maximum length is 1,024 characters.'
        ),
      location: z
        .string()
        .describe(
          'Optional. The geographic location of the job. The default value is US. For more information about BigQuery locations, see: https://cloud.google.com/bigquery/docs/locations'
        )
        .optional(),
      projectId: z
        .string()
        .describe('Required. The ID of the project containing this job.'),
    })
    .describe(
      'Reference to the Job that was created to run the query. This field will be present even if the original request timed out, in which case GetQueryResults can be used to read the results once the query has completed. Since this API only returns the first page of results, subsequent pages can be fetched via the same mechanism (GetQueryResults). If job_creation_mode was set to `JOB_CREATION_OPTIONAL` and the query completes without creating a job, this field will be empty.'
    )
    .optional(),
  kind: z.string().describe('The resource type.').optional(),
  location: z
    .string()
    .describe(
      'Output only. The geographic location of the query. For more information about BigQuery locations, see: https://cloud.google.com/bigquery/docs/locations'
    )
    .optional(),
  numDmlAffectedRows: z
    .string()
    .describe(
      'Output only. The number of rows affected by a DML statement. Present only for DML statements INSERT, UPDATE or DELETE.'
    )
    .optional(),
  pageRowCount: z
    .string()
    .describe(
      'Output only. The number of rows out of `total_rows` returned in this response. This feature is not yet available.'
    )
    .optional(),
  pageToken: z
    .string()
    .describe(
      'A token used for paging results. A non-empty token indicates that additional results are available. To see additional results, query the [`jobs.getQueryResults`](https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs/getQueryResults) method. For more information, see [Paging through table data](https://cloud.google.com/bigquery/docs/paging-results).'
    )
    .optional(),
  queryId: z.string().describe('Auto-generated ID for the query.').optional(),
  rows: z
    .array(
      z.object({
        f: z
          .array(z.object({ v: z.unknown().optional() }))
          .describe(
            'Represents a single row in the result set, consisting of one or more fields.'
          )
          .optional(),
      })
    )
    .describe(
      'An object with as many results as can be contained within the maximum permitted reply size. To get any additional rows, you can call GetQueryResults and specify the jobReference returned above.'
    )
    .optional(),
  schema: z
    .object({
      fields: z
        .array(
          z
            .object({
              categories: z
                .object({
                  names: z.array(z.string()).describe('Deprecated.').optional(),
                })
                .describe('Deprecated.')
                .optional(),
              collation: z
                .string()
                .describe(
                  "Optional. Field collation can be set only when the type of field is STRING. The following values are supported: * 'und:ci': undetermined locale, case insensitive. * '': empty string. Default to case-sensitive behavior."
                )
                .optional(),
              dataGovernanceTagsInfo: z
                .object({
                  dataGovernanceTags: z
                    .record(z.string(), z.string())
                    .describe(
                      'Optional. The data governance tags added to this field are used for field-level access control. Only one data governance tag is currently supported on a field. Tag keys are globally unique. Tag key is expected to be in the namespaced format, for example "123456789012/pii" where 123456789012 is the ID of the parent organization or project resource for this tag key. Tag value is expected to be the short name, for example "sensitive". See [Tag definitions](https://cloud.google.com/iam/docs/tags-access-control#definitions) for more details. For example: "123456789012/pii": "sensitive", "myProject/cost_center": "sales"'
                    )
                    .optional(),
                })
                .describe(
                  'Optional. Specifies the data governance tags on this field. This field works with other column-level security fields as follows: - Precedence: If a data governance tag is attached to a column, it takes precedence over the policy tag attached to the column. However, if a data policy is attached to a column, it takes precedence over the data governance tag. - Patching behavior (how this field behaves during a `Table.patch` schema update): - Unset: If the `data_governance_tags_info` field is omitted from the update request, the existing tags on the column are preserved. - Empty Field: To clear data governance tags from a column, send the `data_governance_tags_info` field as an empty object. This will remove all tags from the column. - Updating tags: To replace existing tag, send the field with the new tag.'
                )
                .optional(),
              dataPolicies: z
                .array(
                  z
                    .object({
                      name: z
                        .string()
                        .describe(
                          'Data policy resource name in the form of projects/project_id/locations/location_id/dataPolicies/data_policy_id.'
                        )
                        .optional(),
                    })
                    .describe(
                      'Data policy option. For more information, see [Mask data by applying data policies to a column](https://docs.cloud.google.com/bigquery/docs/column-data-masking#data-policies-on-column).'
                    )
                )
                .describe(
                  'Optional. Data policies attached to this field, used for field-level access control.'
                )
                .optional(),
              dataPolicyList: z
                .object({
                  dataPolicies: z
                    .array(
                      z
                        .object({
                          name: z
                            .string()
                            .describe(
                              'Data policy resource name in the form of projects/project_id/locations/location_id/dataPolicies/data_policy_id.'
                            )
                            .optional(),
                        })
                        .describe(
                          'Data policy option. For more information, see [Mask data by applying data policies to a column](https://docs.cloud.google.com/bigquery/docs/column-data-masking#data-policies-on-column).'
                        )
                    )
                    .describe(
                      'Contains a list of data policy options. At most 9 data policies are allowed per field.'
                    )
                    .optional(),
                })
                .describe(
                  'Optional. Specifies data policies attached to this field, used for field-level access control. When set, this will be the source of truth for data policy information.'
                )
                .optional(),
              defaultValueExpression: z
                .string()
                .describe(
                  'Optional. A SQL expression to specify the [default value] (https://cloud.google.com/bigquery/docs/default-values) for this field.'
                )
                .optional(),
              description: z
                .string()
                .describe(
                  'Optional. The field description. The maximum length is 1,024 characters.'
                )
                .optional(),
              fields: z
                .array(
                  z
                    .record(z.string(), z.unknown())
                    .describe(
                      'Recursive TableFieldSchema value (recursion cut for the generated contract; validated as an open object).'
                    )
                )
                .describe(
                  'Optional. Describes the nested schema fields if the type property is set to RECORD.'
                )
                .optional(),
              foreignTypeDefinition: z
                .string()
                .describe(
                  'Optional. Definition of the foreign data type. Only valid for top-level schema fields (not nested fields). If the type is FOREIGN, this field is required.'
                )
                .optional(),
              generatedColumn: z
                .object({
                  generatedExpressionInfo: z
                    .object({
                      asynchronous: z
                        .boolean()
                        .describe(
                          'Optional. Whether the column generation is done asynchronously.'
                        )
                        .optional(),
                      generationExpression: z
                        .string()
                        .describe(
                          'Optional. The generation expression (e.g. AI.EMBED(...)) used to generate the field.'
                        )
                        .optional(),
                      stored: z
                        .boolean()
                        .describe(
                          'Optional. Whether the generated column is stored in the table.'
                        )
                        .optional(),
                    })
                    .describe(
                      'Definition of the expression used to generate the field.'
                    )
                    .optional(),
                  generatedMode: z
                    .enum([
                      'GENERATED_MODE_UNSPECIFIED',
                      'GENERATED_ALWAYS',
                      'GENERATED_BY_DEFAULT',
                    ])
                    .describe(
                      'Optional. Dictates when system generated values are used to populate the field.'
                    )
                    .optional(),
                })
                .describe(
                  'Optional. Definition of how values are generated for the field. Only valid for top-level schema fields (not nested fields).'
                )
                .optional(),
              maxLength: z
                .string()
                .describe(
                  'Optional. Maximum length of values of this field for STRINGS or BYTES. If max_length is not specified, no maximum length constraint is imposed on this field. If type = "STRING", then max_length represents the maximum UTF-8 length of strings in this field. If type = "BYTES", then max_length represents the maximum number of bytes in this field. It is invalid to set this field if type ≠ "STRING" and ≠ "BYTES".'
                )
                .optional(),
              mode: z
                .string()
                .describe(
                  'Optional. The field mode. Possible values include NULLABLE, REQUIRED and REPEATED. The default value is NULLABLE.'
                )
                .optional(),
              name: z
                .string()
                .describe(
                  'Required. The field name. The name must contain only letters (a-z, A-Z), numbers (0-9), or underscores (_), and must start with a letter or underscore. The maximum length is 300 characters.'
                ),
              policyTags: z
                .object({
                  names: z
                    .array(z.string())
                    .describe(
                      'A list of policy tag resource names. For example, "projects/1/locations/eu/taxonomies/2/policyTags/3". At most 1 policy tag is currently allowed.'
                    )
                    .optional(),
                })
                .describe(
                  'Optional. The policy tags attached to this field, used for field-level access control. If not set, defaults to empty policy_tags.'
                )
                .optional(),
              precision: z
                .string()
                .describe(
                  'Optional. Precision (maximum number of total digits in base 10) and scale (maximum number of digits in the fractional part in base 10) constraints for values of this field for NUMERIC or BIGNUMERIC. It is invalid to set precision or scale if type ≠ "NUMERIC" and ≠ "BIGNUMERIC". If precision and scale are not specified, no value range constraint is imposed on this field insofar as values are permitted by the type. Values of this NUMERIC or BIGNUMERIC field must be in this range when: * Precision (P) and scale (S) are specified: [-10P-S + 10-S, 10P-S - 10-S] * Precision (P) is specified but not scale (and thus scale is interpreted to be equal to zero): [-10P + 1, 10P - 1]. Acceptable values for precision and scale if both are specified: * If type = "NUMERIC": 1 ≤ precision - scale ≤ 29 and 0 ≤ scale ≤ 9. * If type = "BIGNUMERIC": 1 ≤ precision - scale ≤ 38 and 0 ≤ scale ≤ 38. Acceptable values for precision if only precision is specified but not scale (and thus scale is interpreted to be equal to zero): * If type = "NUMERIC": 1 ≤ precision ≤ 29. * If type = "BIGNUMERIC": 1 ≤ precision ≤ 38. If scale is specified but not precision, then it is invalid.'
                )
                .optional(),
              rangeElementType: z
                .object({
                  type: z
                    .string()
                    .describe(
                      'Required. The type of a field element. For more information, see TableFieldSchema.type.'
                    ),
                })
                .describe('Represents the type of a field element.')
                .optional(),
              roundingMode: z
                .enum([
                  'ROUNDING_MODE_UNSPECIFIED',
                  'ROUND_HALF_AWAY_FROM_ZERO',
                  'ROUND_HALF_EVEN',
                ])
                .describe(
                  'Optional. Specifies the rounding mode to be used when storing values of NUMERIC and BIGNUMERIC type.'
                )
                .optional(),
              scale: z
                .string()
                .describe('Optional. See documentation for precision.')
                .optional(),
              timestampPrecision: z
                .string()
                .describe(
                  'Optional. Precision (maximum number of total digits in base 10) for seconds of TIMESTAMP type. Possible values include: * 6 (Default, for TIMESTAMP type with microsecond precision) * 12 (For TIMESTAMP type with picosecond precision)'
                )
                .optional(),
              type: z
                .string()
                .describe(
                  'Required. The field data type. Possible values include: * STRING * BYTES * INTEGER (or INT64) * FLOAT (or FLOAT64) * BOOLEAN (or BOOL) * TIMESTAMP * DATE * TIME * DATETIME * GEOGRAPHY * NUMERIC * BIGNUMERIC * JSON * RECORD (or STRUCT) * RANGE Use of RECORD/STRUCT indicates that the field contains a nested schema.'
                ),
            })
            .describe('A field in TableSchema')
        )
        .describe('Describes the fields in a table.')
        .optional(),
      foreignTypeInfo: z
        .object({
          typeSystem: z
            .enum(['TYPE_SYSTEM_UNSPECIFIED', 'HIVE'])
            .describe(
              'Required. Specifies the system which defines the foreign data type.'
            ),
        })
        .describe(
          'Optional. Specifies metadata of the foreign data type definition in field schema (TableFieldSchema.foreign_type_definition).'
        )
        .optional(),
    })
    .describe(
      'The schema of the results. Present only when the query completes successfully.'
    )
    .optional(),
  sessionInfo: z
    .object({
      sessionId: z
        .string()
        .describe('Output only. The id of the session.')
        .optional(),
    })
    .describe(
      'Output only. Information of the session if this job is part of one.'
    )
    .optional(),
  startTime: z
    .string()
    .describe(
      'Output only. Start time of this query, in milliseconds since the epoch. This field will be present when the query job transitions from the PENDING state to either RUNNING or DONE.'
    )
    .optional(),
  totalBytesBilled: z
    .string()
    .describe(
      'Output only. If the project is configured to use on-demand pricing, then this field contains the total bytes billed for the job. If the project is configured to use flat-rate pricing, then you are not billed for bytes and this field is informational only.'
    )
    .optional(),
  totalBytesProcessed: z
    .string()
    .describe(
      'The total number of bytes processed for this query. If this query was a dry run, this is the number of bytes that would be processed if the query were run.'
    )
    .optional(),
  totalRows: z
    .string()
    .describe(
      'The total number of rows in the complete query result set, which can be more than the number of rows in this single page of results.'
    )
    .optional(),
  totalSlotMs: z
    .string()
    .describe('Output only. Number of slot ms the user is actually billed for.')
    .optional(),
});

/** Documented 2xx response payload of JobsGetQueryResults (statuses: 200); all fields optional because presence varies by status code. */
export const JobsGetQueryResultsPayloadSchema = z.object({
  cacheHit: z
    .boolean()
    .describe('Whether the query result was fetched from the query cache.')
    .optional(),
  errors: z
    .array(
      z
        .object({
          debugInfo: z
            .string()
            .describe(
              'Debugging information. This property is internal to Google and should not be used.'
            )
            .optional(),
          location: z
            .string()
            .describe('Specifies where the error occurred, if present.')
            .optional(),
          message: z
            .string()
            .describe('A human-readable description of the error.')
            .optional(),
          reason: z
            .string()
            .describe('A short error code that summarizes the error.')
            .optional(),
        })
        .describe('Error details.')
    )
    .describe(
      'Output only. The first errors or warnings encountered during the running of the job. The final message includes the number of errors that caused the process to stop. Errors here do not necessarily mean that the job has completed or was unsuccessful. For more information about error messages, see [Error messages](https://cloud.google.com/bigquery/docs/error-messages).'
    )
    .optional(),
  etag: z.string().describe('A hash of this response.').optional(),
  jobComplete: z
    .boolean()
    .describe(
      'Whether the query has completed or not. If rows or totalRows are present, this will always be true. If this is false, totalRows will not be available.'
    )
    .optional(),
  jobReference: z
    .object({
      jobId: z
        .string()
        .describe(
          'Required. The ID of the job. The ID must contain only letters (a-z, A-Z), numbers (0-9), underscores (_), or dashes (-). The maximum length is 1,024 characters.'
        ),
      location: z
        .string()
        .describe(
          'Optional. The geographic location of the job. The default value is US. For more information about BigQuery locations, see: https://cloud.google.com/bigquery/docs/locations'
        )
        .optional(),
      projectId: z
        .string()
        .describe('Required. The ID of the project containing this job.'),
    })
    .describe(
      'Reference to the BigQuery Job that was created to run the query. This field will be present even if the original request timed out, in which case GetQueryResults can be used to read the results once the query has completed. Since this API only returns the first page of results, subsequent pages can be fetched via the same mechanism (GetQueryResults).'
    )
    .optional(),
  kind: z.string().describe('The resource type of the response.').optional(),
  numDmlAffectedRows: z
    .string()
    .describe(
      'Output only. The number of rows affected by a DML statement. Present only for DML statements INSERT, UPDATE or DELETE.'
    )
    .optional(),
  pageToken: z
    .string()
    .describe(
      'A token used for paging results. When this token is non-empty, it indicates additional results are available.'
    )
    .optional(),
  rows: z
    .array(
      z.object({
        f: z
          .array(z.object({ v: z.unknown().optional() }))
          .describe(
            'Represents a single row in the result set, consisting of one or more fields.'
          )
          .optional(),
      })
    )
    .describe(
      'An object with as many results as can be contained within the maximum permitted reply size. To get any additional rows, you can call GetQueryResults and specify the jobReference returned above. Present only when the query completes successfully. The REST-based representation of this data leverages a series of JSON f,v objects for indicating fields and values.'
    )
    .optional(),
  schema: z
    .object({
      fields: z
        .array(
          z
            .object({
              categories: z
                .object({
                  names: z.array(z.string()).describe('Deprecated.').optional(),
                })
                .describe('Deprecated.')
                .optional(),
              collation: z
                .string()
                .describe(
                  "Optional. Field collation can be set only when the type of field is STRING. The following values are supported: * 'und:ci': undetermined locale, case insensitive. * '': empty string. Default to case-sensitive behavior."
                )
                .optional(),
              dataGovernanceTagsInfo: z
                .object({
                  dataGovernanceTags: z
                    .record(z.string(), z.string())
                    .describe(
                      'Optional. The data governance tags added to this field are used for field-level access control. Only one data governance tag is currently supported on a field. Tag keys are globally unique. Tag key is expected to be in the namespaced format, for example "123456789012/pii" where 123456789012 is the ID of the parent organization or project resource for this tag key. Tag value is expected to be the short name, for example "sensitive". See [Tag definitions](https://cloud.google.com/iam/docs/tags-access-control#definitions) for more details. For example: "123456789012/pii": "sensitive", "myProject/cost_center": "sales"'
                    )
                    .optional(),
                })
                .describe(
                  'Optional. Specifies the data governance tags on this field. This field works with other column-level security fields as follows: - Precedence: If a data governance tag is attached to a column, it takes precedence over the policy tag attached to the column. However, if a data policy is attached to a column, it takes precedence over the data governance tag. - Patching behavior (how this field behaves during a `Table.patch` schema update): - Unset: If the `data_governance_tags_info` field is omitted from the update request, the existing tags on the column are preserved. - Empty Field: To clear data governance tags from a column, send the `data_governance_tags_info` field as an empty object. This will remove all tags from the column. - Updating tags: To replace existing tag, send the field with the new tag.'
                )
                .optional(),
              dataPolicies: z
                .array(
                  z
                    .object({
                      name: z
                        .string()
                        .describe(
                          'Data policy resource name in the form of projects/project_id/locations/location_id/dataPolicies/data_policy_id.'
                        )
                        .optional(),
                    })
                    .describe(
                      'Data policy option. For more information, see [Mask data by applying data policies to a column](https://docs.cloud.google.com/bigquery/docs/column-data-masking#data-policies-on-column).'
                    )
                )
                .describe(
                  'Optional. Data policies attached to this field, used for field-level access control.'
                )
                .optional(),
              dataPolicyList: z
                .object({
                  dataPolicies: z
                    .array(
                      z
                        .object({
                          name: z
                            .string()
                            .describe(
                              'Data policy resource name in the form of projects/project_id/locations/location_id/dataPolicies/data_policy_id.'
                            )
                            .optional(),
                        })
                        .describe(
                          'Data policy option. For more information, see [Mask data by applying data policies to a column](https://docs.cloud.google.com/bigquery/docs/column-data-masking#data-policies-on-column).'
                        )
                    )
                    .describe(
                      'Contains a list of data policy options. At most 9 data policies are allowed per field.'
                    )
                    .optional(),
                })
                .describe(
                  'Optional. Specifies data policies attached to this field, used for field-level access control. When set, this will be the source of truth for data policy information.'
                )
                .optional(),
              defaultValueExpression: z
                .string()
                .describe(
                  'Optional. A SQL expression to specify the [default value] (https://cloud.google.com/bigquery/docs/default-values) for this field.'
                )
                .optional(),
              description: z
                .string()
                .describe(
                  'Optional. The field description. The maximum length is 1,024 characters.'
                )
                .optional(),
              fields: z
                .array(
                  z
                    .record(z.string(), z.unknown())
                    .describe(
                      'Recursive TableFieldSchema value (recursion cut for the generated contract; validated as an open object).'
                    )
                )
                .describe(
                  'Optional. Describes the nested schema fields if the type property is set to RECORD.'
                )
                .optional(),
              foreignTypeDefinition: z
                .string()
                .describe(
                  'Optional. Definition of the foreign data type. Only valid for top-level schema fields (not nested fields). If the type is FOREIGN, this field is required.'
                )
                .optional(),
              generatedColumn: z
                .object({
                  generatedExpressionInfo: z
                    .object({
                      asynchronous: z
                        .boolean()
                        .describe(
                          'Optional. Whether the column generation is done asynchronously.'
                        )
                        .optional(),
                      generationExpression: z
                        .string()
                        .describe(
                          'Optional. The generation expression (e.g. AI.EMBED(...)) used to generate the field.'
                        )
                        .optional(),
                      stored: z
                        .boolean()
                        .describe(
                          'Optional. Whether the generated column is stored in the table.'
                        )
                        .optional(),
                    })
                    .describe(
                      'Definition of the expression used to generate the field.'
                    )
                    .optional(),
                  generatedMode: z
                    .enum([
                      'GENERATED_MODE_UNSPECIFIED',
                      'GENERATED_ALWAYS',
                      'GENERATED_BY_DEFAULT',
                    ])
                    .describe(
                      'Optional. Dictates when system generated values are used to populate the field.'
                    )
                    .optional(),
                })
                .describe(
                  'Optional. Definition of how values are generated for the field. Only valid for top-level schema fields (not nested fields).'
                )
                .optional(),
              maxLength: z
                .string()
                .describe(
                  'Optional. Maximum length of values of this field for STRINGS or BYTES. If max_length is not specified, no maximum length constraint is imposed on this field. If type = "STRING", then max_length represents the maximum UTF-8 length of strings in this field. If type = "BYTES", then max_length represents the maximum number of bytes in this field. It is invalid to set this field if type ≠ "STRING" and ≠ "BYTES".'
                )
                .optional(),
              mode: z
                .string()
                .describe(
                  'Optional. The field mode. Possible values include NULLABLE, REQUIRED and REPEATED. The default value is NULLABLE.'
                )
                .optional(),
              name: z
                .string()
                .describe(
                  'Required. The field name. The name must contain only letters (a-z, A-Z), numbers (0-9), or underscores (_), and must start with a letter or underscore. The maximum length is 300 characters.'
                ),
              policyTags: z
                .object({
                  names: z
                    .array(z.string())
                    .describe(
                      'A list of policy tag resource names. For example, "projects/1/locations/eu/taxonomies/2/policyTags/3". At most 1 policy tag is currently allowed.'
                    )
                    .optional(),
                })
                .describe(
                  'Optional. The policy tags attached to this field, used for field-level access control. If not set, defaults to empty policy_tags.'
                )
                .optional(),
              precision: z
                .string()
                .describe(
                  'Optional. Precision (maximum number of total digits in base 10) and scale (maximum number of digits in the fractional part in base 10) constraints for values of this field for NUMERIC or BIGNUMERIC. It is invalid to set precision or scale if type ≠ "NUMERIC" and ≠ "BIGNUMERIC". If precision and scale are not specified, no value range constraint is imposed on this field insofar as values are permitted by the type. Values of this NUMERIC or BIGNUMERIC field must be in this range when: * Precision (P) and scale (S) are specified: [-10P-S + 10-S, 10P-S - 10-S] * Precision (P) is specified but not scale (and thus scale is interpreted to be equal to zero): [-10P + 1, 10P - 1]. Acceptable values for precision and scale if both are specified: * If type = "NUMERIC": 1 ≤ precision - scale ≤ 29 and 0 ≤ scale ≤ 9. * If type = "BIGNUMERIC": 1 ≤ precision - scale ≤ 38 and 0 ≤ scale ≤ 38. Acceptable values for precision if only precision is specified but not scale (and thus scale is interpreted to be equal to zero): * If type = "NUMERIC": 1 ≤ precision ≤ 29. * If type = "BIGNUMERIC": 1 ≤ precision ≤ 38. If scale is specified but not precision, then it is invalid.'
                )
                .optional(),
              rangeElementType: z
                .object({
                  type: z
                    .string()
                    .describe(
                      'Required. The type of a field element. For more information, see TableFieldSchema.type.'
                    ),
                })
                .describe('Represents the type of a field element.')
                .optional(),
              roundingMode: z
                .enum([
                  'ROUNDING_MODE_UNSPECIFIED',
                  'ROUND_HALF_AWAY_FROM_ZERO',
                  'ROUND_HALF_EVEN',
                ])
                .describe(
                  'Optional. Specifies the rounding mode to be used when storing values of NUMERIC and BIGNUMERIC type.'
                )
                .optional(),
              scale: z
                .string()
                .describe('Optional. See documentation for precision.')
                .optional(),
              timestampPrecision: z
                .string()
                .describe(
                  'Optional. Precision (maximum number of total digits in base 10) for seconds of TIMESTAMP type. Possible values include: * 6 (Default, for TIMESTAMP type with microsecond precision) * 12 (For TIMESTAMP type with picosecond precision)'
                )
                .optional(),
              type: z
                .string()
                .describe(
                  'Required. The field data type. Possible values include: * STRING * BYTES * INTEGER (or INT64) * FLOAT (or FLOAT64) * BOOLEAN (or BOOL) * TIMESTAMP * DATE * TIME * DATETIME * GEOGRAPHY * NUMERIC * BIGNUMERIC * JSON * RECORD (or STRUCT) * RANGE Use of RECORD/STRUCT indicates that the field contains a nested schema.'
                ),
            })
            .describe('A field in TableSchema')
        )
        .describe('Describes the fields in a table.')
        .optional(),
      foreignTypeInfo: z
        .object({
          typeSystem: z
            .enum(['TYPE_SYSTEM_UNSPECIFIED', 'HIVE'])
            .describe(
              'Required. Specifies the system which defines the foreign data type.'
            ),
        })
        .describe(
          'Optional. Specifies metadata of the foreign data type definition in field schema (TableFieldSchema.foreign_type_definition).'
        )
        .optional(),
    })
    .describe(
      'The schema of the results. Present only when the query completes successfully.'
    )
    .optional(),
  totalBytesProcessed: z
    .string()
    .describe('The total number of bytes processed for this query.')
    .optional(),
  totalRows: z
    .string()
    .describe(
      'The total number of rows in the complete query result set, which can be more than the number of rows in this single page of results. Present only when the query completes successfully.'
    )
    .optional(),
});

/** Documented 2xx response payload of TabledataInsertAll (statuses: 200); all fields optional because presence varies by status code. */
export const TabledataInsertAllPayloadSchema = z.object({
  insertErrors: z
    .array(
      z
        .object({
          errors: z
            .array(
              z
                .object({
                  debugInfo: z
                    .string()
                    .describe(
                      'Debugging information. This property is internal to Google and should not be used.'
                    )
                    .optional(),
                  location: z
                    .string()
                    .describe('Specifies where the error occurred, if present.')
                    .optional(),
                  message: z
                    .string()
                    .describe('A human-readable description of the error.')
                    .optional(),
                  reason: z
                    .string()
                    .describe('A short error code that summarizes the error.')
                    .optional(),
                })
                .describe('Error details.')
            )
            .describe(
              'Error information for the row indicated by the index property.'
            )
            .optional(),
          index: z
            .number()
            .int()
            .describe('The index of the row that error applies to.')
            .optional(),
        })
        .describe("Error details about a single row's insertion.")
    )
    .describe(
      'Describes specific errors encountered while processing the request.'
    )
    .optional(),
  kind: z
    .string()
    .describe('Returns "bigquery#tableDataInsertAllResponse".')
    .optional(),
});

/** Documented 2xx response payload of DatasetsList (statuses: 200); all fields optional because presence varies by status code. */
export const DatasetsListPayloadSchema = z.object({
  datasets: z
    .array(
      z
        .object({
          catalogSource: z
            .string()
            .describe(
              'Output only. The origin of the dataset, one of: * (Unset) - Native BigQuery Dataset. * BIGLAKE - Dataset is backed by a namespace stored natively in Biglake.'
            )
            .optional(),
          datasetReference: z
            .object({
              datasetId: z
                .string()
                .describe(
                  'Required. A unique ID for this dataset, without the project name. The ID must contain only letters (a-z, A-Z), numbers (0-9), or underscores (_). The maximum length is 1,024 characters.'
                ),
              projectId: z
                .string()
                .describe(
                  'Optional. The ID of the project containing this dataset.'
                )
                .optional(),
            })
            .describe(
              "The dataset reference. Use this property to access specific parts of the dataset's ID, such as project ID or dataset ID."
            )
            .optional(),
          externalDatasetReference: z
            .object({
              connection: z
                .string()
                .describe(
                  'Required. The connection id that is used to access the external_source. Format: projects/{project_id}/locations/{location_id}/connections/{connection_id}'
                ),
              externalSource: z
                .string()
                .describe('Required. External source that backs this dataset.'),
            })
            .describe(
              'Output only. Reference to a read-only external dataset defined in data catalogs outside of BigQuery. Filled out when the dataset type is EXTERNAL.'
            )
            .optional(),
          friendlyName: z
            .string()
            .describe(
              'An alternate name for the dataset. The friendly name is purely decorative in nature.'
            )
            .optional(),
          id: z
            .string()
            .describe('The fully-qualified, unique, opaque ID of the dataset.')
            .optional(),
          kind: z
            .string()
            .describe(
              'The resource type. This property always returns the value "bigquery#dataset"'
            )
            .optional(),
          labels: z
            .record(z.string(), z.string())
            .describe(
              'The labels associated with this dataset. You can use these to organize and group your datasets.'
            )
            .optional(),
          location: z
            .string()
            .describe('The geographic location where the dataset resides.')
            .optional(),
          type: z
            .string()
            .describe(
              'Output only. Same as `type` in `Dataset`. The type of the dataset, one of: * DEFAULT - only accessible by owner and authorized accounts, * PUBLIC - accessible by everyone, * LINKED - linked dataset, * EXTERNAL - dataset with definition in external metadata catalog, * BIGLAKE_ICEBERG - a Biglake dataset accessible through the Iceberg API, * BIGLAKE_HIVE - a Biglake dataset accessible through the Hive API.'
            )
            .optional(),
        })
        .describe(
          'A dataset resource with only a subset of fields, to be returned in a list of datasets.'
        )
    )
    .describe(
      'An array of the dataset resources in the project. Each resource contains basic information. For full information about a particular dataset resource, use the Datasets: get method. This property is omitted when there are no datasets in the project.'
    )
    .optional(),
  etag: z
    .string()
    .describe(
      'Output only. A hash value of the results page. You can use this property to determine if the page has changed since the last request.'
    )
    .optional(),
  kind: z
    .string()
    .describe(
      'Output only. The resource type. This property always returns the value "bigquery#datasetList"'
    )
    .optional(),
  nextPageToken: z
    .string()
    .describe(
      'A token that can be used to request the next results page. This property is omitted on the final results page.'
    )
    .optional(),
  unreachable: z
    .array(z.string())
    .describe(
      'A list of skipped locations that were unreachable. For more information about BigQuery locations, see: https://cloud.google.com/bigquery/docs/locations. Example: "europe-west5"'
    )
    .optional(),
});

/** Documented 2xx response payload of TablesList (statuses: 200); all fields optional because presence varies by status code. */
export const TablesListPayloadSchema = z.object({
  etag: z.string().describe('A hash of this page of results.').optional(),
  kind: z.string().describe('The type of list.').optional(),
  nextPageToken: z
    .string()
    .describe('A token to request the next page of results.')
    .optional(),
  tables: z
    .array(
      z.object({
        clustering: z
          .object({
            fields: z
              .array(z.string())
              .describe(
                'One or more fields on which data should be clustered. Only top-level, non-repeated, simple-type fields are supported. The ordering of the clustering fields should be prioritized from most to least important for filtering purposes. For additional information, see [Introduction to clustered tables](https://cloud.google.com/bigquery/docs/clustered-tables#limitations).'
              )
              .optional(),
          })
          .describe('Clustering specification for this table, if configured.')
          .optional(),
        creationTime: z
          .string()
          .describe(
            'Output only. The time when this table was created, in milliseconds since the epoch.'
          )
          .optional(),
        expirationTime: z
          .string()
          .describe(
            'The time when this table expires, in milliseconds since the epoch. If not present, the table will persist indefinitely. Expired tables will be deleted and their storage reclaimed.'
          )
          .optional(),
        friendlyName: z
          .string()
          .describe('The user-friendly name for this table.')
          .optional(),
        id: z.string().describe('An opaque ID of the table.').optional(),
        kind: z.string().describe('The resource type.').optional(),
        labels: z
          .record(z.string(), z.string())
          .describe(
            'The labels associated with this table. You can use these to organize and group your tables.'
          )
          .optional(),
        rangePartitioning: z
          .object({
            field: z
              .string()
              .describe(
                'Required. The name of the column to partition the table on. It must be a top-level, INT64 column whose mode is NULLABLE or REQUIRED.'
              ),
            range: z
              .object({
                end: z
                  .string()
                  .describe(
                    '[Experimental] The end of range partitioning, exclusive.'
                  )
                  .optional(),
                interval: z
                  .string()
                  .describe('[Experimental] The width of each interval.')
                  .optional(),
                start: z
                  .string()
                  .describe(
                    '[Experimental] The start of range partitioning, inclusive.'
                  )
                  .optional(),
              })
              .describe(
                '[Experimental] Defines the ranges for range partitioning.'
              )
              .optional(),
          })
          .describe('The range partitioning for this table.')
          .optional(),
        requirePartitionFilter: z
          .boolean()
          .describe(
            'Optional. If set to true, queries including this table must specify a partition filter. This filter is used for partition elimination.'
          )
          .optional(),
        tableReference: z
          .object({
            datasetId: z
              .string()
              .describe(
                'Required. The ID of the dataset containing this table.'
              ),
            projectId: z
              .string()
              .describe(
                'Required. The ID of the project containing this table.'
              ),
            tableId: z
              .string()
              .describe(
                'Required. The ID of the table. The ID can contain Unicode characters in category L (letter), M (mark), N (number), Pc (connector, including underscore), Pd (dash), and Zs (space). For more information, see [General Category](https://wikipedia.org/wiki/Unicode_character_property#General_Category). The maximum length is 1,024 characters. Certain operations allow suffixing of the table ID with a partition decorator, such as `sample_table$20190123`.'
              ),
          })
          .describe('A reference uniquely identifying table.')
          .optional(),
        timePartitioning: z
          .object({
            expirationMs: z
              .string()
              .describe(
                'Optional. Number of milliseconds for which to keep the storage for a partition. A wrapper is used here because 0 is an invalid value.'
              )
              .optional(),
            field: z
              .string()
              .describe(
                "Optional. If not set, the table is partitioned by pseudo column '_PARTITIONTIME'; if set, the table is partitioned by this field. The field must be a top-level TIMESTAMP or DATE field. Its mode must be NULLABLE or REQUIRED. A wrapper is used here because an empty string is an invalid value."
              )
              .optional(),
            requirePartitionFilter: z
              .boolean()
              .describe(
                'If set to true, queries over this table require a partition filter that can be used for partition elimination to be specified. This field is deprecated; please set the field with the same name on the table itself instead. This field needs a wrapper because we want to output the default value, false, if the user explicitly set it.'
              )
              .optional(),
            type: z
              .string()
              .describe(
                'Required. The supported types are DAY, HOUR, MONTH, and YEAR, which will generate one partition per day, hour, month, and year, respectively.'
              ),
          })
          .describe('The time-based partitioning for this table.')
          .optional(),
        type: z.string().describe('The type of table.').optional(),
        view: z
          .object({
            privacyPolicy: z
              .object({
                aggregationThresholdPolicy: z
                  .object({
                    privacyUnitColumns: z
                      .array(z.string())
                      .describe(
                        'Optional. The privacy unit column(s) associated with this policy. For now, only one column per data source object (table, view) is allowed as a privacy unit column. Representing as a repeated field in metadata for extensibility to multiple columns in future. Duplicates and Repeated struct fields are not allowed. For nested fields, use dot notation ("outer.inner")'
                      )
                      .optional(),
                    threshold: z
                      .string()
                      .describe(
                        'Optional. The threshold for the "aggregation threshold" policy.'
                      )
                      .optional(),
                  })
                  .describe('Optional. Policy used for aggregation thresholds.')
                  .optional(),
                differentialPrivacyPolicy: z
                  .object({
                    deltaBudget: z
                      .number()
                      .describe(
                        'Optional. The total delta budget for all queries against the privacy-protected view. Each subscriber query against this view charges the amount of delta that is pre-defined by the contributor through the privacy policy delta_per_query field. If there is sufficient budget, then the subscriber query attempts to complete. It might still fail due to other reasons, in which case the charge is refunded. If there is insufficient budget the query is rejected. There might be multiple charge attempts if a single query references multiple views. In this case there must be sufficient budget for all charges or the query is rejected and charges are refunded in best effort. The budget does not have a refresh policy and can only be updated via ALTER VIEW or circumvented by creating a new view that can be queried with a fresh budget.'
                      )
                      .optional(),
                    deltaBudgetRemaining: z
                      .number()
                      .describe(
                        'Output only. The delta budget remaining. If budget is exhausted, no more queries are allowed. Note that the budget for queries that are in progress is deducted before the query executes. If the query fails or is cancelled then the budget is refunded. In this case the amount of budget remaining can increase.'
                      )
                      .optional(),
                    deltaPerQuery: z
                      .number()
                      .describe(
                        'Optional. The delta value that is used per query. Delta represents the probability that any row will fail to be epsilon differentially private. Indicates the risk associated with exposing aggregate rows in the result of a query.'
                      )
                      .optional(),
                    epsilonBudget: z
                      .number()
                      .describe(
                        'Optional. The total epsilon budget for all queries against the privacy-protected view. Each subscriber query against this view charges the amount of epsilon they request in their query. If there is sufficient budget, then the subscriber query attempts to complete. It might still fail due to other reasons, in which case the charge is refunded. If there is insufficient budget the query is rejected. There might be multiple charge attempts if a single query references multiple views. In this case there must be sufficient budget for all charges or the query is rejected and charges are refunded in best effort. The budget does not have a refresh policy and can only be updated via ALTER VIEW or circumvented by creating a new view that can be queried with a fresh budget.'
                      )
                      .optional(),
                    epsilonBudgetRemaining: z
                      .number()
                      .describe(
                        'Output only. The epsilon budget remaining. If budget is exhausted, no more queries are allowed. Note that the budget for queries that are in progress is deducted before the query executes. If the query fails or is cancelled then the budget is refunded. In this case the amount of budget remaining can increase.'
                      )
                      .optional(),
                    maxEpsilonPerQuery: z
                      .number()
                      .describe(
                        'Optional. The maximum epsilon value that a query can consume. If the subscriber specifies epsilon as a parameter in a SELECT query, it must be less than or equal to this value. The epsilon parameter controls the amount of noise that is added to the groups — a higher epsilon means less noise.'
                      )
                      .optional(),
                    maxGroupsContributed: z
                      .string()
                      .describe(
                        'Optional. The maximum groups contributed value that is used per query. Represents the maximum number of groups to which each protected entity can contribute. Changing this value does not improve or worsen privacy. The best value for accuracy and utility depends on the query and data.'
                      )
                      .optional(),
                    privacyUnitColumn: z
                      .string()
                      .describe(
                        'Optional. The privacy unit column associated with this policy. Differential privacy policies can only have one privacy unit column per data source object (table, view).'
                      )
                      .optional(),
                  })
                  .describe('Optional. Policy used for differential privacy.')
                  .optional(),
                joinRestrictionPolicy: z
                  .object({
                    joinAllowedColumns: z
                      .array(z.string())
                      .describe(
                        'Optional. The only columns that joins are allowed on. This field is must be specified for join_conditions JOIN_ANY and JOIN_ALL and it cannot be set for JOIN_BLOCKED.'
                      )
                      .optional(),
                    joinCondition: z
                      .enum([
                        'JOIN_CONDITION_UNSPECIFIED',
                        'JOIN_ANY',
                        'JOIN_ALL',
                        'JOIN_NOT_REQUIRED',
                        'JOIN_BLOCKED',
                      ])
                      .describe(
                        'Optional. Specifies if a join is required or not on queries for the view. Default is JOIN_CONDITION_UNSPECIFIED.'
                      )
                      .optional(),
                  })
                  .describe(
                    "Optional. Join restriction policy is outside of the one of policies, since this policy can be set along with other policies. This policy gives data providers the ability to enforce joins on the 'join_allowed_columns' when data is queried from a privacy protected view."
                  )
                  .optional(),
              })
              .describe('Specifies the privacy policy for the view.')
              .optional(),
            useLegacySql: z
              .boolean()
              .describe(
                'True if view is defined in legacy SQL dialect, false if in GoogleSQL.'
              )
              .optional(),
          })
          .describe('Information about a logical view.')
          .optional(),
      })
    )
    .describe('Tables in the requested dataset.')
    .optional(),
  totalItems: z
    .number()
    .int()
    .describe('The total number of tables in the dataset.')
    .optional(),
});

export const BigQueryParamsSchema = z.discriminatedUnion('operation', [
  z.object({
    operation: z
      .literal('jobs_query')
      .describe(
        'Runs a BigQuery SQL query synchronously and returns query results if the query completes within a specified timeout.'
      ),
    endpointUrl: z
      .string()
      .url()
      .describe(
        'BigQuery REST API base URL (regional/private endpoints supported) (e.g. https://bigquery.googleapis.com/bigquery/v2)'
      ),
    projectId: z
      .string()
      .describe('Required. Project ID of the query request.'),
    arrowSerializationOptions: z
      .object({
        bufferCompression: z
          .enum(['COMPRESSION_UNSPECIFIED', 'LZ4_FRAME', 'ZSTD'])
          .describe(
            'The compression codec to use for Arrow buffers in serialized record batches.'
          )
          .optional(),
        picosTimestampPrecision: z
          .enum([
            'PICOS_TIMESTAMP_PRECISION_UNSPECIFIED',
            'TIMESTAMP_PRECISION_MICROS',
            'TIMESTAMP_PRECISION_NANOS',
            'TIMESTAMP_PRECISION_PICOS',
          ])
          .describe(
            'Optional. Set timestamp precision option. If not set, the default precision is microseconds.'
          )
          .optional(),
      })
      .describe('Optional. Options specific to the Apache Arrow output format.')
      .optional(),
    connectionProperties: z
      .array(
        z
          .object({
            key: z
              .string()
              .describe('The key of the property to set.')
              .optional(),
            value: z
              .string()
              .describe('The value of the property to set.')
              .optional(),
          })
          .describe(
            'A connection-level property to customize query behavior. Under JDBC, these correspond directly to connection properties passed to the DriverManager. Under ODBC, these correspond to properties in the connection string. Currently supported connection properties: * **dataset_project_id**: represents the default project for datasets that are used in the query. Setting the system variable `@@dataset_project_id` achieves the same behavior. For more information about system variables, see: https://cloud.google.com/bigquery/docs/reference/system-variables * **time_zone**: represents the default timezone used to run the query. * **session_id**: associates the query with a given session. * **query_label**: associates the query with a given job label. If set, all subsequent queries in a script or session will have this label. For the format in which a you can specify a query label, see labels in the JobConfiguration resource type: https://cloud.google.com/bigquery/docs/reference/rest/v2/Job#jobconfiguration * **service_account**: indicates the service account to use to run a continuous query. If set, the query job uses the service account to access Google Cloud resources. Service account access is bounded by the IAM permissions that you have granted to the service account. Additional properties are allowed, but ignored. Specifying multiple connection properties with the same key returns an error.'
          )
      )
      .describe(
        'Optional. Connection properties which can modify the query behavior.'
      )
      .optional(),
    continuous: z
      .boolean()
      .describe(
        '[Optional] Specifies whether the query should be executed as a continuous query. The default value is false.'
      )
      .optional(),
    createSession: z
      .boolean()
      .describe(
        "Optional. If true, creates a new session using a randomly generated session_id. If false, runs query with an existing session_id passed in ConnectionProperty, otherwise runs query in non-session mode. The session location will be set to QueryRequest.location if it is present, otherwise it's set to the default location based on existing routing logic."
      )
      .optional(),
    defaultDataset: z
      .object({
        datasetId: z
          .string()
          .describe(
            'Required. A unique ID for this dataset, without the project name. The ID must contain only letters (a-z, A-Z), numbers (0-9), or underscores (_). The maximum length is 1,024 characters.'
          ),
        projectId: z
          .string()
          .describe('Optional. The ID of the project containing this dataset.')
          .optional(),
      })
      .describe(
        "Optional. Specifies the default datasetId and projectId to assume for any unqualified table names in the query. If not set, all table names in the query string must be qualified in the format 'datasetId.tableId'."
      )
      .optional(),
    destinationEncryptionConfiguration: z
      .object({
        kmsKeyName: z
          .string()
          .describe(
            'Optional. Describes the Cloud KMS encryption key that will be used to protect destination BigQuery table. The BigQuery Service Account associated with your project requires access to this encryption key.'
          )
          .optional(),
      })
      .describe(
        'Optional. Custom encryption configuration (e.g., Cloud KMS keys)'
      )
      .optional(),
    dryRun: z
      .boolean()
      .describe(
        "Optional. If set to true, BigQuery doesn't run the job. Instead, if the query is valid, BigQuery returns statistics about the job such as how many bytes would be processed. If the query is invalid, an error returns. The default value is false."
      )
      .optional(),
    formatOptions: z
      .object({
        timestampOutputFormat: z
          .enum([
            'TIMESTAMP_OUTPUT_FORMAT_UNSPECIFIED',
            'FLOAT64',
            'INT64',
            'ISO8601_STRING',
          ])
          .describe(
            'Optional. The API output format for a timestamp. This offers more explicit control over the timestamp output format as compared to the existing `use_int64_timestamp` option.'
          )
          .optional(),
        useInt64Timestamp: z
          .boolean()
          .describe(
            'Optional. Output timestamp as usec int64. Default is false.'
          )
          .optional(),
      })
      .describe('Optional. Output format adjustments.')
      .optional(),
    jobCreationMode: z
      .enum([
        'JOB_CREATION_MODE_UNSPECIFIED',
        'JOB_CREATION_REQUIRED',
        'JOB_CREATION_OPTIONAL',
      ])
      .describe(
        'Optional. If not set, jobs are always required. If set, the query request will follow the behavior described JobCreationMode.'
      )
      .optional(),
    jobTimeoutMs: z
      .string()
      .describe(
        'Optional. Job timeout in milliseconds. If this time limit is exceeded, BigQuery will attempt to stop a longer job, but may not always succeed in canceling it before the job completes. For example, a job that takes more than 60 seconds to complete has a better chance of being stopped than a job that takes 10 seconds to complete. This timeout applies to the query even if a job does not need to be created.'
      )
      .optional(),
    kind: z.string().describe('The resource type of the request.').optional(),
    labels: z
      .record(z.string(), z.string())
      .describe(
        'Optional. The labels associated with this query. Labels can be used to organize and group query jobs. Label keys and values can be no longer than 63 characters, can only contain lowercase letters, numeric characters, underscores and dashes. International characters are allowed. Label keys must start with a letter and each label in the list must have a different key.'
      )
      .optional(),
    location: z
      .string()
      .describe(
        'The geographic location where the job should run. For more information, see how to [specify locations](https://cloud.google.com/bigquery/docs/locations#specify_locations).'
      )
      .optional(),
    maxResults: z
      .number()
      .int()
      .describe(
        'Optional. The maximum number of rows of data to return per page of results. Setting this flag to a small value such as 1000 and then paging through results might improve reliability when the query result set is large. In addition to this limit, responses are also limited to 10 MB. By default, there is no maximum row count, and only the byte limit applies.'
      )
      .optional(),
    maxSlots: z
      .number()
      .int()
      .describe(
        'Optional. A target limit on the rate of slot consumption by this query. If set to a value > 0, BigQuery will attempt to limit the rate of slot consumption by this query to keep it below the configured limit, even if the query is eligible for more slots based on fair scheduling. The unused slots will be available for other jobs and queries to use. Note: This feature is not yet generally available.'
      )
      .optional(),
    maximumBytesBilled: z
      .string()
      .describe(
        'Optional. Limits the bytes billed for this query. Queries with bytes billed above this limit will fail (without incurring a charge). If unspecified, the project default is used.'
      )
      .optional(),
    parameterMode: z
      .string()
      .describe(
        'GoogleSQL only. Set to POSITIONAL to use positional (?) query parameters or to NAMED to use named (@myparam) query parameters in this query.'
      )
      .optional(),
    preserveNulls: z
      .boolean()
      .describe('This property is deprecated.')
      .optional(),
    query: z
      .string()
      .describe(
        'Required. A query string to execute, using Google Standard SQL or legacy SQL syntax. Example: "SELECT COUNT(f1) FROM myProjectId.myDatasetId.myTableId".'
      ),
    queryParameters: z
      .array(
        z
          .object({
            name: z
              .string()
              .describe(
                'Optional. If unset, this is a positional parameter. Otherwise, should be unique within a query.'
              )
              .optional(),
            parameterType: z
              .object({
                arrayType: z
                  .record(z.string(), z.unknown())
                  .describe(
                    'Recursive QueryParameterType value (recursion cut for the generated contract; validated as an open object).'
                  )
                  .optional(),
                rangeElementType: z
                  .record(z.string(), z.unknown())
                  .describe(
                    'Recursive QueryParameterType value (recursion cut for the generated contract; validated as an open object).'
                  )
                  .optional(),
                structTypes: z
                  .array(
                    z
                      .object({
                        description: z
                          .string()
                          .describe(
                            'Optional. Human-oriented description of the field.'
                          )
                          .optional(),
                        name: z
                          .string()
                          .describe('Optional. The name of this field.')
                          .optional(),
                        type: z
                          .record(z.string(), z.unknown())
                          .describe(
                            'Recursive QueryParameterType value (recursion cut for the generated contract; validated as an open object).'
                          ),
                      })
                      .describe('The type of a struct parameter.')
                  )
                  .describe(
                    'Optional. The types of the fields of this struct, in order, if this is a struct.'
                  )
                  .optional(),
                timestampPrecision: z
                  .string()
                  .describe(
                    'Optional. Precision (maximum number of total digits in base 10) for seconds of TIMESTAMP type. Possible values include: * 6 (Default, for TIMESTAMP type with microsecond precision) * 12 (For TIMESTAMP type with picosecond precision)'
                  )
                  .optional(),
                type: z
                  .string()
                  .describe('Required. The top level type of this field.'),
              })
              .describe('Required. The type of this parameter.'),
            parameterValue: z
              .object({
                arrayValues: z
                  .array(
                    z
                      .record(z.string(), z.unknown())
                      .describe(
                        'Recursive QueryParameterValue value (recursion cut for the generated contract; validated as an open object).'
                      )
                  )
                  .describe(
                    'Optional. The array values, if this is an array type.'
                  )
                  .optional(),
                rangeValue: z
                  .object({
                    end: z
                      .record(z.string(), z.unknown())
                      .describe(
                        'Recursive QueryParameterValue value (recursion cut for the generated contract; validated as an open object).'
                      )
                      .optional(),
                    start: z
                      .record(z.string(), z.unknown())
                      .describe(
                        'Recursive QueryParameterValue value (recursion cut for the generated contract; validated as an open object).'
                      )
                      .optional(),
                  })
                  .describe(
                    'Optional. The range value, if this is a range type.'
                  )
                  .optional(),
                structValues: z
                  .record(
                    z.string(),
                    z
                      .record(z.string(), z.unknown())
                      .describe(
                        'Recursive QueryParameterValue value (recursion cut for the generated contract; validated as an open object).'
                      )
                  )
                  .describe('The struct field values.')
                  .optional(),
                value: z
                  .string()
                  .describe(
                    'Optional. The value of this value, if a simple scalar type.'
                  )
                  .optional(),
              })
              .describe('Required. The value of this parameter.'),
          })
          .describe('A parameter given to a query.')
      )
      .describe('Query parameters for GoogleSQL queries.')
      .optional(),
    queryResultsFormat: z
      .enum(['QUERY_RESULTS_FORMAT_UNSPECIFIED', 'STRUCT_ENCODING', 'ARROW'])
      .describe(
        'Optional. The query results format. If the value is anything other than `STRUCT_ENCODING` or unspecified: * The schema of the results will be provided in `QueryResponse.results_schema` field. * The results of the first page will be provided in `QueryResponse.results` field. * The `QueryResponse.rows` will not be populated. * The `QueryResponse.schema` for `QueryResponse.rows` will also not be populated since it is the schema of the `QueryResponse.rows`. This feature is not yet available.'
      )
      .optional(),
    requestId: z
      .string()
      .describe(
        "Optional. A unique user provided identifier to ensure idempotent behavior for queries. Note that this is different from the job_id. It has the following properties: 1. It is case-sensitive, limited to up to 36 ASCII characters. A UUID is recommended. 2. Read only queries can ignore this token since they are nullipotent by definition. 3. For the purposes of idempotency ensured by the request_id, a request is considered duplicate of another only if they have the same request_id and are actually duplicates. When determining whether a request is a duplicate of another request, all parameters in the request that may affect the result are considered. For example, query, connection_properties, query_parameters, use_legacy_sql are parameters that affect the result and are considered when determining whether a request is a duplicate, but properties like timeout_ms don't affect the result and are thus not considered. Dry run query requests are never considered duplicate of another request. 4. When a duplicate mutating query request is detected, it returns: a. the results of the mutation if it completes successfully within the timeout. b. the running operation if it is still in progress at the end of the timeout. 5. Its lifetime is limited to 15 minutes. In other words, if two requests are sent with the same request_id, but more than 15 minutes apart, idempotency is not guaranteed."
      )
      .optional(),
    reservation: z
      .string()
      .describe(
        'Optional. The reservation that jobs.query request would use. User can specify a reservation to execute the job.query. The expected format is `projects/{project}/locations/{location}/reservations/{reservation}`. Forces the query to use on-demand billing when set to `none`. This requires the project or organization to have `reservation_override_mode` set to `ALLOW_ANY_OVERRIDE`.'
      )
      .optional(),
    timeoutMs: z
      .number()
      .int()
      .describe(
        'Optional. Optional: Specifies the maximum amount of time, in milliseconds, that the client is willing to wait for the query to complete. By default, this limit is 10 seconds (10,000 milliseconds). If the query is complete, the jobComplete field in the response is true. If the query has not yet completed, jobComplete is false. You can request a longer timeout period in the timeoutMs field. However, the call is not guaranteed to wait for the specified timeout; it typically returns after around 200 seconds (200,000 milliseconds), even if the query is not complete. If jobComplete is false, you can continue to wait for the query to complete by calling the getQueryResults method until the jobComplete field in the getQueryResults response is true.'
      )
      .optional(),
    useLegacySql: z
      .boolean()
      .describe(
        "Specifies whether to use BigQuery's legacy SQL dialect for this query. The default value is true. If set to false, the query uses BigQuery's [GoogleSQL](https://docs.cloud.google.com/bigquery/docs/introduction-sql). When useLegacySql is set to false, the value of flattenResults is ignored; query will be run as if flattenResults is false."
      )
      .optional(),
    useQueryCache: z
      .boolean()
      .describe(
        'Optional. Whether to look for the result in the query cache. The query cache is a best-effort cache that will be flushed whenever tables in the query are modified. The default value is true.'
      )
      .optional(),
    writeIncrementalResults: z
      .boolean()
      .describe(
        'Optional. This is only supported for SELECT query. If set, the query is allowed to write results incrementally to the temporary result table. This may incur a performance penalty. This option cannot be used with Legacy SQL. This feature is not yet available.'
      )
      .optional(),
    credentials: BaseCredentialsSchema,
  }),
  z.object({
    operation: z
      .literal('jobs_get_query_results')
      .describe('RPC to get the results of a query job.'),
    endpointUrl: z
      .string()
      .url()
      .describe(
        'BigQuery REST API base URL (regional/private endpoints supported) (e.g. https://bigquery.googleapis.com/bigquery/v2)'
      ),
    projectId: z.string().describe('Required. Project ID of the query job.'),
    jobId: z.string().describe('Required. Job ID of the query job.'),
    'formatOptions.timestampOutputFormat': z
      .enum([
        'TIMESTAMP_OUTPUT_FORMAT_UNSPECIFIED',
        'FLOAT64',
        'INT64',
        'ISO8601_STRING',
      ])
      .describe(
        'Optional. The API output format for a timestamp. This offers more explicit control over the timestamp output format as compared to the existing `use_int64_timestamp` option.'
      )
      .optional(),
    'formatOptions.useInt64Timestamp': z
      .boolean()
      .describe('Optional. Output timestamp as usec int64. Default is false.')
      .optional(),
    location: z
      .string()
      .describe(
        "The geographic location of the job. You must specify the location to run the job for the following scenarios: * If the location to run a job is not in the `us` or the `eu` multi-regional location * If the job's location is in a single region (for example, `us-central1`) For more information, see how to [specify locations](https://cloud.google.com/bigquery/docs/locations#specify_locations)."
      )
      .optional(),
    maxResults: z
      .number()
      .int()
      .describe('Maximum number of results to read.')
      .optional(),
    pageToken: z
      .string()
      .describe(
        'Page token, returned by a previous call, to request the next page of results.'
      )
      .optional(),
    startIndex: z
      .string()
      .describe('Zero-based index of the starting row.')
      .optional(),
    timeoutMs: z
      .number()
      .int()
      .describe(
        'Optional: Specifies the maximum amount of time, in milliseconds, that the client is willing to wait for the query to complete. By default, this limit is 10 seconds (10,000 milliseconds). If the query is complete, the jobComplete field in the response is true. If the query has not yet completed, jobComplete is false. You can request a longer timeout period in the timeoutMs field. However, the call is not guaranteed to wait for the specified timeout; it typically returns after around 200 seconds (200,000 milliseconds), even if the query is not complete. If jobComplete is false, you can continue to wait for the query to complete by calling the getQueryResults method until the jobComplete field in the getQueryResults response is true.'
      )
      .optional(),
    credentials: BaseCredentialsSchema,
  }),
  z.object({
    operation: z
      .literal('tabledata_insert_all')
      .describe(
        'Streams data into BigQuery one record at a time without needing to run a load job.'
      ),
    endpointUrl: z
      .string()
      .url()
      .describe(
        'BigQuery REST API base URL (regional/private endpoints supported) (e.g. https://bigquery.googleapis.com/bigquery/v2)'
      ),
    projectId: z.string().describe('Required. Project ID of the destination.'),
    datasetId: z.string().describe('Required. Dataset ID of the destination.'),
    tableId: z.string().describe('Required. Table ID of the destination.'),
    ignoreUnknownValues: z
      .boolean()
      .describe(
        'Optional. Accept rows that contain values that do not match the schema. The unknown values are ignored. Default is false, which treats unknown values as errors.'
      )
      .optional(),
    kind: z
      .string()
      .describe(
        'Optional. The resource type of the response. The value is not checked at the backend. Historically, it has been set to "bigquery#tableDataInsertAllRequest" but you are not required to set it.'
      )
      .optional(),
    rows: z
      .array(
        z
          .object({
            insertId: z
              .string()
              .describe(
                'Insertion ID for best-effort deduplication. This feature is not recommended, and users seeking stronger insertion semantics are encouraged to use other mechanisms such as the BigQuery Write API.'
              )
              .optional(),
            json: z
              .record(z.string(), z.unknown())
              .describe('Data for a single row.')
              .optional(),
          })
          .describe('Data for a single insertion row.')
      )
      .optional(),
    skipInvalidRows: z
      .boolean()
      .describe(
        'Optional. Insert all valid rows of a request, even if invalid rows exist. The default value is false, which causes the entire request to fail if any invalid rows exist.'
      )
      .optional(),
    templateSuffix: z
      .string()
      .describe(
        'Optional. If specified, treats the destination table as a base template, and inserts the rows into an instance table named "{destination}{templateSuffix}". BigQuery will manage creation of the instance table, using the schema of the base template table. See https://cloud.google.com/bigquery/streaming-data-into-bigquery#template-tables for considerations when working with templates tables.'
      )
      .optional(),
    traceId: z
      .string()
      .describe(
        'Optional. Unique request trace id. Used for debugging purposes only. It is case-sensitive, limited to up to 36 ASCII characters. A UUID is recommended.'
      )
      .optional(),
    credentials: BaseCredentialsSchema,
  }),
  z.object({
    operation: z
      .literal('datasets_list')
      .describe(
        'Lists all datasets in the specified project to which the user has been granted the READER dataset role.'
      ),
    endpointUrl: z
      .string()
      .url()
      .describe(
        'BigQuery REST API base URL (regional/private endpoints supported) (e.g. https://bigquery.googleapis.com/bigquery/v2)'
      ),
    projectId: z
      .string()
      .describe('Required. Project ID of the datasets to be listed'),
    all: z
      .boolean()
      .describe('Whether to list all datasets, including hidden ones')
      .optional(),
    filter: z
      .string()
      .describe(
        'An expression for filtering the results of the request by label. The syntax is `labels.[:]`. Multiple filters can be AND-ed together by connecting with a space. Example: `labels.department:receiving labels.active`. See [Filtering datasets using labels](https://cloud.google.com/bigquery/docs/filtering-labels#filtering_datasets_using_labels) for details.'
      )
      .optional(),
    maxResults: z
      .number()
      .int()
      .describe(
        'The maximum number of results to return in a single response page. Leverage the page tokens to iterate through the entire collection.'
      )
      .optional(),
    pageToken: z
      .string()
      .describe(
        'Page token, returned by a previous call, to request the next page of results'
      )
      .optional(),
    credentials: BaseCredentialsSchema,
  }),
  z.object({
    operation: z
      .literal('tables_list')
      .describe('Lists all tables in the specified dataset.'),
    endpointUrl: z
      .string()
      .url()
      .describe(
        'BigQuery REST API base URL (regional/private endpoints supported) (e.g. https://bigquery.googleapis.com/bigquery/v2)'
      ),
    projectId: z
      .string()
      .describe('Required. Project ID of the tables to list'),
    datasetId: z
      .string()
      .describe('Required. Dataset ID of the tables to list'),
    maxResults: z
      .number()
      .int()
      .describe(
        'The maximum number of results to return in a single response page. Leverage the page tokens to iterate through the entire collection.'
      )
      .optional(),
    pageToken: z
      .string()
      .describe(
        'Page token, returned by a previous call, to request the next page of results'
      )
      .optional(),
    credentials: BaseCredentialsSchema,
  }),
]);

export const BigQueryResultSchema = z.discriminatedUnion('operation', [
  z
    .object({
      operation: z.literal('jobs_query'),
      success: z.boolean().describe('Whether the operation succeeded'),
      error: z.string().describe('Error message if operation failed'),
    })
    .merge(JobsQueryPayloadSchema),
  z
    .object({
      operation: z.literal('jobs_get_query_results'),
      success: z.boolean().describe('Whether the operation succeeded'),
      error: z.string().describe('Error message if operation failed'),
    })
    .merge(JobsGetQueryResultsPayloadSchema),
  z
    .object({
      operation: z.literal('tabledata_insert_all'),
      success: z.boolean().describe('Whether the operation succeeded'),
      error: z.string().describe('Error message if operation failed'),
    })
    .merge(TabledataInsertAllPayloadSchema),
  z
    .object({
      operation: z.literal('datasets_list'),
      success: z.boolean().describe('Whether the operation succeeded'),
      error: z.string().describe('Error message if operation failed'),
    })
    .merge(DatasetsListPayloadSchema),
  z
    .object({
      operation: z.literal('tables_list'),
      success: z.boolean().describe('Whether the operation succeeded'),
      error: z.string().describe('Error message if operation failed'),
    })
    .merge(TablesListPayloadSchema),
]);

export type BigQueryParamsInput = z.input<typeof BigQueryParamsSchema>;
export type BigQueryParams = z.output<typeof BigQueryParamsSchema>;
export type BigQueryResult = z.output<typeof BigQueryResultSchema>;

export type BigQueryJobsQueryParams = Extract<
  BigQueryParamsInput,
  { operation: 'jobs_query' }
>;
export type BigQueryJobsGetQueryResultsParams = Extract<
  BigQueryParamsInput,
  { operation: 'jobs_get_query_results' }
>;
export type BigQueryTabledataInsertAllParams = Extract<
  BigQueryParamsInput,
  { operation: 'tabledata_insert_all' }
>;
export type BigQueryDatasetsListParams = Extract<
  BigQueryParamsInput,
  { operation: 'datasets_list' }
>;
export type BigQueryTablesListParams = Extract<
  BigQueryParamsInput,
  { operation: 'tables_list' }
>;

export type BigQueryOperationResult<T extends BigQueryParams['operation']> =
  Extract<BigQueryResult, { operation: T }>;
