/**
 * Doc-grounded per-operation side-effect metadata (IR-8) for the 'bigquery' bubble.
 *
 * GENERATED by @bubblelab/bubble-appgen from bigquery-v2.openapi.json — do not hand-edit;
 * re-run `pnpm --filter @bubblelab/bubble-appgen generate:bigquery` instead.
 * Vendor docs: https://cloud.google.com/bigquery/docs/reference/rest
 */

import type { BubbleOperationMetadata } from '@bubblelab/shared-schemas';

export const BIGQUERY_OPERATION_METADATA: BubbleOperationMetadata = {
  jobs_query: {
    sideEffect: 'write',
    destructive: false,
    idempotent: false,
    confidence: 0.85,
    source: 'openapi',
    citation:
      'bigquery-v2.openapi.json#/paths/~1projects~1{projectId}~1queries/post — "Runs a BigQuery SQL query synchronously and returns query results if the query completes within a specified timeout." — carrier operation: executes caller-supplied SQL; fail-safe write until statement-level verb refinement is applied',
  },
  jobs_get_query_results: {
    sideEffect: 'read',
    destructive: false,
    idempotent: true,
    confidence: 0.85,
    source: 'openapi',
    citation:
      'bigquery-v2.openapi.json#/paths/~1projects~1{projectId}~1queries~1{jobId}/get — "RPC to get the results of a query job."',
  },
  tabledata_insert_all: {
    sideEffect: 'write',
    destructive: false,
    idempotent: false,
    confidence: 0.2,
    source: 'openapi',
    citation:
      'bigquery-v2.openapi.json#/paths/~1projects~1{projectId}~1datasets~1{datasetId}~1tables~1{tableId}~1insertAll/post — no doc signal in "Streams data into BigQuery one record at a time without needing to run a load job."; fail-safe write pending human review',
    unverified: true,
  },
  datasets_list: {
    sideEffect: 'read',
    destructive: false,
    idempotent: true,
    confidence: 0.85,
    source: 'openapi',
    citation:
      'bigquery-v2.openapi.json#/paths/~1projects~1{projectId}~1datasets/get — "Lists all datasets in the specified project to which the user has been granted the READER dataset role."',
  },
  tables_list: {
    sideEffect: 'read',
    destructive: false,
    idempotent: true,
    confidence: 0.85,
    source: 'openapi',
    citation:
      'bigquery-v2.openapi.json#/paths/~1projects~1{projectId}~1datasets~1{datasetId}~1tables/get — "Lists all tables in the specified dataset."',
  },
};
