/**
 * ServiceBubble class (raw-fetch pattern) for the 'bigquery' bubble.
 *
 * GENERATED by @bubblelab/bubble-appgen from bigquery-v2.openapi.json — do not hand-edit;
 * re-run `pnpm --filter @bubblelab/bubble-appgen generate:bigquery` instead.
 * Vendor docs: https://cloud.google.com/bigquery/docs/reference/rest
 */

import { ServiceBubble } from '../../../types/service-bubble-class.js';
import type { BubbleContext } from '../../../types/bubble.js';
import { CredentialType } from '@bubblelab/shared-schemas';
import { BIGQUERY_OPERATION_METADATA } from './bigquery.metadata.js';
import {
  BigQueryParamsSchema,
  BigQueryResultSchema,
  JobsQueryPayloadSchema,
  JobsGetQueryResultsPayloadSchema,
  TabledataInsertAllPayloadSchema,
  DatasetsListPayloadSchema,
  TablesListPayloadSchema,
  type BigQueryParams,
  type BigQueryParamsInput,
  type BigQueryResult,
} from './bigquery.schema.js';

/** Strip a trailing slash so path concatenation stays canonical. */
function trimBaseUrl(url: string): string {
  return url.endsWith('/') ? url.slice(0, -1) : url;
}

/** Serialize defined query params; returns '' or '?k=v&…'. */
function buildQuery(
  params: Record<string, string | number | boolean | undefined>
): string {
  const search = new URLSearchParams();
  for (const [key, value] of Object.entries(params)) {
    if (value !== undefined) search.set(key, String(value));
  }
  const qs = search.toString();
  return qs.length > 0 ? `?${qs}` : '';
}

/** Drop undefined values before JSON body serialization. */
function pruneUndefined(
  record: Record<string, unknown>
): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(record)) {
    if (value !== undefined) out[key] = value;
  }
  return out;
}

export class BigQueryBubble<
  T extends BigQueryParamsInput = BigQueryParamsInput,
> extends ServiceBubble<
  T,
  Extract<BigQueryResult, { operation: T['operation'] }>
> {
  static readonly type = 'service' as const;
  static readonly service = 'bigquery';
  static readonly authType = 'apikey' as const;
  static readonly bubbleName = 'bigquery';
  static readonly operationMetadata = BIGQUERY_OPERATION_METADATA;
  static readonly schema = BigQueryParamsSchema;
  static readonly resultSchema = BigQueryResultSchema;
  static readonly shortDescription =
    'Google BigQuery REST API v2 integration generated from the official API Discovery document (run SQL queries, stream row inserts, list datasets and tables)';
  static readonly longDescription = `
    Google BigQuery REST API v2 integration generated from the official API Discovery document (run SQL queries, stream row inserts, list datasets and tables)

    Operations (generated from the vendor OpenAPI spec):
    - jobs_query [side-effect: write]: Runs a BigQuery SQL query synchronously and returns query results if the query completes within a specified timeout.
    - jobs_get_query_results [side-effect: read]: RPC to get the results of a query job.
    - tabledata_insert_all [side-effect: write]: Streams data into BigQuery one record at a time without needing to run a load job.
    - datasets_list [side-effect: read]: Lists all datasets in the specified project to which the user has been granted the READER dataset role.
    - tables_list [side-effect: read]: Lists all tables in the specified dataset.

    Credential: BIGQUERY_TOKEN (bearer token) + per-account endpointUrl.
  `;
  static readonly alias = 'bq';

  constructor(
    params: T = {
      operation: 'jobs_get_query_results',
      endpointUrl: 'https://bigquery.googleapis.com/bigquery/v2',
      projectId: 'example',
      jobId: 'example',
    } as T,
    context?: BubbleContext,
    instanceId?: string
  ) {
    super(params, context, instanceId);
  }

  private requestHeaders(
    token: string,
    hasBody: boolean
  ): Record<string, string> {
    const headers: Record<string, string> = {
      Authorization: `Bearer ${token}`,
      Accept: 'application/json',
      'User-Agent': 'bubblelab/1.0',
    };
    if (hasBody) headers['Content-Type'] ??= 'application/json';
    return headers;
  }

  public async testCredential(): Promise<boolean> {
    const token = this.chooseCredential();
    if (!token) {
      throw new Error('bigquery credentials are required');
    }
    const params = { endpointUrl: this.params.endpointUrl };
    // Probe: GET /projects/{projectId}/queries/{jobId} (jobs_get_query_results) with a synthesized handle.
    // 401/403 mean the credential was rejected; any other status means it was accepted.
    const response = await fetch(
      `${trimBaseUrl(params.endpointUrl)}/projects/example/queries/example`,
      {
        method: 'GET',
        headers: this.requestHeaders(token, false),
      }
    );
    return response.status !== 401 && response.status !== 403;
  }

  protected chooseCredential(): string | undefined {
    const credentials = this.params.credentials;
    if (!credentials || typeof credentials !== 'object') {
      return undefined;
    }
    return credentials[CredentialType.BIGQUERY_TOKEN];
  }

  protected async performAction(
    context?: BubbleContext
  ): Promise<Extract<BigQueryResult, { operation: T['operation'] }>> {
    void context;
    const { operation } = this.params;
    switch (operation) {
      case 'jobs_query':
        return this.handleJobsQuery() as Promise<
          Extract<BigQueryResult, { operation: T['operation'] }>
        >;
      case 'jobs_get_query_results':
        return this.handleJobsGetQueryResults() as Promise<
          Extract<BigQueryResult, { operation: T['operation'] }>
        >;
      case 'tabledata_insert_all':
        return this.handleTabledataInsertAll() as Promise<
          Extract<BigQueryResult, { operation: T['operation'] }>
        >;
      case 'datasets_list':
        return this.handleDatasetsList() as Promise<
          Extract<BigQueryResult, { operation: T['operation'] }>
        >;
      case 'tables_list':
        return this.handleTablesList() as Promise<
          Extract<BigQueryResult, { operation: T['operation'] }>
        >;
      default:
        return {
          operation: operation as T['operation'],
          success: false,
          error: `Unknown operation: ${String(operation)}`,
        } as Extract<BigQueryResult, { operation: T['operation'] }>;
    }
  }

  private async handleJobsQuery(): Promise<
    Extract<BigQueryResult, { operation: 'jobs_query' }>
  > {
    const params = BigQueryParamsSchema.parse(this.params) as Extract<
      BigQueryParams,
      { operation: 'jobs_query' }
    >;
    try {
      const token = this.chooseCredential();
      if (!token) {
        return {
          operation: 'jobs_query',
          success: false,
          error: 'BIGQUERY_TOKEN credential not found',
        };
      }
      const url = `${trimBaseUrl(params.endpointUrl)}/projects/${encodeURIComponent(params.projectId)}/queries`;
      const body = pruneUndefined({
        maxResults: params.maxResults,
        arrowSerializationOptions: params.arrowSerializationOptions,
        destinationEncryptionConfiguration:
          params.destinationEncryptionConfiguration,
        writeIncrementalResults: params.writeIncrementalResults,
        parameterMode: params.parameterMode,
        jobTimeoutMs: params.jobTimeoutMs,
        kind: params.kind,
        query: params.query,
        reservation: params.reservation,
        continuous: params.continuous,
        defaultDataset: params.defaultDataset,
        queryParameters: params.queryParameters,
        createSession: params.createSession,
        useQueryCache: params.useQueryCache,
        dryRun: params.dryRun,
        maxSlots: params.maxSlots,
        connectionProperties: params.connectionProperties,
        jobCreationMode: params.jobCreationMode,
        useLegacySql: params.useLegacySql,
        formatOptions: params.formatOptions,
        queryResultsFormat: params.queryResultsFormat,
        timeoutMs: params.timeoutMs,
        requestId: params.requestId,
        location: params.location,
        maximumBytesBilled: params.maximumBytesBilled,
        labels: params.labels,
        preserveNulls: params.preserveNulls,
      });
      const response = await fetch(url, {
        method: 'POST',
        headers: this.requestHeaders(token, true),
        body: JSON.stringify(body),
      });
      if (!response.ok) {
        const errorText = await response.text();
        return {
          operation: 'jobs_query',
          success: false,
          error: `bigquery API error (${response.status}): ${errorText}`,
        };
      }
      const payload = JobsQueryPayloadSchema.parse(await response.json());
      return { operation: 'jobs_query', success: true, error: '', ...payload };
    } catch (error) {
      return {
        operation: 'jobs_query',
        success: false,
        error:
          error instanceof Error ? error.message : 'Unknown error occurred',
      };
    }
  }

  private async handleJobsGetQueryResults(): Promise<
    Extract<BigQueryResult, { operation: 'jobs_get_query_results' }>
  > {
    const params = BigQueryParamsSchema.parse(this.params) as Extract<
      BigQueryParams,
      { operation: 'jobs_get_query_results' }
    >;
    try {
      const token = this.chooseCredential();
      if (!token) {
        return {
          operation: 'jobs_get_query_results',
          success: false,
          error: 'BIGQUERY_TOKEN credential not found',
        };
      }
      const query = buildQuery({
        'formatOptions.timestampOutputFormat':
          params['formatOptions.timestampOutputFormat'],
        'formatOptions.useInt64Timestamp':
          params['formatOptions.useInt64Timestamp'],
        location: params.location,
        maxResults: params.maxResults,
        pageToken: params.pageToken,
        startIndex: params.startIndex,
        timeoutMs: params.timeoutMs,
      });
      const url = `${trimBaseUrl(params.endpointUrl)}/projects/${encodeURIComponent(params.projectId)}/queries/${encodeURIComponent(params.jobId)}${query}`;
      const response = await fetch(url, {
        method: 'GET',
        headers: this.requestHeaders(token, false),
      });
      if (!response.ok) {
        const errorText = await response.text();
        return {
          operation: 'jobs_get_query_results',
          success: false,
          error: `bigquery API error (${response.status}): ${errorText}`,
        };
      }
      const payload = JobsGetQueryResultsPayloadSchema.parse(
        await response.json()
      );
      return {
        operation: 'jobs_get_query_results',
        success: true,
        error: '',
        ...payload,
      };
    } catch (error) {
      return {
        operation: 'jobs_get_query_results',
        success: false,
        error:
          error instanceof Error ? error.message : 'Unknown error occurred',
      };
    }
  }

  private async handleTabledataInsertAll(): Promise<
    Extract<BigQueryResult, { operation: 'tabledata_insert_all' }>
  > {
    const params = BigQueryParamsSchema.parse(this.params) as Extract<
      BigQueryParams,
      { operation: 'tabledata_insert_all' }
    >;
    try {
      const token = this.chooseCredential();
      if (!token) {
        return {
          operation: 'tabledata_insert_all',
          success: false,
          error: 'BIGQUERY_TOKEN credential not found',
        };
      }
      const url = `${trimBaseUrl(params.endpointUrl)}/projects/${encodeURIComponent(params.projectId)}/datasets/${encodeURIComponent(params.datasetId)}/tables/${encodeURIComponent(params.tableId)}/insertAll`;
      const body = pruneUndefined({
        ignoreUnknownValues: params.ignoreUnknownValues,
        skipInvalidRows: params.skipInvalidRows,
        templateSuffix: params.templateSuffix,
        traceId: params.traceId,
        rows: params.rows,
        kind: params.kind,
      });
      const response = await fetch(url, {
        method: 'POST',
        headers: this.requestHeaders(token, true),
        body: JSON.stringify(body),
      });
      if (!response.ok) {
        const errorText = await response.text();
        return {
          operation: 'tabledata_insert_all',
          success: false,
          error: `bigquery API error (${response.status}): ${errorText}`,
        };
      }
      const payload = TabledataInsertAllPayloadSchema.parse(
        await response.json()
      );
      return {
        operation: 'tabledata_insert_all',
        success: true,
        error: '',
        ...payload,
      };
    } catch (error) {
      return {
        operation: 'tabledata_insert_all',
        success: false,
        error:
          error instanceof Error ? error.message : 'Unknown error occurred',
      };
    }
  }

  private async handleDatasetsList(): Promise<
    Extract<BigQueryResult, { operation: 'datasets_list' }>
  > {
    const params = BigQueryParamsSchema.parse(this.params) as Extract<
      BigQueryParams,
      { operation: 'datasets_list' }
    >;
    try {
      const token = this.chooseCredential();
      if (!token) {
        return {
          operation: 'datasets_list',
          success: false,
          error: 'BIGQUERY_TOKEN credential not found',
        };
      }
      const query = buildQuery({
        all: params.all,
        filter: params.filter,
        maxResults: params.maxResults,
        pageToken: params.pageToken,
      });
      const url = `${trimBaseUrl(params.endpointUrl)}/projects/${encodeURIComponent(params.projectId)}/datasets${query}`;
      const response = await fetch(url, {
        method: 'GET',
        headers: this.requestHeaders(token, false),
      });
      if (!response.ok) {
        const errorText = await response.text();
        return {
          operation: 'datasets_list',
          success: false,
          error: `bigquery API error (${response.status}): ${errorText}`,
        };
      }
      const payload = DatasetsListPayloadSchema.parse(await response.json());
      return {
        operation: 'datasets_list',
        success: true,
        error: '',
        ...payload,
      };
    } catch (error) {
      return {
        operation: 'datasets_list',
        success: false,
        error:
          error instanceof Error ? error.message : 'Unknown error occurred',
      };
    }
  }

  private async handleTablesList(): Promise<
    Extract<BigQueryResult, { operation: 'tables_list' }>
  > {
    const params = BigQueryParamsSchema.parse(this.params) as Extract<
      BigQueryParams,
      { operation: 'tables_list' }
    >;
    try {
      const token = this.chooseCredential();
      if (!token) {
        return {
          operation: 'tables_list',
          success: false,
          error: 'BIGQUERY_TOKEN credential not found',
        };
      }
      const query = buildQuery({
        maxResults: params.maxResults,
        pageToken: params.pageToken,
      });
      const url = `${trimBaseUrl(params.endpointUrl)}/projects/${encodeURIComponent(params.projectId)}/datasets/${encodeURIComponent(params.datasetId)}/tables${query}`;
      const response = await fetch(url, {
        method: 'GET',
        headers: this.requestHeaders(token, false),
      });
      if (!response.ok) {
        const errorText = await response.text();
        return {
          operation: 'tables_list',
          success: false,
          error: `bigquery API error (${response.status}): ${errorText}`,
        };
      }
      const payload = TablesListPayloadSchema.parse(await response.json());
      return { operation: 'tables_list', success: true, error: '', ...payload };
    } catch (error) {
      return {
        operation: 'tables_list',
        success: false,
        error:
          error instanceof Error ? error.message : 'Unknown error occurred',
      };
    }
  }
}
